_F_installCss(".oYLlHe{display:-moz-box;display:flex;-moz-box-flex:1;flex-grow:1;overflow:clip}sentinel{}");
loaded_h_0(function(_){var window=this;
_.t("d6FVZd");

_.v();
_.cK=_.x("yb08jf",[]);_.Kc(_.cK);
_.t("yb08jf");
var nPe,oPe,pPe,qPe;nPe=function(a,b){a.oa.forEach(c=>{const d=b.filter(e=>c.elements.includes(e.target));d.length>0&&c.callback(d)})};oPe=function(a,b,c){const d=a.Aa++;if(a.Yh===void 0)return d;b=b instanceof _.lo?b.toArray():[b];a.oa.push({key:d,elements:b,callback:c});b.forEach(e=>{a.Yh.observe(e)});return d};
pPe=function(a,b){if(a.Yh!==void 0){var c=a.oa.filter(d=>d.key===b).flatMap(d=>d.elements);a.oa=a.oa.filter(d=>d.key!==b);c.filter(d=>!a.oa.flatMap(e=>e.elements).includes(d)).forEach(d=>{a.Yh.unobserve(d)})}};
qPe=class{constructor(){this.oa=[];this.Aa=1;const a=window;this.Yh=a.ResizeObserver===void 0?void 0:new a.ResizeObserver(b=>{nPe(this,b)})}pause(){this.Yh!==void 0&&this.Yh.disconnect()}resume(){this.Yh!==void 0&&this.oa.flatMap(a=>a.elements).forEach(a=>{this.Yh.observe(a)})}isSupported(){return this.Yh!==void 0}};_.rPe=function(a,b){pPe(a.Yh,b)};_.dK=class{constructor(){this.Yh=new qPe}oa(a,b){return oPe(this.Yh,a,b)}pause(){this.Yh.pause()}resume(){this.Yh.resume()}isSupported(){return this.Yh.isSupported()}};
_.Pe(_.dK,_.cK);
_.v();
_.gfC=_.x("Si45qc",[_.cK]);
var KLg,LLg,MLg,NLg,OLg,PLg,RLg,VLg,TLg,WLg,XLg,ULg,ZLg,YLg,bMg,aMg,cMg,dMg,QLg;KLg=function(a){let b;a=Number((b=a.trim().match(/^(\d+|\d+\.\d+)px$/))==null?void 0:b[1]);return isNaN(a)?null:a};LLg=function(a){return`linear(${a.map(([b,c])=>`${b} ${100*c}%`).join(",")})`};MLg=function(a,b){return b.map(([c,d])=>[(1/(c*(1-a)+a)-1/a)/(1-1/a),d])};NLg=function(a,b,c){return(1-a)*(1-a)*(1-a)*0+3*(1-a)*(1-a)*a*b+3*(1-a)*a*a*c+a*a*a};
OLg=function(a){const b=Number(a.split("%")[0])/100;if(isNaN(b))throw Error("tq`"+a);return b};
PLg=function(a,b){a=a.match(/linear\((.*)\)/i);const c=(a?a[1].split(",").map(e=>e.trim()):["0","1"]).map(e=>{e=e.split(" ");const f=Number(e[0]),g=[[f]];e.length>=2&&g[0].push(OLg(e[1]));e.length>=3&&g.push([f,OLg(e[2])]);return g}).flatMap(e=>e);c[0][1]=0;c[c.length-1][1]=1;for(let e=0;e<c.length;e++)if(c[e].length===1){var d=e-1;a=c.findIndex((g,h)=>h>e&&g[1]!==void 0);const f=(c[a][1]-c[d][1])/(a-d);d=c[d][1];for(let g=e;g<a;g++)d+=f,c[g][1]=d}return c.map(([e,f],g)=>{const h=[[e,f]];var k=c[g+
1];if(!k)return h;var l=k[1]-f;g=Math.ceil(l*b/8.3333333);l/=g;k=(k[0]-e)/g;for(let n=0;n<g-1;n++)f+=l,e+=k,h.push([e,f]);return h}).flatMap(e=>e)};
RLg=function(a,b,c){if(a===1)return b;c=Number(c);isNaN(c)&&(c=500);if(b.startsWith("linear("))b=PLg(b,c);else{a:{var d=QLg[b.trim().toLowerCase()];if(d)var e=d;else{try{var f=b.match(/cubic-bezier\s*\(\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*\)/i);if(f){e=f.slice(1).map(Number);break a}}catch(g){}e=QLg.linear}}b=e;e=2*Math.round(c/8.3333333);f=[];for(c=0;c<=e;c++)d=c/e,f.push([NLg(d,b[1],b[3]),NLg(d,b[0],b[2])]);b=f}a=MLg(a,b);return LLg(a)};
VLg=function(a="root",b=1,c=!1){const d=[];if(b===0)return d;const e=`::view-transition-group(${a})`,f=document.getAnimations().find(Z=>{let Y;return((Y=Z.effect)==null?void 0:Y.pseudoElement)===e});if(!f)return d;const g=f.effect,h=g.getKeyframes(),k=f.effect.getTiming().duration;if(h[1].width==="auto"){f.currentTime=k;var l=window.getComputedStyle(document.documentElement,e);var n=new DOMMatrix(l.transform);var q=KLg(l.width);l=KLg(l.height);f.currentTime=0}else n=new DOMMatrix(h[1].transform),
q=KLg(h[1].width),l=KLg(h[1].height);if(q===null||l===null)return d;var r=KLg(h[0].width);const u=KLg(h[0].height);if(r===null||u===null)return d;var B=new DOMMatrix(h[0].transform);let G=_.SLg(B);c&&(G=TLg(G,r,u,e));c=G.left;B=G.top;const L=G.aV,N=n.e;n=n.f;q=G.vR*(b===4?1:b===5?u/l:r/q);r=b===3||b===2?L*u/l:q;a!=="sb"&&(B+u<0||n+l<0)&&f.cancel();const T=[{transform:`translate(${c}px, ${B}px) scale(${q}, ${r})`,easing:h[0].easing,transformOrigin:"top left"},{transform:`translate(${N}px, ${n}px) scale(1, 1)`,
easing:h[1].easing,transformOrigin:"top left"}];d.push(()=>void g.setKeyframes(T));b===2&&d.push(...ULg({name:a,easing:h[0].easing,duration:k,oCe:q,pCe:r}));return d};_.SLg=function(a){return{left:a.e,top:a.f,vR:a.a,aV:a.d}};TLg=function(a,b,c,d){try{const e=window.getComputedStyle(document.documentElement,d).transformOrigin,{Gvd:f,dMd:g}=WLg(Object.assign({},{transformOrigin:e,width:b,height:c},a));if(isNaN(g)||isNaN(f))return a;a.left+=f;a.top+=g}catch(e){}return a};
WLg=function({transformOrigin:a,width:b,height:c,vR:d,aV:e}){a=XLg({transformOrigin:a,height:c,width:b});return a===null?{Gvd:0,dMd:0}:{Gvd:a.Hvd*(1-d),dMd:a.eMd*(1-e)}};XLg=function({transformOrigin:a,height:b,width:c}){const d=a.match(/(-?\d+\.?\d*)px (-?\d+\.?\d*)px/);if(d){const [,e,f]=d;return{Hvd:Number(e),eMd:Number(f)}}if(a=a.match(/(-?\d+\.?\d*)% (-?\d+\.?\d*)%/)){const [,e,f]=a;return{Hvd:c*Number(e)/100,eMd:b*Number(f)/100}}return null};
ULg=function({name:a,easing:b,duration:c,oCe:d,pCe:e}){const f=[];if(e===1)return f;const g=`::view-transition-image-pair(${a})`;b=RLg(e,b,c);const h=[{transformOrigin:"top left",transform:`scale(1, ${d/e})`},{transformOrigin:"top left",transform:"scale(1, 1)"}],k={duration:c,easing:b};f.push(()=>{try{document.documentElement.animate(h,Object.assign({},k,{pseudoElement:g}))}catch(n){n.details={src:"spa-vt-c-cs",kf:JSON.stringify(h),o:JSON.stringify(k),pe:g},n.h1d=2}});const l=`::view-transition-group(${a})`;
a=window.getComputedStyle(document.documentElement,l).borderRadius;a=KLg(a);if(a!==null){const n=[{borderRadius:`${a/d}px / ${a/e}px`},{borderRadius:`${a}px`}],q={duration:c,easing:b};f.push(()=>{try{document.documentElement.animate(n,Object.assign({},q,{pseudoElement:l}))}catch(r){r.details={src:"spa-vt-c-br",kf:JSON.stringify(n),o:JSON.stringify(q),pe:l},r.h1d=2}})}return f};ZLg=function(a){return document.startViewTransition?document.startViewTransition(a):YLg(a)};
YLg=function(a){a=Promise.resolve(a()).then(()=>{});return{ready:Promise.resolve(),updateCallbackDone:a,finished:a,skipTransition:()=>{}}};
bMg=function(a,b={}){const c=document.createElement("style");document.head.prepend(c);const d=[];var e;const f=(e=b.groups)!=null?e:[],g=[...f];b.root&&(b.root.viewTransitionName="root",g.unshift(b.root));var h;((h=b.root)==null?0:h.disable)&&_.$Lg(c,":root",{viewTransitionName:"none"});for(e=0;e<f.length;e++){h=f[e];const l=`${"spa-vt-"}${e}`;h.viewTransitionName=l;h.element&&(h.element.style.viewTransitionName=l)}const k=ZLg(async()=>{try{const l=g.map(n=>{let q;return(q=n.cF)==null?void 0:q.call(n)}).filter(n=>
n);_.y(await _.y(Promise.all([a(),...l])));for(const n of f)n.Zya===void 0&&(n.Zya=n.ifb?n.ifb():n.element),n.element&&(n.element.style.viewTransitionName=""),n.Zya&&(n.Zya.style.viewTransitionName=n.viewTransitionName)}finally{_.y()}});g.forEach(l=>{let n;return void(l==null?void 0:(n=l.k6f)==null?void 0:n.resolve(k))});k.updateCallbackDone.catch(()=>{});k.ready.then(()=>{for(var l of f)l.Zya&&(l.Zya.style.viewTransitionName="");if(l=b.keyframes)for(var n of l){l=c.sheet.insertRule(`@keyframes ${n.name} {}`);
l=c.sheet.cssRules[l];for(const [q,r]of Object.entries(n.keyframes)){const u=r;l.appendRule(`${q} {}`);const B=l.cssRules[l.cssRules.length-1];for(const G in u)u.hasOwnProperty(G)&&(B.style[G]=u[G])}}n=[b.root,...f];for(const q of n)d.push(...aMg(c,q));for(const q of n){let r;((r=q)==null?0:r.hwa)&&d.push(...VLg(q.viewTransitionName,q.hwa,q.x9c))}for(const q of d)q()},()=>{});k.finished.catch(()=>{});k.finished.finally(()=>{for(const l of f)l.element&&(l.element.style.viewTransitionName=""),l.Zya&&
(l.Zya.style.viewTransitionName="");c.remove()});return k};aMg=function(a,b){if(!b)return[];const c=b.viewTransitionName;return[cMg(a,c,"old",b.Cta),cMg(a,c,"new",b.new),cMg(a,c,"group",b.group),cMg(a,c,"image-pair",b.lWf)].flatMap(d=>d)};
cMg=function(a,b,c,d){const e=[];if(!d)return e;d.animation&&(e.push(dMg(b,c,d.animation)),d.styles=d.styles||{},d.styles.animation="none");let f;(f=d.u9c)==null||f.forEach(g=>{e.push(dMg(b,c,g))});d.styles&&_.$Lg(a,`${"::view-transition"}-${c}(${b})`,d.styles);return e};dMg=function(a,b,c){const d=`${"::view-transition"}-${b}(${a})`;return()=>document.documentElement.animate(c.keyframes,Object.assign({},c.options,{pseudoElement:d}))};
_.$Lg=function(a,b,c){b=a.sheet.insertRule(`${b} {}`);a=a.sheet.cssRules[b];for(const d in c)c.hasOwnProperty(d)&&(a.style[d]=c[d]);return a};_.fMg=function(a,b){if(_.eMg)return YLg(a);_.Mf(document.body,"iGTUtd");a=bMg(a,b);a.finished.then(()=>{_.Mf(document.body,"NJClW")});return a};QLg={linear:[0,0,1,1],ease:[.25,.1,.25,1],"ease-in":[.42,0,1,1],"ease-out":[0,0,.58,1],"ease-in-out":[.42,0,.58,1]};_.eMg=!!(_.uh[64]>>24&1);_.gMg=!!(_.uh[64]>>25&1);_.hMg=!!document.startViewTransition;
_.e1c=function(){return _.Jl("center_col")};
_.t("Si45qc");
var O2E=function(a,b){a=Number(a.getAttribute("data-r"));b=Number(b.getAttribute("data-r"));return a-b};var P2E={Tgd:_.gMg,vce:!!(_.uh[39]&4096)},Q2E=function(a){if(a.oa){var b=_.Tl();a=a.oa.getBoundingClientRect();b.height<=a.bottom?window.scrollTo({top:window.scrollY+a.bottom-b.height+40,behavior:"auto"}):80>=a.top&&window.scrollTo({top:window.scrollY+a.top-80,behavior:"auto"})}},S2E=function(a){const b=a.Dv.oa(a.container,c=>{[c]=c;c.contentRect.width!==a.containerWidth&&(a.containerWidth=c.contentRect.width,a.Dv.pause(),R2E(a),(0,_.Tn)(()=>void a.Dv.resume(),0))});a.addOnDisposeCallback(()=>{_.rPe(a.Dv,
b)})},R2E=function(a){const b=T2E(a);b.hide();let c=-1,d=-1,e=0;for(_.mo(a.container.children(),f=>{if(!(f.hasClass("Tv90E")||f.kb().offsetTop<=c)){c=f.kb().offsetTop;d++;var g=_.ZOa(b,e);g==null||Number(g.getAttribute("data-r"))>d||(f.before(g),e++)}});e<b.size();)a.container.append(b.eq(e)),e++;b.show()},T2E=function(a){a=_.no(a.container.find(".Tv90E")).sort(O2E);return new _.lo(a)},U2E=class extends _.Tr{static Sa(){return{service:{Dv:_.dK}}}constructor(a){super(a.Oa);this.containerWidth=0;this.oa=
null;this.Da=()=>{if(P2E.Tgd){const b=[],c=this.getRoot().el().querySelectorAll('[jsname="dTDiAc"]');for(const d of c)b.push({element:d});_.fMg(()=>{this.Ba.classList.add("xKxVbb")},{groups:b})}else this.Ba.classList.add("xKxVbb")};this.Ca=()=>{if(P2E.Tgd){const b=[],c=this.getRoot().el().querySelectorAll('[jsname="dTDiAc"]');for(const d of c)b.push({element:d});_.fMg(()=>{this.Ba.classList.remove("xKxVbb")},{groups:b})}else this.Ba.classList.remove("xKxVbb");Q2E(this)};this.Ea=b=>{const c=b.detail.id;
b=b.detail.k;if(c==="mosaic"||c==="regis"){if(c==="regis"){let d,e,f;this.oa=(f=(d=this.container.children().filter(_.io("jsname","yk2ZCc")))==null?void 0:(e=d.toArray())==null?void 0:e[0])!=null?f:null}else this.oa=b<this.Aa.length?this.Aa[b]:this.oa;Q2E(this)}};this.Dv=a.service.Dv;this.Ba=_.e1c();this.container=_.po(this.getRoot(),".jFk0f");a=this.Ya("BRTknd");this.Pn=a.isEmpty()?new _.lo([]):_.bRa(a,"GDPwke");this.Pn.setStyle("visibility","hidden");this.Aa=this.container.children().filter(_.ho("ivg-i")).toArray();
document.addEventListener("viewerOpened",this.Da);document.addEventListener("viewerClosed",this.Ca);document.addEventListener("viewerUpdated",this.Ea);this.addOnDisposeCallback(()=>{document.removeEventListener("viewerOpened",this.Da);document.removeEventListener("viewerClosed",this.Ca);document.removeEventListener("viewerUpdated",this.Ea)});P2E.vce&&S2E(this)}Ha(a){const b=_.po(this.Pn,".jFk0f"),c=!b.isEmpty();if(c){var d=this.container.children().last();d&&d.setStyle("flex-grow","10000");d=b.children();
this.Aa=this.Aa.concat(d.filter(_.ho("ivg-i")).toArray());const e=Math.min(10,d.size());for(let f=0;f<e;f++)d.eq(f).setStyle("flex-grow","10000");d.appendTo(this.container);this.notify("k7WJpc")}!a.data&&(a=this.container.children().last())&&(a.setStyle("visibility","visible"),a.setStyle("height","unset"),c&&a.setStyle("flex-grow","1"));b.remove()}};U2E.prototype.$wa$T13UJb=function(){return this.Ha};_.Ie.getInstance().register(_.gfC,U2E);
_.v();
_.t("IoGlCf");
_.tLc=new _.Me(_.d0a);
_.v();
_.rz=_.x("C8HsP",[_.d0a]);
_.nCb={xNf:0,yNf:5,DMf:7,gNf:10,uMf:9,RMf:11,rMf:13,nMf:14,vMf:15,ZMf:16,wNf:17,jNf:18,pMf:19,oMf:25,fNf:36,EMf:20,uNf:21,mNf:22,zMf:23,sMf:24,bNf:26,cNf:54,iNf:27,kNf:28,nNf:29,AMf:31,rNf:32,KMf:33,tNf:34,aNf:35,CMf:37,WMf:1E5,SMf:100001,TMf:100002,UMf:100003,XMf:100004,VMf:100005,qNf:30,lNf:38,BNf:39,BMf:40,hNf:41,wMf:42,OMf:43,PMf:59,MMf:44,IMf:45,JMf:46,jMf:47,xMf:48,sNf:49,eNf:50,HMf:51,oNf:52,kMf:53,tMf:55,zNf:56,lMf:57,ANf:69,LMf:58,qMf:60,QMf:61,NMf:62,yMf:63,GMf:64,pNf:65,mMf:66,FMf:67,dNf:68,
vNf:70,YMf:71};
_.t("C8HsP");
var uLc;_.sz=new Set;uLc=function(a,b){b.Da()||(a=_.Cf(a.getRoot().el(),c=>c instanceof Element&&_.Ve(c,"ved"),!0))&&(a=_.Te(a,"ved"))&&b.Aa(a)};_.tz=function(a,b){let c;a.getRoot().el().setAttribute("data-vhid",(c=b==null?void 0:b.OV())!=null?c:"");uLc(a,b);a.Ha.resolve(b);a.OPc(b)};_.uz=function(a,b,c){uLc(a,c);a.Aa.set(b,c);a.Da=!0};
_.vLc=function(a,b,c,d){if(b.event){var e;let k;(k=(e=b.event).preventDefault)==null||k.call(e);let l,n;(n=(l=b.event).stopPropagation)==null||n.call(l)}c&&uLc(a,c);var f;d=d?(f=_.Te(d,"ved"))!=null?f:void 0:void 0;f=a.Ca(b);let g,h;e=((g=b.qb)==null?0:g.el())?_.Ve((h=b.qb)==null?void 0:h.el(),"hsr"):!1;a.trigger("aevozb",{mJe:c,interactionVed:d,interactionContext:f,aha:e})};
_.vz=class extends _.Tr{static Sa(){return{service:{vIa:_.tLc}}}constructor(a){super(a.Oa);this.Aa=new Map;this.Da=!1;this.Ha=_.re();this.vIa=a.service.vIa;this.trigger("k7WJpc")}Pa(a){a.data.element?_.uz(this,a.data.element,a.data.qo):_.tz(this,a.data.qo)}async lz(){return await this.Ha.promise}Oc(a){if(this.Da){let b=a.targetElement.el();const c=this.getRoot().el();for(;b&&b!==c;){if(this.Aa.has(b))return _.vLc(this,a,this.Aa.get(b),b),!1;b=b.parentElement}c&&this.Aa.has(c)?_.vLc(this,a,this.Aa.get(c),
c):_.vLc(this,a)}else _.vLc(this,a);return!1}Ca(a){return(a=a.qb.el())?Number(_.Te(a,"ictx"))||void 0:void 0}OPc(a){let b;(a=(b=a.Ba())==null?void 0:b.getViewerType())&&_.sz.has(a)&&this.vIa.OPc(a)}async sOa(a){this.trigger("vcOT6c",a)}Ta(){return!1}};_.vz.prototype.$wa$M5Scjd=function(){return this.Ta};_.vz.prototype.$wa$zYAnae=function(){return this.Ca};_.vz.prototype.$wa$h5M12e=function(){return this.Oc};_.vz.prototype.$wa$mKCalb=function(){return this.lz};_.vz.prototype.$wa$kNqZ1c=function(){return this.Pa};
_.Ie.getInstance().register(_.rz,_.vz);
_.sz.add(10);_.sz.add(15);_.sz.add(16);_.sz.add(18);_.sz.add(19);_.sz.add(25);_.sz.add(36);_.sz.add(21);_.sz.add(22);_.sz.add(23);_.sz.add(24);_.sz.add(26);_.sz.add(27);_.sz.add(28);_.sz.add(29);_.sz.add(31);_.sz.add(40);_.sz.add(32);_.sz.add(33);_.sz.add(35);
_.v();
_.rMc=_.x("gOTY1",[_.mxa,_.d0a]);
_.Pz=class extends _.m{constructor(a){super(a)}};_.Pz.prototype.ob="PFrTzf";
_.JLc=function(a,b){return _.Vh(a,1,_.yz,b)};_.KLc=function(a){return _.fi(a,_.mu,1,_.HLc)};_.Fz=function(a,b){return _.ji(a,1,_.HLc,b)};_.Mz=function(a,b){return _.Sf(a,3,b)};_.LLc=function(a,b){return _.Sf(a,7,b)};_.MLc=_.Mb(_.Ez);
_.t("gOTY1");
var sMc=function(a){const b=a.getRoot().el();a=[...b.querySelectorAll('[data-viewer-entrypoint]:not([data-nv="1"])')];return a.length===0?a:a.filter(c=>{for(c=c.parentElement;c!==null&&c!==b;){if(c.hasAttribute("data-viewer-group"))return!1;c=c.parentElement}return!0})},uMc=async function(a,b,c=null,d=null){try{const e=_.y(await _.y(Promise.all(b.map(k=>tMc(a,k))))),f=new Set,g=e.filter(k=>f.has(k.OV())?!1:(f.add(k.OV()),!0)),h=_.QLc(_.OLc(new _.Nz,g),a.streamId);a.Hjc&&h.setQuery(a.Hjc);if(c&&d){const k=
b.indexOf(c);k>=0&&_.Yh(h,1,_.Ez,k,d)}return h}finally{_.y()}},tMc=function(a,b){if(a.Ca.has(b))return a.Ca.get(b);const c=vMc(a,b);a.Ca.set(b,c);return c},vMc=async function(a,b){try{if(_.mMc)try{return _.y(await _.y(a.xl.resolve(b,_.Ez)))}catch(c){_.y()}return _.y(await _.y(a.wc(b,_.zo))).lz()}finally{_.y()}},wMc=class extends _.Tr{static Sa(){return{service:{xl:_.aYa,vIa:_.tLc},Hf:{Pna:_.Pz}}}constructor(a){super(a.Oa);this.Ca=new Map;this.oa=[];this.Ba=this.Aa=null;this.Da=Promise.resolve();this.xl=
a.service.xl;this.vIa=a.service.vIa;let b,c;this.streamId=(c=(b=_.nl(this.getData("id")))!=null?b:_.nl(this.getData("vssid")))!=null?c:"global";this.Hjc=_.nl(this.getData("q"));this.Pna=a.Hf.Pna;_.mMc||this.zn(this.initialize(),_.bo)}async initialize(){try{const a=sMc(this);_.y(await _.y(this.registerStream(a)))}finally{_.y()}}async rwb(a){try{const c=a.targetElement.el();var b;const d=(b=a.data.mJe)!=null?b:null;b=d?c:null;let e=void 0;if(_.mMc){const h=sMc(this);e=_.y(await _.y(uMc(this,h,b,d)))}else this.Aa===
b&&this.Ba===d||_.y(await _.y(this.registerStream(this.oa,b,d)));const f=d!=null?d:_.y(await _.y(tMc(this,c)));let g;_.y(await _.y(this.vIa.navigateToView({streamId:this.streamId,historyId:f.OV(),resultElement:c,mJb:_.sua(a)+_.gg,hWc:_.ti(f,5),interactionVed:a.data.interactionVed,interactionContext:a.data.interactionContext,replace:!!a.data.aha,Pna:(g=this.Pna)!=null?g:void 0,stream:e})))}finally{_.y()}}bIc(a){this.vIa.sOa(a.data)}async Ea(a){try{const b=a.targetElement.el();if(!_.mMc&&!this.oa.includes(b)){const c=
sMc(this);_.y(await _.y(this.registerStream(c,this.Aa,this.Ba)))}}finally{_.y()}}async Ha(){try{if(!_.mMc){const a=sMc(this);_.y(await _.y(this.registerStream(a,this.Aa,this.Ba)))}return!0}finally{_.y()}}async registerStream(a,b=null,c=null){try{const d=this.oa;this.oa=a;this.Aa=b;this.Ba=c;const e=this.Da,f=new _.fh;this.Da=f.promise;_.y(await _.y(e));const g=_.y(await _.y(uMc(this,a,b,c)));a.length>0&&d.length===0?_.y(await _.y(this.vIa.registerStream(this,g))):_.y(await _.y(this.vIa.eWe(this,g)));
f.resolve()}finally{_.y()}}Ub(){_.mMc||this.vIa.hpc(this,this.streamId)}};wMc.prototype.$wa$k4Iseb=function(){return this.Ub};wMc.prototype.$wa$sCDZjb=function(){return this.Ha};wMc.prototype.$wa$beCLof=function(){return this.Ea};wMc.prototype.$wa$C6KsF=function(){return this.bIc};wMc.prototype.$wa$T2P31d=function(){return this.rwb};_.Ie.getInstance().register(_.rMc,wMc);
_.v();
_.hfC=_.x("sFFyCd",[]);
_.t("sFFyCd");
var V2E=class extends _.m{constructor(a){super(a)}};V2E.prototype.ob="JDto1e";_.W2E=class extends _.ih{static Sa(){return{jsdata:{BKe:V2E}}}constructor(a){super();a=this.data=a.jsdata.BKe;var b=_.Ol("GMFBpe",this.Ca());b=b.length===1?_.Te(b[0],"incompleteRowData")||"0":"0";_.Sf(a,3,b)}};_.Gr(_.hfC,_.W2E);
_.v();
_.ifC=_.x("XW992c",[_.hfC,_.Qk]);
_.t("XW992c");
var X2E=class extends _.Tr{static Sa(){return{model:{vAc:_.W2E},service:{Tb:_.Gu}}}constructor(a){super(a.Oa);this.vAc=a.model.vAc;this.Tb=a.service.Tb;var b=this.vAc.data;if(a=_.dg(document.body,document.body,"BRTknd")[0])b={DEe:_.sd(b,1),EMa:_.A(b,3)},_.Jf(a,"QEvNdb",b)}oa(){const a=this.Ia("xMkiWb"),b=this.Ia("qVH5fe"),c=this.Ya("R5j3Z").first();a.show();b.hide();c&&c.show();c?_.Ap(_.Ap(_.pFb(_.yp(this.Tb.oa(),b.el()),b.el()),a.el()),c.el()).log():_.Ap(_.pFb(_.yp(this.Tb.oa(),b.el()),b.el()),a.el()).log();
this.notify("XGRTMd")}};X2E.prototype.$wa$Dl4LN=function(){return this.oa};_.Ie.getInstance().register(_.ifC,X2E);
_.v();
_.t("G6wU6e");
_.mtF=new _.Me(_.o0a);
_.v();
_.oG=class extends _.m{constructor(a){super(a,2)}fu(){return _.$f(this,_.mG,1,_.ag())}};_.oG.prototype.ob="U9CFPc";_.Ike=[-2,{},_.F,_.Fke];
_.xG=class extends _.m{constructor(a){super(a)}qOb(){return _.xd(this,_.oG,2)}};_.xG.prototype.ob="X2sNs";
_.Jke=function(a,b){return _.Sf(a,1,b)};_.Kke=function(a,b){return _.Bb(a,_.mG,2,b)};_.Lke=function(a){return _.p(a,_.uke,15)};_.Mke=_.Mb(_.mG);_.Nke=_.Mb(_.nG);new _.gh(_.mG);_.To.XZxcdf=function(a){return _.Uo(_.Vo(_.ske(a)))};new _.gh(_.oG);_.To.U9CFPc=_.So;_.Hq(_.oG,_.mG,function(a){return a.fu()});_.pG=_.Cb(444383007,_.wz,_.nG);_.xz[444383007]=_.Hke;var Oke=new _.gh(_.nG);Oke.Wa=new _.gh(_.xke);Oke.wb=_.pG;_.To.j0Opre=function(a){return _.Uo(_.Vo(a.Cf()))};_.Hq(_.nG,_.mG,function(a){a=a.getImage();return a!=null?[a]:[]});_.Hq(_.nG,_.xke,function(a){a=a.lDa();return a!=null?[a]:[]});_.To.IRVcEb=function(a){return _.Uo(_.Vo(a.Cf()))};
_.Sne=function(a){return(0,_.Nke)(a)?a.getId():(0,_.MLc)(a)?a.OV():a.getUniqueId()};
_.Rne=_.x("Wn3aEc",[]);
_.t("Wn3aEc");
var Tne;Tne=function(a){if((0,_.Mke)(a))return a;if((0,_.MLc)(a)){let c,d;a=(c=a.Ca())==null?void 0:(d=c.we())==null?void 0:d.getExtension(_.pG);if(!a)return null}let b;return a.getType()===1?(b=a.getImage())!=null?b:null:null};
_.Une=class extends _.ih{static Sa(){return{Hf:{hqc:_.xG}}}constructor(a){super();this.oa=a.Hf.hqc;this.Aa=_.re();this.Ba=_.re();this.results=new Map;a:{if(this.getData("vnora").Lb()){a=_.Ol("WA6vPb",this.Ca());if(a.length===1){a=Number(_.Te(a[0],"count"));break a}a=_.Ol("LgL7He",this.Ca());if(a.length===1){a=Number(_.Te(a[0],"count"));break a}}a=_.Yc(this.getData("count"),-1)}this.Da=a}Fca(){if(this.Da<0){const a=this.oa?_.p(this.oa,_.oG,2):null;return a?_.tf(a.fu()):_.tf([])}return this.Aa.promise}fu(){return this.Fca().then(a=>
a.map(Tne).filter(b=>b!=null))}SGc(){return this.Ba.promise}jie(){return this.SGc().then(a=>{const b=new Map;for(const [c,d]of a){a=c;const e=Tne(d);e&&b.set(a,e)}return b})}fA(a,b){b&&_.Sne(b)&&this.results.set(a,b);if(--this.Da===0){this.Aa.resolve(Array.from(this.results.entries()).sort((c,d)=>_.mHa(c[0],d[0])).map(c=>c[1]));a=new Map;for(const [c,d]of this.results.entries()){b=c;const e=d;e&&a.set(b,e)}this.Ba.resolve(a)}}};_.Gr(_.Rne,_.Une);
_.v();
_.vhC=_.x("Um3BXb",[_.Rne]);
_.Nwv=!!(_.uh[27]&512);_.Owv=!!(_.uh[27]&1024);_.Pwv=!!(_.uh[27]&2048);_.Qwv=!!(_.uh[27]&8192);
_.sTe=!!(_.uh[38]>>25&1);_.tTe=!!(_.uh[38]>>29&1);_.uTe=!!(_.uh[39]&2);_.vTe=!!(_.uh[39]&32);_.wTe=!!(_.uh[39]&512);
_.mz=function(a,b=!1,c){var d=a.getRoot().el();_.Jf(d,"EormBc",new mKc(a,b,c))};_.nKc=function(a,b=!1,c=!1){a=a.getRoot().el();_.Jf(a,"EormBc",{logVisibility:b,Oe:c,JG:void 0})};var mKc=class{constructor(a,b,c){this.logVisibility=b;this.JG=c;this.kga=a}};
_.t("Um3BXb");
var qtF,otF,rtF;_.ptF=function({construct:a}){otF.push({construct:a})};qtF=_.Ob(_.nG);otF=[];
rtF=class extends _.Tr{static Sa(){return{model:{baa:_.Une},Hf:{gWc:_.nG}}}constructor(a){super(a.Oa);this.oa=!this.getData("ni").Lb();this.zs=a.Hf.gWc;if((this.Ba=this.getData("au").Lb())&&this.zs){var b=(b=this.getRoot().closest(_.io("jsname","uK8Ylc")).el())?_.Te(b,"ved"):null;const e=qtF(this.zs.serialize());if(b&&e&&e.Rj()){var c;(c=e.getImage())!=null&&_.Sf(c,5,b)}this.zs=e}a.model.baa.fA(this.getRoot().el(),this.zs);_.mz(this);let d;(c=(d=this.zs)==null?void 0:d.getImage())&&this.trigger("cEfxe",
c==null?void 0:c.getUniqueId());this.B2(a)}L4a(){let a,b;return(b=(a=this.zs)==null?void 0:a.getImage())!=null?b:null}Ca(a){var b=a.targetElement.parent();a=_.Pl("srrRv",this.getRoot().el());b=_.Yr(this,b.eq(0),"YsWoif").el();_.Lv([new _.Nn(b,"show")],{triggerElement:b,userAction:9});_.Mf(b,"BUYwVb");a==null&&_.rm(b,"display","inline-block")}Da(a){const b=a.targetElement;a=a.targetElement.parent();a=_.Yr(this,a.eq(0),"YsWoif").el();_.Lv([new _.Nn(a,"hide")],{triggerElement:b.eq(0).el(),userAction:9});
_.rm(a,"display","none")}Oc(a){if(this.zs&&this.zs.getId()){var b,c;(c=(b=a.event).preventDefault)==null||c.call(b);var d,e;(e=(d=a.event).stopPropagation)==null||e.call(d);this.trigger("PdWSXe",{Lv:a.event});var f;(a=(f=this.zs)==null?void 0:f.getImage())&&this.trigger("Kc2lDe",a==null?void 0:a.getUniqueId())}}Df(){this.notify("BUYwVb")}hf(){this.oa||(_.Lv([new _.Nn(this.getRoot().el(),"show")]),this.oa=!0)}hidden(){}B2(a){for(const b of otF)b.construct(this,a)}Aa(){this.notify("BUYwVb");const a=
!_.Nwv;this.getRoot().setStyle("display",a?"inline-flex":"unset");this.getRoot().removeAttr("aria-hidden");this.hf()}};rtF.prototype.$wa$bNsLWe=function(){return this.Aa};rtF.prototype.$wa$L6cTce=function(){return this.hidden};rtF.prototype.$wa$TSZdd=function(){return this.hf};rtF.prototype.$wa$AwdEqd=function(){return this.Df};rtF.prototype.$wa$h5M12e=function(){return this.Oc};rtF.prototype.$wa$XEuVS=function(){return this.Da};rtF.prototype.$wa$RrAr1=function(){return this.Ca};
rtF.prototype.$wa$TsqBdc=function(){return this.L4a};_.Ie.getInstance().register(_.vhC,rtF);
var stF=function(a,b,c,d){const e=a.Ya("tdeeNb");e.isEmpty()||(d=new _.En(_.dl(d.url)),c=d.get("imgrc")===c&&!d.get("imgdii")||d.get("vhid")===c,c||(a=a.getRoot(),e.hasClass("srrRv")&&(d=e.prev(),b.gze(a,d))),e.toggleClass("srrRv",c))},utF=function(a,b){if(!a.closest(g=>ttF.some(h=>g.classList.contains(h))).isEmpty()){var c=a.el().getBoundingClientRect();a=a.parent();a.hasClass("dECn0b")&&(a=a.closest(".T62xob"));var d=a.el().getBoundingClientRect();a=c.top===d.top;var e=Math.abs(d.bottom-c.bottom)<
8,f=Math.abs(d.left-c.left)<8;c=Math.abs(d.right-c.right)<8;b.toggleClass("Xn9Tkc",a&&f);b.toggleClass("oGwWse",a&&c);b.toggleClass("y0jvId",e&&c);b.toggleClass("lM9tvf",e&&f)}},ttF=["DhGrzc","l5X1Ye","o6uAG","OXEsB","T62xob"];
_.ptF({construct(a){const b=_.nl(a.getData("docid"));b&&(_.wTe?(document.addEventListener("viewerUpdated",f=>{f=f.detail.vhid.replace("e-","")===b;a.Ya("tdeeNb").toggleClass("srrRv",f)}),document.addEventListener("viewerClosed",()=>{a.Ya("tdeeNb").toggleClass("srrRv",!1)})):_.hg(a,{service:{wJc:_.zG,focus:_.mtF}}).then(f=>{const g=f.service.focus;f=f.service.wJc;f.addListener(h=>{stF(a,g,b,h)});stF(a,g,b,f.getState())},f=>void _.Yd(f)));const c=a.getRoot();_.Ef(c.el(),"qWWJ8e",()=>{utF(c,a.Ya("tdeeNb"))});
utF(c,a.Ya("tdeeNb"));let d=null;const e=a.Ya("qQjpJ").el();e&&(e.addEventListener("mouseenter",()=>{d===null&&(d=(0,_.Tn)(()=>{c.toggleClass("dB3j8",!0);d=null},50))}),e.addEventListener("mouseleave",()=>{d&&((0,_.Un)(d),d=null);c.toggleClass("dB3j8",!1)}))}});
_.v();
_.ooe=function(a){return _.Hg(a,1,2)};_.poe=function(a){return _.Hg(a,2,2)};_.qoe=function(a,b){return _.Hg(a,3,b)};
_.Zne=function(a,b){return _.Sf(a,9,b)};_.$ne=function(a,b){return _.Sf(a,10,b)};_.aoe=function(a,b){return _.Sf(a,12,b)};_.boe=function(a,b){return _.lh(a,2,b)};_.coe=function(a,b){return _.lh(a,3,b)};_.doe=function(a,b){return _.Hg(a,1,b)};_.eoe=function(a,b){return _.Sf(a,2,b)};var foe=[0,_.E,_.D];var goe=[0,_.E,_.rk,_.C,_.E];var hoe=class extends _.m{constructor(a){super(a)}};hoe.prototype.ob="IV0Wqf";var ioe=[0,_.E,-1];_.joe=function(a,b){return _.Sf(a,3,b)};_.koe=function(a,b){return _.Sf(a,4,b)};_.loe=function(a,b){return _.Sf(a,13,b)};_.moe=function(a,b){return _.Sf(a,18,b)};
_.noe=class extends _.m{constructor(a){super(a,37)}tF(){return _.A(this,3)}O5(){return _.ti(this,3)}pB(){return _.A(this,4)}Yra(){return _.ti(this,4)}Xe(){return _.A(this,5)}xu(){return _.xj(this,5)}vv(){return _.A(this,11)}wF(){return _.A(this,13)}KLa(){return _.ti(this,13)}Teb(){return _.A(this,18)}Hl(){return _.A(this,31)}awb(){return _.p(this,hoe,32)}};_.noe.prototype.ob="onFC6b";_.yG=_.Cb(2003,_.mG,_.noe);_.tke[2003]=[-37,{},_.E,-4,_.D,1,_.E,1,_.D,_.E,_.D,_.E,4,_.E,goe,1,foe,1,_.D,1,_.D,2,_.D,_.E,1,_.E,ioe,1,_.E,_.vo,_.D];
var Xne=class extends _.m{constructor(a){super(a)}};Xne.prototype.ob="LMXOyf";_.Yne=_.Cb(2009,_.mG,Xne);_.tke[2009]=[0,_.D];
_.t("cNgdQc");
var roe;
_.soe=function(a){if(a){var b=a.getImage(),c,d=b==null?void 0:(c=b.getExtension(_.yG))==null?void 0:c.tF(),e;d&&((e=_.cl(d))==null?0:e.match(/\.gstatic\.com$/))&&_.rEa(d)==="/licensed-image"&&(b==null||_.doe(b,18));switch(b==null?void 0:_.Wi(b,1)){case 16:c=a.Ba;d=new _.vke;d=_.Jg(d,5,!0);d=_.Hg(d,6,2);c=c.call(a,d);d=c.Aa;e=roe();e=_.Jg(e,5,!0);d.call(c,e);break;case 9:case 19:a.Aa(roe());break;case 18:c=a.Aa;d=new _.uke;d=_.Hg(d,4,2);c.call(a,_.poe(_.ooe(d)));break;case 20:a.Aa(_.ooe(_.poe(new _.uke)))}var f,g;
c=(g=b==null?void 0:_.z(b,9))!=null?g:!1;g=(b==null?void 0:_.xi(b,1))===18;!c&&!g&&(b==null?void 0:(f=b.Te(_.Yne))==null?void 0:_.Kg(f,1))!==!0||_.qoe(a.Ca(),2)}};_.toe=function(a){a&&(a.oa(_.yG,a.Te(_.yG)||new _.noe),a=a.getExtension(_.yG),a.wF()||_.loe(a,a.Teb()||_.cl(a.tF()||"")))};roe=function(){var a=_.qoe(_.poe(new _.uke),2);a=_.Hg(a,4,2);a=_.Hg(a,7,2);return _.Hg(a,8,2)};
_.v();
_.t("K02r3e");

_.v();
_.L2q=_.x("qKrDxc",[_.hr,_.Tq,_.dr,_.Qk,_.rz]);
var Wpe;
_.Xpe=function(a,b,c,d,e){var f=(a==null?void 0:a.Ha())||"";if(!f){var g,h,k;if(a=(h=(g=a.Ca())==null?void 0:g.we())==null?void 0:(k=h.Te(_.pG))==null?void 0:k.getImage()){f=a;a=(0,_.Nke)(f)?f.getImage():f;g=(f=a.Te(_.yG))&&_.Tf(f,2);h=f&&_.Tf(f,3);k=_.Tf(a,2);var l=a.lJ();a=l?_.pke(l):"";const n=l?_.rke(l):"";l=l?_.qke(l):"";if(!g||!h||!k)throw Error("Ym");b=new Map([["q",b],["imgurl",a],["imgrefurl",h],["docid",g],["tbnid",k],["vet",1],["w",n],["h",l],["hcb","2"]]);_.z(f,10)&&b.set("itg",1);c&&
(b.set("ved",c),d&&b.set("ictx",d),e&&b.set("vet",e));f=_.kc(Wpe,b)}}return f};Wpe=(0,_.jc)`/imgres`;
_.fSc=function(a){return _.p(a,_.ju,4)};
_.DB=function(a,b){return _.mh(a,1,_.yz,b)};_.EB=function(a,b){return _.Bb(a,_.wz,1,b)};
_.t("qKrDxc");
var M2q=function(a){var b=(new _.mu).Kp(7);const c=a.getId(),d=new _.yz;_.Bz(d).oa(_.pG,a);b=_.Dz(_.Mz(_.Fz(new _.Ez,b),c),d);_.soe(a);_.toe(a.getImage());return b};var N2q=async function(a,b,c){try{const g=_.y(await _.y(a.lz())),h=_.A(g,5);var d=a.Ca(c),e=(c=h)&&_.OUa(h)||void 0;const k=_.Xpe(g,_.Gn(new _.yn(a.Wi.getCurrentUrl()),"q")||"",c,d,e);if(k){var f=_.ac(k.toString());f&&_.Ac(b,f)}}finally{_.y()}},O2q=class extends _.vz{static Sa(){return{jsdata:{zs:_.nG},service:{history:_.zG,navigation:_.Sz,focus:_.kw,Ec:_.Gu}}}constructor(a){super(a.Oa);this.Ea=!1;this.Ba=b=>{const c=this.getRoot();if(c.el()){var d=_.nl(this.getData("docid"));c.toggleClass("loWRed",
d!==null&&b.detail.vhid===d)}};this.oa=()=>{const b=this.getRoot();b.el()&&b.hasClass("loWRed")&&(b.removeClass("loWRed"),this.Af.dU(b,{preventScroll:!0}))};_.tz(this,M2q(a.jsdata.zs));this.Wi=a.service.history;this.kc=a.service.navigation;this.Af=a.service.focus;this.Tb=a.service.Ec;this.logger=null;_.Bw&&(document.addEventListener("viewerUpdated",this.Ba),document.addEventListener("viewerClosed",this.oa),this.addOnDisposeCallback(()=>{document.removeEventListener("viewerUpdated",this.Ba);document.removeEventListener("viewerClosed",
this.oa)}))}Ka(a){if(this.Ea)return!0;let b=a.targetElement.el();for(let c=0;c<10&&b;c++,b=b.parentElement){let d;if(((d=b)==null?void 0:d.tagName)==="A"){N2q(this,b,a);this.Ea=!0;break}}return!0}Oc(a){this.trigger("yu1Hm");return super.Oc(a)}Na(a){this.Oc(a);return null}Ma(a){a=a.targetElement.el();if(!a)return null;var b=a.getAttribute("href");if(!b)return null;b=_.ac(b);if(!b)return null;this.kc.navigateTo(b);this.Tb.logEvent({xe:_.zg(a)});return null}};O2q.prototype.$wa$WZxsNc=function(){return this.Ma};
O2q.prototype.$wa$Esn7Cd=function(){return this.Na};O2q.prototype.$wa$h5M12e=function(){return this.Oc};O2q.prototype.$wa$UI3Kjd=function(){return this.Ka};_.Ie.getInstance().register(_.L2q,O2q);
_.v();
_.whC=_.x("N8Q1ib",[]);
_.t("N8Q1ib");
var buF=class extends _.Tr{constructor(a){super(a.Oa)}Oc(a){let b,c;(c=(b=a.event).stopPropagation)==null||c.call(b)}};buF.prototype.$wa$h5M12e=function(){return this.Oc};_.Ie.getInstance().register(_.whC,buF);
_.v();
});
// Google Inc.
