"use strict";loaded_1_5(function(_){var window=this;
_.k("nCUUCf");

_.l();
var Gvc;_.Evc=_.oe(_.Wt);_.Fvc=function(a){return _.r(a,_.Wt,1)};Gvc=class extends _.q{constructor(a){super(a)}};Gvc.prototype.qb="JAZN7b";_.Hvc=_.ie(53,_.nn,Gvc);
_.k("iaRXBb");
var Mvc=function(a,b){return _.kf(function*(){var c=new Promise(h=>void setTimeout(h,1E3)),d=_.yvc(a,window).sendMessage(Ivc(new _.YD,Jvc(new Kvc,b))),e;c=(e=yield Promise.race([c,d]))==null?void 0:_.Xg(e,Lvc,11,_.ZD);if(!c||!_.Hg(c,_.UD,4))return null;e=_.r(c,_.UD,4).Aa();e=_.r(c,_.UD,4).Ea(e);d=_.r(c,_.TD,2);let f,g;return{RR:e,mwa:(f=d==null?void 0:_.z(d,6))!=null?f:!1,Vq:(g=_.r(c,_.eNb,3))!=null?g:null}})},Nvc=function(a){return a.z4.get().filter(b=>_.jr(b).getContentType()===1)},Ovc=function(a){return Nvc(a)[0]||
null},Pvc=_.oe(_.dn),Qvc=function(a){return!a.Aa&&!a.oa},Rvc=_.oe(_.Xp),Svc=class extends _.XFb{},Tvc=function(a){return new Svc(_.yFb(a,_.nvc))},Uvc=function(a){a=a.images;let b;b="<velog"+_.u(new _.I(_.mvc),!1)+">";const c=a.length;for(let d=0;d<c;d++){const e=a[d];let f;b+='<div data-index="'+_.L(d)+'"'+_.N(_.Tw())+_.u(new _.I(_.lvc,_.$r(new _.ds,(f=_.hvc(e))==null?void 0:f.qg())),!1)+"></div>"}return(0,_.Ns)(b+"</velog>")},Vvc=function(a,b){return _.ee(a,_.xw,29,b)},Wvc=function(a){return _.sh(a,
46,!0)},Xvc=new _.ag("HoAMBc",_.XD,_.qvc,[_.wq,!0,_.xq,"/VisualFrontendDataService.GetImageSearch"]),Yvc=function(a){let b;return(b=a.yu)!=null?b:"uviewer"},Zvc=function(a){if(a.yu){let b,c,d;return new Set((d=(b=a.cq.streams.get(a.yu))==null?void 0:(c=b.Aa())==null?void 0:c.map(e=>e.wk()))!=null?d:[])}return new Set},$vc=function(a,b){if(a.yu){const c=a.cq.streams.get(a.yu);b=c.Aa().concat(b.map(d=>{d=d.Me();if((0,_.Evc)(d))var e=d;else{if(Rvc(d)){var f=d;var g;d=(g=f.Gb())==null?void 0:_.yl(g,_.zn)}else{if(Pvc(d)){g=
new _.nn;var h=(f=d.getUniqueId())!=null?f:"";g=_.Bg(g,8,h);d=_.Qxa(g.Sc(1),d)}f=_.JFa(new _.Xp,_.zl(new _.sn,_.zn,d))}var m;if((m=d)==null?0:m.hasExtension(_.Hvc))e=_.Fvc(_.yl(d,_.Hvc));else{m=_.Wu(new _.Wt,f);var n;g=(n=d)==null?void 0:n.getId();g!=null&&_.Vu(m,g);var p;n=(e=d)==null?void 0:(p=e.Pc())==null?void 0:_.nk(p,5);n!=null&&_.Bg(m,5,n);e=m}}return e}));_.bNb(a.cq,c.Ea(b))}},awc=function(a){if(a.Ea){const b=Zvc(a);a.Ea=!1;const c=Wvc(Vvc(new _.qvc,a.Aj()));a.Se.fetch(Xvc.Ec(c)).then(d=>
{let e,f;const g=((f=(e=Ovc(Tvc(d.getScope()).oa))==null?void 0:_.KFb(e))!=null?f:[]).filter(h=>!b.has(h.id())&&h.Me().getType()===1);a.Zc&&(d=_.Nx(a.Xc,()=>a.Ib.Ac(Uvc,{images:g.map(h=>h.Uq())}),{Zc:a.Zc}),_.sb(d.children,h=>{var m=Number(_.uf(h,"index"));(m=g[m].Me().Pc())!=null&&(h=_.uf(h,"ved"),_.Bg(m,5,h))}));$vc(a,g);a.notify("fQ0Wz")})}else a.Ga&&a.Ja&&(a.Ga=!1,a.Ja(Yvc(a)))},Jvc=function(a,b){return _.Bg(a,1,b)},Kvc=class extends _.q{constructor(a){super(a)}},Lvc=class extends _.q{constructor(a){super(a)}},
Ivc=function(a,b){return _.ek(a,10,_.ZD,b)},bwc=_.re(_.eNb),cwc=[0,_.Il],dwc=new Map;var fwc=function(a){_.kf(function*(){const b=a.Qh.O5();if(b){var c={Zc:_.Wuc(a.Qh),HAa:!0,replace:!0},d=_.Uuc(a.Qh);var e=_.Quc(a.Qh);if(e){var f=a.Qh.getUserData();var g=f.eAa?(0,_.Kuc)(f.eAa):null;f=f.Vq?bwc(f.Vq):null;var h;g={RR:e,mwa:(h=g==null?void 0:_.z(g,6))!=null?h:!1,Vq:f}}else g=null;h=g;if((h=h!=null?h:yield ewc(a,b,d))!=null)var m=h;else{h=a.Qh.getUserData();h=h.Vq?bwc(h.Vq):null;g=null;var n;if(d)a:{e=b.split("/");f=new Map;for(n of e){const [v,x]=n.split("=");e=v;const y=x;e&&f.set(e,
y||"")}if(n=f.get("vt"))if(n=dwc.get(n)){n=n==null?void 0:(m=n(f))==null?void 0:_.Vu(m,b);break a}n=void 0}else n=null;if(m=n)n=_.Cuc(new _.UD,d),g=_.gk(n,1,_.Wt,m);m={RR:g,Vq:h,mwa:!1}}m.Vq&&(a.hK.Vq=m.Vq);m.RR&&a.model.oa(m.RR,m.mwa);m=null;if(d)c.t3=b,c.yu=d;else if(n=a.Qh.wcb())if(h=_.$uc(a.Qh))c.S6=b,c.V4=n,m=h;var p,t;(d?(p=_.cNb(a.cq,d,b))==null?0:p.callback:(t=m)==null?0:t.oa.nPa(b))?yield a.Qh.navigateToView(c):(a.ri.getDocument().body.style.opacity="",yield a.Qh.navigateToView({replace:!0}))}})},
ewc=function(a,b,c){return _.kf(function*(){const d=yield Mvc(a.ri.get(),b);if(!d)return null;d.RR&&a.model.oa(d.RR,d.mwa);if(c){const e=_.cNb(a.cq,c,b);return e&&e.callback?d:null}return d})},gwc=class extends _.Yu{static Za(){return{model:{jn:_.rvc},service:{Vq:_.fNb,cq:_.dNb,Qh:_.WD,ri:_.jv}}}constructor(a){super();this.model=a.model.jn;this.hK=a.service.Vq;this.cq=a.service.cq;this.Qh=a.service.Qh;this.ri=a.service.ri;this.wd=null;fwc(this)}Aa(){}Ea(a){a.data===Yvc(this.model)&&awc(this.model)}oa(a,
b){const c=_.dv(this,"Sva75c").el();c&&(a=!(!a||a.closest('[data-scope-id="qZRtEe"]')===null),c.classList.toggle("InCanvas_",a&&!b))}bU(a){this.oa(a.data.sourceElement,Qvc(a.data));_.Fi(()=>{this.Ka().toggleClass("DWVRvc",Qvc(a.data))})}};gwc.prototype.$wa$e4mHGd=function(){return this.bU};gwc.prototype.$wa$BeSr3d=function(){return this.oa};gwc.prototype.$wa$uj875b=function(){return this.Ea};gwc.prototype.$wa$ruyrc=function(){return this.Aa};_.av(_.abb,gwc);var hwc=class extends _.q{constructor(a){super(a)}};var iwc=_.ie(35,_.rr,hwc);_.sr[35]=[0,_.E,1,[0,[0,_.E,-3],_.E,_.C,_.E,-1,_.lm,[0,_.Xl,_.El,_.Xl],1,_.C,_.vm,cwc]];if(dwc.has("20"))throw Error("Qe`20");dwc.set("20",function(a){if(a=a.get("docid")){var b=new hwc;a=_.Bg(b,1,a);b=new _.rr;b=_.zva(b,1,[1,2]);a=_.zl(b,iwc,a);a=_.aE((new _.vr).oa(20),a);return _.Su(_.Wu(new _.Wt,_.nEb(null,!0,2)),a)}});





_.l();
});
// Google Inc.
