"use strict";_F_installCss(".Rh1lN{display:-moz-box;display:flex;-moz-box-align:center;align-items:center;-moz-box-pack:justify;justify-content:space-between;border-radius:10px;width:117px;height:20px;visibility:hidden;opacity:0;transition:opacity 250ms cubic-bezier(0.2,0,0,1),visibility 0s 250ms}.GPp4md{visibility:visible;opacity:1;transition:opacity 250ms cubic-bezier(0.2,0,0,1)}.UCOQHe .sdQC9e{transition:transform 250ms cubic-bezier(0.2,0,0,1)}.mipa1{filter:drop-shadow(0 0 2px rgba(0,0,0,.9))}.Zzkood{display:-moz-box;display:flex;width:20px;height:20px;-moz-box-align:center;align-items:center;-moz-box-pack:center;justify-content:center}.deKEjf{display:-moz-box;display:flex;height:48px;width:48px;-moz-box-align:center;align-items:center;-moz-box-pack:center;justify-content:center;flex-shrink:0}.LUwZqf{display:-moz-box;display:flex;height:20px;min-width:0;-moz-box-flex:1;flex-grow:1;flex-shrink:1;-moz-box-align:center;align-items:center;-moz-box-pack:center;justify-content:center}.LOzlUe{width:97px;height:10px}.tpbGH,.sYTunc{cx:3px;cy:5px;r:3px;transform-origin:3px}.xZfjr{x:3px;y:2px;width:14px;height:6px;transform-origin:3px}.ANbZS{clip:rect(1px,1px,1px,1px);height:1px;overflow:hidden;position:absolute;-moz-user-select:none;user-select:none;white-space:nowrap;width:1px;z-index:-1000}sentinel{}");
loaded_1_8(function(_){var window=this;
_.pf(_.gq);
_.Otd=function({title:a,ot:b,pageUrl:c,imageUrl:d}){if(a||b||c||d)return!1;a=new _.Nv("invalid_content","contains empty strings or unsupported keys");_.Ntd(a);return a};_.Ntd=function(a){_.uG({Ub:"sh",methodName:"sss"},a)};_.Ptd=function(a){_.fNc({Ub:"sh",methodName:"sss"},_.UGb(a))};_.Qtd=function(){_.AG("sh","bctnsb")};_.Rtd=function(){_.AG("sh","rbtnsb")};
_.k("Qj0suc");
_.Gh(_.pHa,class extends _.At{isAvailable(){return!1}bF(){return!1}xz(){const a=_.Ov();_.Ntd(a);return Promise.reject(a)}bD(){return!1}mU(){return!1}vL(){_.Qtd();Promise.resolve(!1)}pN(){_.Rtd();Promise.resolve(!1)}kZ(){return Promise.reject(_.Ov())}});
_.l();
_.pf(_.i1a);
_.k("vVVzjb");
var a9c=class extends _.At{isAvailable(){return!1}oa(){return!1}vibrate(){return _.AG("Haptics","vibrate")}Aa(){_.AG("Haptics","playSystemHaptic")}};_.Gh(_.h1a,a9c);
_.l();
_.k("mUtlJf");
var s9d,t9d;s9d=class{constructor(a,b){this.group=b;this.start=_.cv(a,b,"HRk6mf").el();this.end=_.cv(a,b,"AlNdAd").el();this.oa=_.cv(a,b,"ESSeec").el()}};
t9d=function(a,b,c,d){const e=_.Vi(b-(d-2),0,c-d);a.lxa.forEach((f,g)=>{g=_.fv(g-e,8)+e-2;var h=_.Vi(e-g,0,1),m=_.Vi(g-(e+d-1),0,1);const n=_.Vi(Math.abs(g-b),0,1);var p=6+(1-n)*14+Math.max(h,m,Math.min(_.Vi(e+1-g,0,1),_.Vi(g,0,1)),Math.min(_.Vi(g+1-(e+d-1),0,1),_.Vi(c-1-g,0,1)))*-2;h=1-Math.max(Math.max(h,m),n*.1);m=Math.min(p,6)/6;p=Math.max(0,p-6);f.group.style.transform=`translateX(${(g-e)*11+_.Vi(g-b,0,1)*14}px)`;f.group.style.opacity=h.toString();f.start.style.transform=`scale(${m})`;f.end.style.transform=
`scale(${m}) translateX(${p}px)`;f.oa.style.transform=`scaleX(${p/14})`})};
_.u9d=class extends _.Yu{constructor(){super();this.lxa=[];this.state={visible:!1,transition:!1,page:0,lY:1};this.oa={visible:!1,transition:!1,page:0,lY:1};this.statusText=this.Va("mGwflf").el();this.Ea=this.Va("MMb2F").el();this.lxa=this.Tb("jyEOKd").map(a=>new s9d(this,a));this.wYa=_.iv(this).Yb(this.Aa).build()}hide(){this.update(!1,this.state.transition,this.state.page,this.state.lY)}update(a,b,c,d){this.oa.visible=a;this.oa.transition=b;this.oa.page=c;this.oa.lY=d;this.wYa()}Aa(){var a=this.oa.visible&&
this.oa.lY>=2,b=this.state.visible;this.Nw(a);a&&(this.statusText.textContent=Math.round(this.oa.page+1).toString()+" \u0438\u0437 "+this.oa.lY.toString()+". \u0427\u0442\u043e\u0431\u044b \u0443\u0432\u0438\u0434\u0435\u0442\u044c \u0431\u043e\u043b\u044c\u0448\u0435, \u043f\u0440\u043e\u0432\u043e\u0434\u0438\u0442\u0435 \u0432\u043b\u0435\u0432\u043e \u0438\u043b\u0438 \u0432\u043f\u0440\u0430\u0432\u043e \u043f\u043e \u044d\u043a\u0440\u0430\u043d\u0443 \u0438\u043b\u0438 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u0441\u043e \u0441\u0442\u0440\u0435\u043b\u043a\u0430\u043c\u0438 \u0432\u043d\u0438\u0437\u0443 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b.",
a=this.oa.transition&&a&&b,this.Ka().toggleClass("UCOQHe",a),this.state.transition=a,a=Math.min(this.oa.lY,4),b=this.oa.lY,this.Ea.style.transform=`translateX(${(39-(a*6+(a-1)*5))/2}px)`,this.state.lY=b,t9d(this,this.oa.page,this.oa.lY,a))}Nw(a){this.state.visible!==a&&(this.Ka().toggleClass("GPp4md",a),this.state.visible=a)}};_.u9d.prototype.$wa$ZYIfFd=function(){return this.hide};_.av(_.O6a,_.u9d);

_.l();
var kRc,jRc;kRc=function(a,b){var c=_.QG.Za.document.documentElement;const d=c.scrollHeight;a=Math.max(0,Math.min(c.scrollWidth-_.QG.Za.window.innerWidth,a));b=Math.max(0,Math.min(d-_.QG.Za.window.innerHeight,b));c.style.height=`${d}px`;c=_.QG.Za.document.body.style;c.position="fixed";c.width="100%";c.left=`${-a}px`;c.top=`${-b}px`;iRc&&(0,_.Tp)(iRc);_.QG.Za.window.requestAnimationFrame?_.QG.Za.window.requestAnimationFrame(()=>void jRc(a,b)):iRc=(0,_.Sp)(()=>void jRc(a,b),10)};
jRc=function(a,b){_.QG.Za.window.scrollTo(a,b);iRc=null;_.QG.Za.document.body.style.position="";_.QG.Za.document.body.style.width="";_.QG.Za.document.body.style.left="";_.QG.Za.document.body.style.top="";_.QG.Za.document.documentElement.style.height=""};_.QG={};_.QG.Za={window,document:window.document};var lRc=_.Zb(),iRc=null;_.QG.by=function(a,b,c){if(a||b)lRc?(c=_.mj(),kRc(c.x+a,c.y+b)):c?_.QG.Za.window.scrollBy({top:b,left:a,behavior:"smooth"}):_.QG.Za.window.scrollBy(a,b)};
_.QG.to=function(a,b,c){lRc?kRc(a,b):c?_.QG.Za.window.scrollTo({top:b,left:a,behavior:"smooth"}):_.QG.Za.window.scrollTo(a,b)};
_.k("U4MzKc");
_.mRc=class extends _.At{static Za(){return{service:{cache:_.PG,history:_.uw,location:_.LG,window:_.uu}}}constructor(a){super();this.oa=null;this.window=a.service.window.get();this.document=a.service.window.getDocument();this.cache=a.service.cache;this.location=a.service.location;this.storage=this.cache.get("s",_.fRc);this.history=a.service.history;this.Aa=this.history.getEventTarget().listen("FWkcec",()=>{})}by(a,b,c){(0,_.QG.by)(a,b,c)}disable(){this.oa||(this.oa=_.Rf(this.document.documentElement,
"touchmove",_.ZQc));if(!window.visualViewport||window.visualViewport.scale>=1)this.document.body.style.overflow="hidden"}enable(){this.oa&&(_.Qf(this.oa),this.oa=null);if(!window.visualViewport||window.visualViewport.scale>=1)this.document.body.style.overflow=""}YP(){return this.storage.get(this.location.location.href)}Xo(){this.storage.set(this.location.location.href,_.mj())}to(a,b,c){(0,_.QG.to)(a,b,c)}ld(){this.oa&&_.Qf(this.oa);this.Aa&&this.history.getEventTarget().Hq(this.Aa)}c1(a){const b=
window.getComputedStyle(a);return(b.overflowY==="scroll"||b.overflowY==="auto")&&a.scrollHeight>a.clientHeight}};_.Gh(_.DFa,_.mRc);
_.l();
_.k("g8nkx");
_.nRc=new _.nf(_.EFa);
_.l();
_.R7c=function(a,b=!1){const c=_.P7c.get(a);if(c){var d=null;for(const e of c)_.Bp(e.target,e.type,e.callback,b),d=e.target;_.P7c.delete(a);if(b=Q7c.get(a)){for(const e of b)e();Q7c.delete(a)}d&&"_GTL_"in d&&_.jb(d._GTL_,a)}};_.V7c=function(a,b,c,d,e,f,g,h){S7c||(S7c=_.T7c.Hj()||new U7c);return S7c.Hva(a,b,c,d,e,f,g,h)};var Q7c;_.P7c=new Map;Q7c=new Map;var S7c,U7c;S7c=void 0;_.T7c=new _.Ip;U7c=class{Hva(){return"DEFAULT_ID"}};
_.e8c=function(a){const b=_.mf.Ec().tE(a),c=_.tka(b);c?_.poa.add(c.toString()):_.poa.add(b);a.Os&&(a.Os.Fhb=null)};
_.o8c=!!(_.Th[59]&8);_.p8c=!!(_.Th[59]&16);
_.k("ww04Df");
var q8c,s8c,r8c,t8c,v8c,A8c,y8c,x8c,z8c,C8c,B8c,E8c,D8c,F8c,H8c,G8c,I8c,J8c,L8c,K8c,M8c,N8c;q8c=function(a){typeof a==="function"?a():a.unsubscribe()};s8c=function(a){return a.length===0?r8c:a.length===1?a[0]:function(b){return a.reduce((c,d)=>d(c),b)}};r8c=function(a){return a};t8c=function(a){return typeof a==="function"};v8c=function(a,b,c,d,e){return new u8c(a,b,c,d,e)};A8c=function(a){if(a<0)throw Error("jg");return b=>w8c(b,x8c((c,d)=>d===a),y8c(),z8c(()=>Error("jg")))};
y8c=function(){return a=>new vI(b=>{let c=0;const d=v8c(b,e=>{++c<1?b.next(e):(d.unsubscribe(),b.next(e),b.complete())});a.subscribe(d)})};x8c=function(a){return b=>new vI(c=>{let d=0;b.subscribe(v8c(c,e=>{a.call(void 0,e,d++)&&c.next(e)}))})};z8c=function(a){return b=>new vI(c=>{let d=!1;b.subscribe(v8c(c,e=>{d=!0;c.next(e)},()=>{d?c.complete():c.error(a())}))})};C8c=function(a){if(a instanceof vI)return a;if(a instanceof Array)return B8c(a);throw Error("kg`"+a);};
B8c=function(a){return new vI(b=>{for(let c=0;c<a.length&&!b.closed;c++)b.next(a[c]);b.complete()})};E8c=function(a,b,c=!1){return new vI(d=>{function e(g,...h){requestAnimationFrame(()=>{h.length?d.next(Array.prototype.slice.call([g,...h])):d.next(g)})}function f(g,...h){h.length?d.next(Array.prototype.slice.call([g,...h])):d.next(g)}D8c(a,b,c?e:f,d)})};D8c=function(a,b,c,d){a.addEventListener(b,c,void 0);d.add(()=>{a.removeEventListener(b,c,void 0)})};
F8c=function(a){return b=>new vI(c=>{let d=0;b.subscribe(v8c(c,e=>{c.next(a(e,d++))}))})};H8c=function(...a){a=a.length===1&&Array.isArray(a[0])?a[0]:a;return a.length===1?C8c(a[0]):new vI(G8c(a))};G8c=function(a){return b=>{let c=[];for(let d=0;c&&!b.closed&&d<a.length;d++)c.push(C8c(a[d]).subscribe(v8c(b,e=>{if(c){for(let f=0;f<c.length;f++)f!==d&&c[f].unsubscribe();c=null}b.next(e)})))}};
I8c=function(a){return b=>new vI(c=>{let d=null,e=0;b.subscribe(v8c(c,f=>{var g;(g=d)==null||g.unsubscribe();g=e++;C8c(a(f,g)).subscribe(d=v8c(c,void 0,()=>{d=null}))},()=>{}))})};J8c=function(a){return b=>new vI(c=>{C8c(a).subscribe(v8c(c,()=>{c.complete()},()=>{}));!c.closed&&b.subscribe(c)})};
L8c=function(a){const b=typeof a==="function"?{next:a}:a;return b?c=>new vI(d=>{let e;(e=b.subscribe)==null||e.call(b);let f=!0;c.subscribe(v8c(d,g=>{let h;(h=b.next)==null||h.call(b,g);d.next(g)},()=>{f=!1;let g;(g=b.complete)==null||g.call(b);d.complete()},g=>{f=!1;let h;(h=b.error)==null||h.call(b,g);d.error(g)},()=>{if(f){let h;(h=b.unsubscribe)==null||h.call(b)}let g;(g=b.aJ)==null||g.call(b)}))}):K8c};K8c=function(a){return a};M8c=function(a){return{x:a.changedTouches[0].clientX,y:a.changedTouches[0].clientY}};
N8c=function(a){return Object.assign({},M8c(a),{target:_.Je(a.target)?a.target:void 0})};_.O8c=class{constructor(){this.closed=!1;this.Aa=null}unsubscribe(){if(!this.closed){this.closed=!0;const a=this.Aa;if(a){this.Aa=null;for(const b of a)try{q8c(b)}catch(c){}}}}add(a){a&&a!==this&&(this.closed?q8c(a):(a&&"add"in a&&a.add(()=>{this.remove(a)}),this.Aa!=null||(this.Aa=new Set),this.Aa.add(a)))}remove(a){let b;(b=this.Aa)==null||b.delete(a)}};var P8c=class extends _.O8c{constructor(a){super();this.oa=!1;this.destination=a instanceof P8c?a:new Q8c(!a||t8c(a)?{next:a!=null?a:void 0}:a);a&&t8c(a.unsubscribe)&&t8c(a.add)&&a.add(this)}next(a){this.oa||this.Ja(a)}error(a){a&&!this.oa&&(this.oa=!0,this.Ga(a))}complete(){this.oa||(this.oa=!0,this.Ea())}unsubscribe(){this.closed||(this.oa=!0,super.unsubscribe(),this.destination=null)}Ja(a){let b,c;(c=(b=this.destination).next)==null||c.call(b,a)}Ga(a){try{let b,c;(c=(b=this.destination).error)==
null||c.call(b,a)}finally{this.unsubscribe()}}Ea(){try{let a,b;(b=(a=this.destination).complete)==null||b.call(a)}finally{this.unsubscribe()}}},Q8c=class{constructor(a){this.oa=a}next(a){const b=this.oa;if(b.next)try{b.next(a)}catch(c){}}error(a){const b=this.oa;if(b.error)try{b.error(a)}catch(c){}}complete(){const a=this.oa;if(a.complete)try{a.complete()}catch(b){}}};var w8c=function(a,...b){return s8c(b)(a)},vI=class{constructor(a){a&&(this.oa=a)}oa(){}subscribe(a){a=a instanceof P8c?a:new P8c(a);a.add(this.oa(a));return a}};var u8c=class extends P8c{constructor(a,b,c,d,e){super(a);this.La=e;this.Ja=b?function(f){try{b(f)}catch(g){a.error(g)}}:super.Ja;this.Ga=d?function(f){try{d(f)}catch(g){a.error(g)}finally{this.unsubscribe()}}:super.Ga;this.Ea=c?function(){try{c()}catch(f){a.error(f)}finally{this.unsubscribe()}}:super.Ea}unsubscribe(){const a=this.closed;super.unsubscribe();let b;a||(b=this.La)!=null&&b.call(this)}};var S8c,T8c,U8c,V8c,R8c;
S8c=function(a,b,c,d,e){const f=e-1;return I8c(g=>w8c(c,A8c(f),L8c(()=>{var h=g.target,m=0,n=0;let p=0,t=0;for(h=h!=null?h:b;h&&h!==b.parentElement;){var v=getComputedStyle(h);(v.overflowY==="scroll"||v.overflowY==="auto")&&h.scrollHeight>h.clientHeight&&(m+=h.scrollTop,n+=h.scrollHeight-h.clientHeight-h.scrollTop);v=getComputedStyle(h);(v.overflowX==="scroll"||v.overflowX==="auto")&&h.scrollWidth>h.clientWidth&&(p+=h.scrollLeft,t+=h.scrollWidth-h.clientWidth-h.scrollLeft);h=h.parentElement}a.Ja=
{i7:m<=8,BRa:n<=8,ARa:p<=8,zRa:t<=8};if(n=g.target)for(m=[];n&&n!==document.body;)(n.scrollHeight>n.clientHeight||n.scrollWidth>n.clientWidth)&&m.push({element:n,overflow:getComputedStyle(n).overflow}),n=n.parentElement;else m=[];a.Ga=m}),F8c(h=>({x:h.x,y:h.y,axis:R8c(g,h,d).axis,direction:R8c(g,h,d).direction}))))};T8c=function(a,b){return{horizontal:b.x-a.x,vertical:b.y-a.y}};U8c=function(a,b){a.oa=_.V7c(b,c=>{c.oa.cancelable&&(c.oa.preventDefault(),c.oa.stopPropagation())})};
V8c=function(a,b,c){let d=0;var e=0;a.Aa&&a.La&&(e=performance.now()-a.La,d=(c.horizontal-a.Aa.horizontal)/e,e=(a.Aa.vertical-c.vertical)/e);a.Aa=c;a.La=performance.now();const {horizontalVelocity:f,verticalVelocity:g}={horizontalVelocity:d,verticalVelocity:e};return{axis:b.axis,horizontalDistance:c.horizontal,verticalDistance:-c.vertical,horizontalVelocity:f,verticalVelocity:g,xEa:a.Ja,m_a:{x:b.x,y:b.y}}};
R8c=function(a,b,c){const {horizontal:d,vertical:e}=T8c(a,b);return Math.abs(d)>Math.abs(e)*c?d>=0?{axis:"x",direction:4}:{axis:"x",direction:3}:Math.abs(e)>Math.abs(d)*c?e>=0?{axis:"y",direction:2}:{axis:"y",direction:1}:{axis:"uncategorized",direction:0}};
_.W8c=class extends _.At{static Za(){return{service:{gV:_.nRc}}}constructor(a){super();this.Ea=!0;this.oa="";this.Ja={i7:!1,BRa:!1,ARa:!1,zRa:!1};this.La=this.Aa=null;this.Ga=[];this.Na=!1;this.gV=a.service.gV}FKa({M_a:a,fJa:b,J_a:c,zSb:d,tpa:e,c2:f,options:g}){var h;const m=(h=g==null?void 0:g.Gjb)!=null?h:!0;let n;const p=(n=g==null?void 0:g.Fjb)!=null?n:!0;g=!_.o8c;h=w8c(E8c(a,"touchstart",g),F8c(N8c));const t=w8c(E8c(a,"touchmove",!0),F8c(M8c)),v=E8c(a,"touchcancel",g),x=w8c(E8c(a,"touchend",
g),F8c(M8c));return w8c(w8c(h,S8c(this,a,t,b,d!=null?d:4)),I8c(y=>w8c(t,F8c(A=>T8c(y,A)),L8c(A=>{if(!c||c.includes(y.direction)){if(m&&this.Ea){if(this.Ja.i7)for(const D of this.Ga)D.element.style.overflow="hidden";document.body.style.overflow==="hidden"?this.Na=!0:this.gV.disable();this.Ea=!1}p&&!this.oa&&U8c(this,a);e==null||e(V8c(this,y,A))}}),J8c(H8c(w8c(x,F8c(A=>T8c(y,A)),L8c(A=>{if(!c||c.includes(y.direction)){if(m&&!this.Ea){for(const D of this.Ga)D.element.style.overflow=D.overflow;this.Ga=
[];this.Na||this.gV.enable();this.Na=!1;this.Ea=!0}this.oa&&(_.R7c(this.oa,!1),this.oa="");f==null||f(V8c(this,y,A))}})),v))))).subscribe()}};_.Gh(_.GYa,_.W8c);_.e8c(_.W8c);
_.l();
_.k("pj82le");
_.X8c=new _.nf(_.nbb);
_.l();
_.k("Ym9NZc");
var c9c=class extends _.q{constructor(a){super(a)}};c9c.prototype.oa=_.ne([0,_.F,-1]);var d9c=!!(_.Th[34]>>18&1);var e9c;e9c=[6];_.f9c=function(a){if(a.oa.oa()){a=a.oa;var b=a.Aa;var c=new c9c;c=_.ph(c,1,1);c=_.ph(c,2,22);b.call(a,c)}else d9c&&a.vibrate(e9c)};
_.g9c=class{constructor(a){this.oa=a}vibrate(a){if(_.Zb()&&_.Cca().split(".")[0]>="18"){a=document.createElement("input");a.type="checkbox";a.id="XAvPJd";a.setAttribute("switch","");a.style.display="none";document.body.appendChild(a);var b=document.createElement("label");b.htmlFor="XAvPJd";b.style.display="none";document.body.appendChild(b);b.click();document.body.removeChild(a);document.body.removeChild(b);return!0}let c;return((c=(b=window.navigator).vibrate)==null?void 0:c.call(b,a))||!1}};
_.l();
_.k("TroZ1d");
_.Z8c=new _.nf(_.i1a);
_.l();
_.k("JZmW9e");
var u9c=function(a,b,c,d){return e=>_.kf(function*(){if(e.xEa.i7){yield r9c(a,b,c);var f=s9c(-e.verticalDistance,b.clientHeight*.25),g=s9c(e.horizontalDistance,b.clientWidth*.25),h=Math.min(1-f/2500,1);if(a.Aa)a.Aa.onMove({xWithTension:g,yWithTension:f,scale:h,axis:e.axis,horizontalDistance:e.horizontalDistance,verticalDistance:e.verticalDistance,horizontalVelocity:e.horizontalVelocity,verticalVelocity:e.verticalVelocity,startedFromScrollTop:e.xEa.i7,startX:e.m_a.x,startY:e.m_a.y});else b.style.transform=
`scale(${h}) translate(${g}px, ${f}px)`;_.l9c&&!a.La&&t9c(e)&&(a.La=!0,_.f9c(a.Xa));d&&!a.Aa&&(d.style.transition||requestAnimationFrame(()=>{d.style.transition="opacity .5s ease-out"}),d.style.opacity=t9c(e)?"0.4":"0.8")}})},w9c=function(a,b,c,d){return e=>_.kf(function*(){e.xEa.i7&&(a.La=!1,yield v9c(a,t9c(e),b,c,d),(_.o8c||a.Aa?f=>f():requestAnimationFrame)(()=>{if(t9c(e)){let f;(f=a.Aa)==null||f.onDismiss();a.unsubscribe();_.$e(document.body,"VOy8xe",b);d&&(a.oa=void 0,d.animate({opacity:0},{duration:100,
fill:"forwards"}).finished.then(()=>{d==null||d.remove()}))}else{let f;(f=a.Aa)==null||f.onCancel();_.$e(document.body,"s2IYHc",b)}}))})},r9c=function(a,b,c){return _.kf(function*(){if(!a.Ea){_.$e(document.body,"ucVTnf",b);a.Ea=!0;c&&(c.style.opacity="0.01");if(a.Aa)try{yield a.Aa.onStart()}catch(d){_.Pv(d,{tq:{src:"std-ch"},level:2}),a.Aa=void 0}if(!a.Aa){b.style.transformOrigin="center center";b.style.willChange="transform";b.style.transition="transform 50ms ease-out";b.style.clipPath="inset(0 round 20px)";
const d=b.parentElement;d&&b.style.height&&b.style.width&&(d.style.filter=`drop-shadow(${document.body.dataset.dt?"0px 2px 6px rgba(23, 23, 23, 0.32)":"0px 2px 6px rgba(60, 64, 67, 0.16)"})`,d.style.height=b.style.height,d.style.width=b.style.width,d.style.position=b.style.position,d.style.top=b.style.top,d.style.zIndex=b.style.zIndex);yield(0,_.Sp)(()=>{b.style.transition="transform ease-out"},50)}}})},v9c=function(a,b,c,d,e){return _.kf(function*(){if(a.Ea){var f=c.parentElement;a.Ea=!1;(0,_.Qp)(()=>
{_.$e(document.body,"pU3PWb",c)});b||(c.style.transition="transform 100ms ease-out",c.style.transform="scale(1.0) translate(0px, 0px)");yield(0,_.Sp)(()=>{f&&(f.style.filter="",f.style.height="",f.style.width="",f.style.position="",f.style.top="",f.style.zIndex="");c.style.transition="";c.style.clipPath="";c.style.transform="";c.style.willChange="";d&&(d.style.opacity="1");e&&(e.style.transition="",e.style.opacity="0")},300)}})},s9c=function(a,b){if(Math.abs(a)<=b)return a;const c=a<0?-1:1;return c*
b+c*Math.pow(Math.abs(a)-b,1)},t9c=function(a){return Math.abs(a.horizontalDistance)>70||Math.abs(a.verticalDistance)>70?!0:a.verticalDistance+a.verticalVelocity*20<-70},x9c=class extends _.At{static Za(){return{service:{RZa:_.Z8c,L_a:_.X8c}}}constructor(a){super();this.Na="";this.Sa=[];this.La=this.Ea=!1;this.Ja=!0;this.Xa=new _.g9c(a.service.RZa);this.L_a=a.service.L_a}uTb(a,b){this.unsubscribe();this.Aa=void 0;this.Na="";this.Sa=[];let c=a;for(;c;){const g=getComputedStyle(c).zIndex;g!==""&&g!==
"auto"&&(this.Na===""?this.Na=g:this.Sa.push({element:c,zIndex:c.style.zIndex,TAc:g}));c=c.parentElement}document.documentElement.style.overscrollBehaviorY="none";document.body.style.overscrollBehaviorY="none";this.Ja=!1;let d;if(_.o8c){let g;this.oa=(g=this.oa)!=null?g:_.pj("div");this.oa.style.inset="-1px";this.oa.style.position="fixed";this.oa.style.zIndex="1000";this.oa.style.background="black";this.oa.style.willChange="opacity";this.oa.style.transition="";this.oa.style.opacity="0";this.oa.style.pointerEvents=
"none";a.before(this.oa);d=this.oa}let e,f;this.Ga=(f=(e=this.L_a).FKa)==null?void 0:f.call(e,{M_a:a,fJa:2,J_a:[2],zSb:1,tpa:u9c(this,a,b,d),c2:w9c(this,a,b,d),options:void 0})}unsubscribe(){if("function"==typeof _.O8c&&this.Ga instanceof _.O8c){let a;(a=this.Ga)==null||a.unsubscribe()}else if(this.Ga instanceof AbortController){let a;(a=this.Ga)==null||a.abort()}this.Ja||(document.documentElement.style.overscrollBehaviorY="",document.body.style.overscrollBehaviorY="",this.Ja=!0)}};_.Gh(_.obb,x9c);
_.e8c(x9c);

_.l();
_.k("yx4a8e");
_.PGe=new Map;_.QGe=null;_.RGe=!1;_.SGe=new _.VVb;
(function(a,b={}){_.PGe.set(a,b)})(10,{UUb:!0});
_.l();
_.k("Dkk6ge");
_.y9c=new _.nf(_.pbb);
_.l();
_.k("JXS8fb");
_.cud=new _.nf(_.gq);
_.l();
_.eO=class extends _.q{constructor(a){super(a,3)}getViewerType(){return _.rk(this,1)}oa(a){return _.ph(this,1,a)}};_.rce=new _.ag("cinoBd",class extends _.q{constructor(a){super(a)}},_.eO,[_.wq,!0,_.xq,"/ViewerService.WriteFootprint"]);
_.k("J29Kkd");
var Rwm=function(a){let b=(0,_.Evc)(a)?a:void 0;a=_.Qae(a);!b&&a&&a.hasExtension(_.Hvc)&&(b=_.Fvc(_.yl(a,_.Hvc)));return b},Swm=function(a,b){return a.map(b)},Twm=function(a){return _.Io(a.getData("tbnid"))},Uwm=function(a){return Twm(a)?a.getData("pending").Sb()?1:2:0},Vwm=function(a){a=a.wb();return{ub:a.className,jsname:a.getAttribute("jsname"),ariaHidden:a.getAttribute("aria-hidden")!==null}},Wwm=function(a,b){a=a.wb();a.className=b.ub;a.setAttribute("jsname",b.jsname);b.ariaHidden?a.setAttribute("aria-hidden",
"true"):a.removeAttribute("aria-hidden")},Xwm=function(){var a=(0,_.Ut)();return _.z(a,139)},Ywm=function(){var a=(0,_.Ut)();return _.Jg(a,129)},Zwm=function(a){var b=new _.VMb;a.Aa=b},$wm=function(a,b){if((a=a.oa.get(b))!=null){let c;(c=a.state.Jf)==null||c.oa.startTime==null||a.state.oa!=="sa"||a.state.Ea||(a.state.Ea=_.Qx(a.state.Jf.oa.elapsedTime()),_.Sx(a.state.Jf,"uvphct"),a.state.Ja=!0,a.state.Xa.resolve())}},axm=function(a,b,c){let d;(d=a.oa.get(b))!=null&&d.state.oa==="sa"&&d.Aa(c)},bxm=
function(a,b){const c=a.oa.get(b);c&&c.state.oa==="sa"&&a.oa.has(b)},cxm=function(a,b,c){return _.kf(function*(){return _.quc(a,b,c)})},dxm=function(a,b){return!!a.Aa().find(c=>c.wk()===b)},exm=function(a,b){if((0,_.Evc)(b)&&_.B(b,5))return new _.ch(_.B(b,5),3);var c=_.Qae(b);if(c){b=b.wk();if(a.Ya()&&c.getType()!==23){var d=b?(d=a.kb.sessionStorage.get(a.hb))&&_.$f(d)?d[b]||null:null:null;return d?new _.ch(d,3):null}let g;var e;a=a.RDa;if(c.getId()){b="data-tbnid";var f=c.getId();_.sFb(c)&&(b="data-id");
let h;if((h=(e=c.Pc())==null?void 0:e.hasExtension(_.isc))!=null&&h){e=f.split("-");if(e.length<2)throw Error("Xg`"+f);f=`${e[0]}-${e[1]}`}e=_.dJd(a,f,b)}else e=null;e=(g=e)==null?void 0:g.el();c=(d=c.Pc())==null?void 0:_.nk(d,5);if(e)return _.dh(e,3)||null;if(c)return new _.ch(c,3)}return null},fxm=function(a,b){return a.Aa().findIndex(c=>c.wk()===b)},gxm=function(a){if(a.Na===void 0){if(a.Yda)var b=a.oa;else{b=a.aU.getScope(a.oa).oa;const c=_.RFb(b,_.QFb(b,a.clusterId));b=_.TFb(b,c);b=b[b.length-
1].id()}a.Na=b}return a.Na},hxm=function(a){a=a||{};var b=a.Xn;a=a.Vb;b="<div"+_.N(_.Tw())+(a!=null?" ssk='"+_.L(_.Ss("n2bbUd")+a)+"'":"")+_.u(new _.I(_.IOb,_.bs(new _.ds,_.zl(new _.Rr,_.FOb,_.DOb(b)))),!1)+"></div>";return(0,_.Ns)(b)},ixm=function(a){a=a||{};var b=a.Xn;a=a.Vb;b="<div"+_.N(_.Tw())+(a!=null?" ssk='"+_.L(_.Ss("mWMspb")+a)+"'":"")+_.u(new _.I(_.HOb,_.bs(new _.ds,_.zl(new _.Rr,_.FOb,_.DOb(b)))),!1)+"></div>";return(0,_.Ns)(b)},jxm=function(a){return _.pZb(a.jsname,a.content,a.Xn,a.class,
a.ariaHidden,a.xBc,a.Vb)};var kxm=function(a,b,c){a.oa.forEach((d,e)=>void c(d,b[e],e))},lxm=function(a,b){a.oa=b;kxm(a,a.Ga,Wwm)},mxm=function(a,b){const [c,d,e]=a.oa;var f=a.map(Twm)[1];f&&(f===b[2]?(e.remove(),f=_.yp(a.Aa("sG7ZCe")),c.before(f),lxm(a,[f,c,d])):f===b[0]&&(c.remove(),f=_.yp(a.Aa("R5S48d")),e.after(f),lxm(a,[d,e,f])));const g=a.map(Twm),h=a.map((m,n)=>g[n]===null||g[n]===b[n]?!1:!0);h.some(m=>m)&&(f=a.map((m,n)=>{if(!h[n])return m;n=_.yp(a.Aa(["sG7ZCe","CGzTgf","R5S48d"][n]));m.replaceWith(n);return n}),lxm(a,
f))},nxm=function(a,b,c=!1){kxm(a,b,(d,e,f)=>{d.setStyle("display",!e||f!==1&&c?"none":"block")})},oxm=function(a,b,c){return _.kf(function*(){a.empty();a.setData("tbnid",b);a.setData("pending","true");a.append(yield c);a.setData("pending",null)})},pxm=class{constructor(a,b){this.Ea=a;this.Aa=b;this.oa=this.Ea.children().toArray().map(_.yp);this.Ga=this.map(Vwm)}lN(){return this.oa[0]}current(){return this.oa[1]}next(){return this.oa[2]}map(a){return this.oa.map(a)}};var qxm=class extends _.q{constructor(a){super(a)}getImageUrl(){return _.B(this,1)}oa(){return _.nk(this,1)}hx(){return _.nk(this,2)}RT(){return _.r(this,_.Pg,5)}};var rxm=_.ie(1E3,_.eO,qxm);var sxm,txm,uxm,vxm,wxm,zxm,Axm,x$,Bxm,Cxm,Fxm,Gxm,Hxm,Lxm,Mxm,Pxm,Qxm,Nxm,Oxm,yxm,Sxm,Txm,Dxm,Exm,Uxm,Wxm,Yxm,Vxm,Zxm,$xm,Xxm,aym,bym,xxm,Jxm,Kxm,Rxm,cym,dym;_.oWb&&((sxm=window)==null?0:(txm=sxm.google)==null?0:txm.zl)&&(window.google.zl.qvd=!0);uxm=null;vxm=[1,6,23];wxm=function(a,b){_.$o(a,"transform",b?`translate3d(${b}px, ${0}px, 0)`:"")};zxm=function(a){a.Pb.mU()&&(a.Pb.vL(()=>xxm()),a.Ih=!0,a.addOnDisposeCallback(()=>void yxm(a)))};
Axm=function(a,b,c,d=!1){const e=b.wk();a.Ah.has(e)||(a.Ah.add(e),c&&_.$e(c,"XbKQde",{xna:d}),_.Cq(()=>a.Ah.delete(e),5E3))};x$=function(a,b){return b>=0&&b<a.Ga().length};Bxm=function(a,b,c=a.Ka()){const d=b.targetElement.el();return _.kb(c.find("scrolling-carousel").toArray(),c.find("g-scrolling-carousel").toArray(),c.find(".xbmkib").toArray(),c.find(".ZsmQ7d-eteedb").toArray()).some(e=>e.contains(d))};
Cxm=function(a,b){return _.kf(function*(){a.Kf&&(a.HEa.uTb(a.tS.wb(),b),a.Wd&&_.Ue(a.Wd),a.Wd=_.Te(a.Ka().wb(),"ucVTnf",()=>{_.Pwm(a.JR,!0);a.W$.setStyle("opacity","0");let c;(c=a.hb)==null||c.hide()}),a.le&&_.Ue(a.le),a.le=_.Te(a.Ka().wb(),"s2IYHc",()=>{_.Pwm(a.JR,!1);a.W$.setStyle("opacity","1");let c;(c=a.hb)==null||c.update(!0,!0,a.Ea,a.Ga().length)}),a.Kd&&_.Ue(a.Kd),a.Kd=_.Ve(a.Ka().wb(),"VOy8xe",()=>_.kf(function*(){_.Pwm(a.JR,!0);a.jc=!0;yield a.Qr()})))})};
Fxm=function(a){return _.kf(function*(){const b=a.Ga(),c=a.oa.map((g,h)=>{g=a.Ea-1+h;return x$(a,g)?b[g]:null});var d=Swm(c,g=>{let h;return(h=g==null?void 0:g.wk())!=null?h:null});mxm(a.oa,d);a.uc=null;d=Swm(c,g=>!!g);nxm(a.oa,d,_.WVb);a.zj();const e=[],f=a.oa.map(Uwm);kxm(a.oa,c,(g,h,m)=>{if(h){var n=f[m];n===0?(n=h.wk(),e.push(oxm(g,n,Dxm(a,h,m)).then(()=>void Exm(a,g,h)))):n===2&&Exm(a,g,h)}});a.Aa&&($wm(a.Ml,a.Aa),axm(a.Ml,a.Aa,a.oa.current().el()));yield Promise.all(e)})};
Gxm=function(a,b,c){return _.kf(function*(){var d=a.jn;d.Sa=b;d=d.Aa();const {eOb:e,results:f}={eOb:d[b],results:d};a.kb=b-1;a.Sa=b+1;d=a.Aa;e&&(a.Aa=e.wk());if(a.Aa){var g=a.Ml,h=a.Aa;_.CRb.has(c)&&_.ERb(g,h,!1)}yield Fxm(a);g="";if(a.oa.current().el()&&(h=a.oa.current().el().querySelector("[aria-label]"))){var m;g=(m=h.getAttribute("aria-label"))!=null?m:""}if(g.length===0&&a.sourceElement&&(m=a.sourceElement.querySelector("[alt], [aria-label]"))){var n;let p;g=(p=(n=m.getAttribute("aria-label"))!=
null?n:m.getAttribute("alt"))!=null?p:""}if(g.length>0){let p;(p=a.ZK.el())==null||p.setAttribute("role","dialog");let t;(t=a.ZK.el())==null||t.setAttribute("aria-label",g)}else{let p;(p=a.ZK.el())==null||p.setAttribute("role","");let t;(t=a.ZK.el())==null||t.setAttribute("aria-label","")}n=a.Aa;n!==d&&(_.$e(a.Ka().el(),"OPpNPb",n),_.$e(a.Ka().el(),"wMvXeb",d));_.$e(a.Ka().el(),"TwZGwe",a.Aa,c,a.sourceElement);a.Mz(a.Aa);a.Ea+3>=f.length&&_.$e(a.window.getDocument().body,"bXJUz",gxm(a.jn))})};
Hxm=function(a,b,c=!0){a.Jd=b;wxm(a.tS.wb(),b);a.tS.el().classList.toggle("Fx8vcb",b!==0);for(const d of a.eL)wxm(d,b);if(c){b=_.Vi(b/a.RP().width,-1,1);c=a.Ja?-1:1;let d;(d=a.hb)==null||d.update(!0,!1,a.Ea+b*c,a.Ga().length)}};_.Ixm=function(a){let b,c,d,e;return(e=(b=_.Qae(a))==null?void 0:(c=b.Pc())==null?void 0:(d=_.cn(c))==null?void 0:d.Jc())!=null?e:null};
Lxm=function(a,b,c,d){return _.kf(function*(){var e=_.Qae(b);switch(d){case 1:case 2:case 6:case 5:case 8:case 9:case 10:var f=Jxm(a,b),g=typeof(f==null?void 0:f.QN)==="string"?new _.ah(f.QN):void 0,h=b.wk();f={replace:!0,SHb:!0,clusterId:c,Zc:f,Mc:g,MAa:!1,Y0:a.Y0()};(g=_.Uuc(a.Qh))?(f.t3=h,f.yu=g):(f.S6=h,f.V4=null);yield a.Qh.navigateToView(f)}var m;if((e==null?void 0:e.getType())===1||(e==null?void 0:(m=e.Pc())==null?void 0:_.Kk(m,6))===9)m=a.Qh,h=b.wk(),m.yb=h,m=Kxm(a,e,b),a.Qh.Na=m;(e==null?
void 0:e.getType())===23&&(e=Kxm(a,e,b),a.Qh.Na=e);"scrollRestoration"in a.window.get().history&&(a.window.get().history.scrollRestoration="auto")})};Mxm=function(a){switch(a){case 1:case 2:case 6:case 5:case 8:case 9:return!0;default:return!1}};
Pxm=function(a,b,c){_.kf(function*(){const d=a.Ga()[b];let e;const f=(e=a.oa.current().children().filter(g=>!!g["__deferred-log"]).first())==null?void 0:e.el();Nxm(a,d,c,f&&f["__deferred-log"]);f&&(f["__deferred-log"]=void 0);yield a.jn.sfa().wait();Oxm(a,d,b,c)})};Qxm=function(a){(a=a.ZK.el())&&(a=_.fna(a))&&_.Cp(window,"attn_viewer_open",!1,a)};
Nxm=function(a,b,c,d){const e=Jxm(a,b);var f;const g=((f=b.Mk())==null?void 0:f.getViewerType())||null;f=a.Ml;var h=b.wk();f=f.oa.get(h);f!=null?(f.oa(g?g:7),f=_.muc(f)):f=1;c=Rxm(a,c,e,g);var m;b=(m=_.Qae(b))==null?void 0:m.Pc();m=_.rxc(b?_.nxc(b):null,f);d instanceof _.QQb?(d.Jq=m,c&&(d.Mc=c),e&&(d.Zc=e),_.VQb(a.Xc,d)):c&&_.Ix(a.Db,{Mc:c,Jq:m,SF:_.oxc()})};
Oxm=function(a,b,c,d){var e=_.Qae(b),f;if((e==null?void 0:e.getType())===1||(e==null?void 0:(f=e.Pc())==null?void 0:_.Kk(f,6))===9){f=new qxm;c=_.Pk(f,4,c);f=_.vna(a.window.get());c=_.ee(c,_.Pg,5,f);d=_.sh(c,7,Mxm(d));var g,h;(c=e==null?void 0:(g=e.Pc())==null?void 0:(h=_.cn(g))==null?void 0:h.Jc())&&_.Bg(d,1,c);(g=b.wk())&&_.Bg(d,3,g);var m,n;(g=e==null?void 0:(m=e.Pc())==null?void 0:(n=m.getExtension(_.cr))==null?void 0:n.hx())&&_.Bg(d,2,g);var p;(e=e==null?void 0:(p=e.Pc())==null?void 0:p.Cp())&&
_.ph(d,8,e);var t;b=((t=b.Mk())==null?void 0:t.getViewerType())||7;t=_.zl((new _.eO).oa(b),rxm,d);a.Hf.fetch(_.rce.Ec(t))}};yxm=function(a){a.Ih&&a.Pb.mU()&&(a.Pb.pN(),a.Ih=!1)};Sxm=function(a){return _.kf(function*(){if(a.ob)_.mWb&&(yield _.Zuc(a.Qh),a.Qh.go(-1));else{_.kXb(a.window.getDocument());var b=(0,_.Ut)();_.z(b,92)?yield a.Qh.navigateToView({}):(yield _.Zuc(a.Qh),yxm(a),_.$e(a.Ka().el(),"wMvXeb",a.Aa),_.$e(a.Ka().el(),"TwZGwe",null))}})};
Txm=function(a,b){const c=b.target;return _.kb(a.Ka().find(".ZsmQ7d-tEE2Ac").toArray()).some(d=>d.contains(c))};Dxm=function(a,b,c){return _.kf(function*(){const d={Zc:_.dh(a.Qh.Ea()||void 0,3),SF:_.oxc()},e=Rwm(b);var f=x$(a,c-1);const g=x$(a,c+1);f=_.luc(_.kuc(_.juc(a.Y0()),f),g);let h;f={Wa:b.XP(),isActive:!1,Dr:f,imageHeight:(h=_.Po(a.getData("ih")))!=null?h:void 0,Yq:e};const {output:m,oa:n}=yield cxm(a.X$,f,d);m["__deferred-log"]=n;return m})};
Exm=function(a,b,c){if(c.wk()===a.Aa){b=b.wb();a.yd();Uxm(a);let d;(d=a.Fi)==null||d.hb(b);let e;(e=a.Fi)==null||e.kb(Rwm(c));let f;(f=a.Fi)==null||f.uc();_.$e(b,"BUYwVb")}};Uxm=function(a){_.kf(function*(){if(!_.kWb){var b,c;(c=(b=yield a.hc())==null?void 0:b.hc())==null||c.focus({preventScroll:!0})}})};
Wxm=function(a,b,c){const d=b.touches[0].clientX-(a.La||0);if(a.state!==1)if(a.mb){const e=a.Ja?d<0:d>=0,f=Math.abs(a.mb.scrollLeft),g=Math.round(a.mb.scrollWidth-a.mb.clientWidth-f);if(!(f<=1&&!e||g<=1&&e)){a.Cb=!0;return}}else if(a.rb){const e=a.Ja?d<0:d>=0;let f=!0;const g=a.rb.clientWidth;a.rb.childNodes.forEach(h=>{(0,_.oMc)(h)&&(h=h.getBoundingClientRect(),!e&&h.left<1?f=!1:e&&h.right>g+1&&(f=!1))});if(f)a.Cb=!1;else{a.Cb=!0;return}}a.aO||a.Cb||Vxm(a,d,c)||b.preventDefault()};
Yxm=function(a){a.Fb=0;a.yb=a.Ea;Xxm(a)};
Vxm=function(a,b,c){if(!a.Cc)return!0;if(a.state===0){var d=-a.tS.el().getBoundingClientRect().top;a.oa.lN().setStyle("top",`${d}px`);a.oa.next().setStyle("top",`${d}px`);a.state=1}d=a.oa.current().wb().clientWidth+10;var e=(b>0?1:-1)*Math.sqrt(Math.abs(b));b=Math.max(b,x$(a,a.Tl)?-d:e);b=Math.min(b,x$(a,a.Gf)?d:e);a.Eb=(b-a.mj)/(c-a.Oi+1);Hxm(a,b);a.mj=b;a.Oi=c;b=a.Ja?b<0:b>=0;c=!b;d=a.Ga();e=a.Ea;const f=a.oa.lN(),g=a.oa.next();b&&d.length-1>=e+1&&Zxm(a,d[e+1],g);c&&e-1>=0&&Zxm(a,d[e-1],f);return!1};
Zxm=function(a,b,c){const d=_.Ixm(b);d&&a.prefetch(d);Axm(a,b,c.wb(),!0)};$xm=function(a,b){a.jn.Ea=!1;const c=a.Jd,d=a.oa.current().wb().clientWidth;b=Math.abs(c/(b-a.ZN+1));(c>d/4&&a.Eb>-.2||c>0&&a.Eb>.2)&&x$(a,a.Gf)?(a.Fb=d+10,a.yb=a.Gf,Xxm(a,b)):(c<-d/4&&a.Eb<.2||c<0&&a.Eb<-.2)&&x$(a,a.Tl)?(a.Fb=-(d+10),a.yb=a.Tl,Xxm(a,b)):Yxm(a)};Xxm=function(a,b){a.state=2;a.startOffset=a.Jd;a.Wb=0;a.Lr=b?Math.min(Math.abs(a.Fb-a.startOffset)/b,100):100;aym(a,0)};
aym=function(a,b){a.Wb||(a.Wb=b);b=1-Math.pow(1-Math.min((b-a.Wb)/a.Lr,1),3);Hxm(a,a.startOffset+b*(a.Fb-a.startOffset));const c=a.window.get().requestAnimationFrame||a.window.get().webkitRequestAnimationFrame;b<1&&c?c(d=>{aym(a,d)}):_.Fi(()=>{a.jn.Ja=!1;a.state=0;a.yb===a.Ea?Hxm(a,0):a.showViewer(a.yb,a.yb===a.kb?1:2)})};bym=function(a){return _.kf(function*(){const b=_.Mu(a.oa.current(),"H9tDt").el();return b?a.Lg(b):null})};
xxm=function(){return _.kf(function*(){try{return!1}catch(a){return _.Jb(new ReferenceError("Cr",{cause:a})),!1}})};Jxm=function(a,b){var c;const d=(c=_.Qae(b))==null?void 0:c.getType();if(d&&!vxm.includes(d))return _.Jb(Error("Dr")),null;c=b.wk();if(b=exm(a.jn,b))return b;if(c!==null&&dxm(a.jn,c))return _.dh(a.Qh.Ea()||void 0,3)||null;if(a.sourceElement)return _.dh(a.sourceElement,3)||null;_.Jb(Error("Er"));return null};
Kxm=function(a,b,c){try{let d,e;const f=((d=Rwm(c))==null?void 0:_.B(d,5))||(b==null?void 0:(e=b.Pc())==null?void 0:_.B(e,5)),g=c.wk(),h=(n,p)=>{if(!n||!p)return!1;const t=n.dataset.ved===p;n=n.querySelectorAll(`[data-ved="${p}"]`).length>0;return t||n};let m=Array.from(a.window.getDocument().querySelectorAll(`[data-docid="${g}"]`)).filter(n=>h(n,f));m.length===0&&(m=Array.from(a.window.getDocument().querySelectorAll("[jsdata]")).filter(n=>{if(n&&g){var p;var t=n==null?void 0:(p=n.getAttribute("jsdata"))==
null?void 0:p.includes(g);n=n.querySelectorAll(`[jsdata="${g}"]`).length>0;t=t||n}else t=!1;return t}).filter(n=>h(n,f)));if(m.length===0){const n=a.Tb("dn277e").first()||a.Ka();m=Array.from(a.window.getDocument().querySelectorAll(`[data-tbnid="${g}"]`)).filter(p=>!n.el().contains(p))}return m.length===1?m[0]:null}catch(d){return null}};
Rxm=function(a,b,c,d){let e;b===1||b===6||b===9||b===2||b===5||b===8?c?(c=_.Nx(a.Xc,()=>a.Ib.Ac(b===1||b===6||b===9?hxm:ixm,{Xn:d}),{Zc:c},!1),e=_.bh(c,cym(b))):e=dym(a,b):b===10&&(e=_.bh(a.sourceElement,3));return e||null};cym=function(a){switch(a){case 1:case 2:return 21;case 6:case 5:case 0:return 3;case 8:case 9:return 5;case 3:return 26;default:return 1}};dym=function(a,b){return _.bh(a.Qh.Ea(),cym(b))};
_.y$=class extends _.Yu{static Za(){return{Jb:{soy:_.Ls},service:{config:_.dy,data:_.Ux,Ml:_.Tx,Qb:_.Jx,Nqa:_.eJd,Uc:_.Ox,Q1a:_.uuc,Of:_.WD,window:_.jv,k_a:_.Qwm,jU:_.azd,mY:_.HU,share:_.cud,visualViewport:_.fJd,viewport:_.vw,qO:_.rTb,Vq:_.fNb,navigation:_.hy,aaa:_.XMb,HEa:_.y9c},model:{IZ:_.Sae},Ff:{NJb:{jsname:"Na3C1e",ctor:_.u9d}}}}constructor(a){super();this.Fi=this.hb=this.uc=this.Ya=null;this.qn=void 0;this.Sa=this.kb=-1;this.eL=[];this.yb=-1;this.ej=0;this.Ja=!1;this.Jd=this.zG=0;this.Qc=!1;
this.Xa=this.Kb=this.La=null;this.Oi=this.mj=this.ZN=0;this.Kf=this.Cc=this.hC=!0;this.Um=!1;this.Fb=this.startOffset=this.Eb=0;this.aO=!1;this.rb=this.mb=null;this.Ih=this.Cb=!1;this.Lr=this.Wb=0;this.sourceElement=this.Kd=this.Wd=this.le=this.Aa=this.state=null;this.jc=!1;this.Ib=a.Jb.soy;this.Ko=a.service.config;this.Hf=a.service.data;this.Ml=a.service.Ml;this.Db=a.service.Qb;this.RDa=a.service.Nqa;this.Xc=a.service.Uc;this.X$=a.service.Q1a;this.Qh=a.service.Of;this.window=a.service.window;this.YQ=
a.service.mY;this.Pb=a.service.share;this.vS=a.service.jU;this.fq=a.service.viewport;this.xta=a.service.visualViewport;this.JR=a.service.k_a;this.qO=a.service.qO;this.hK=a.service.Vq;this.Wc=a.service.navigation;this.aaa=a.service.aaa;this.HEa=a.service.HEa;this.jn=a.model.IZ;this.Fya()===10&&Xwm()?this.Cc=!1:(this.Cc=!0,this.hb=a.Ff.NJb);this.ZK=this.Tb("dn277e").first()||this.Ka();this.W$=this.Tb("xFKZqd");this.ob=this.Qh.ob();(this.IH=this.Qh.IH())&&Zwm(this.aaa);this.tS=this.Va("To2LVe");this.oa=
new pxm(this.tS,d=>this.Ib.Ac(jxm,{jsname:d}));(a=this.ZK.closest(_.Ho("jsname","Sva75c")).first())&&(0,_.oMc)(a.el())&&(a=a.wb().querySelector('[jsname="ootzjb"]'),(0,_.oMc)(a)&&this.eL.push(a));this.Ja=_.bp(this.window.getDocument().documentElement,"direction")!=="rtl";this.state=0;this.Tg=new Set;this.Ah=new Set;let b;this.LIa=(b=Ywm())!=null?b:100;_.Qu(this).listen(this.window.getDocument().body,"keydown",d=>{if(this.Qh.Rna()){var e,f;((e=this.window.getDocument().activeElement)==null?void 0:
e.tagName)==="INPUT"||((f=this.window.getDocument().activeElement)==null?void 0:f.tagName)==="TEXTAREA"||this.Es()||Txm(this,d)||(d.key!=="Escape"||this.oca?!this.hC||d.ctrlKey||d.altKey||d.shiftKey||d.metaKey||(e=this.Ja?d.key==="ArrowRight":d.key==="ArrowLeft",(this.Ja?d.key==="ArrowLeft":d.key==="ArrowRight")&&x$(this,this.kb)?(this.showViewer(this.kb,9),d.preventDefault()):e&&x$(this,this.Sa)&&(this.showViewer(this.Sa,8),d.preventDefault())):this.od(5))}});this.window.getDocument().body.style.opacity=
"";_.$e(this.window.getDocument(),"kyj0be",!0);zxm(this);const c=_.Te(this.window.getDocument().body,"aQMtle",()=>{this.Nv()});this.addOnDisposeCallback(()=>{_.Ue(c)});this.Ya=_.SGe.new({Sx:this,window:this.window.get()});this.tW();this.oca=!this.Qh.IH();this.wd=null;this.Ka().setStyle("visibility","")}get Ea(){return this.jn.Sa}tW(){}yd(){}zS(){const a=this;return _.kf(function*(){Axm(a,a.Ga()[a.Ea],a.oa.current().wb(),!1);let b;(b=a.Fi)==null||b.Pb(a.zOa().wb());let c;yield(c=a.Ya)==null?void 0:
c.La(a.fe())})}fe(){let a,b;return(b=(a=this.sourceElement)==null?void 0:a.querySelector('[jsname="zccVWc"]'))!=null?b:this.sourceElement}Bv(){return document.querySelector(`[jsname="${"VVvY3e"}"][data-tbnid="${this.Aa}"]`)}xt(){const a=this;return _.kf(function*(){let b;(b=a.hb)==null||b.hide();a.Lj()})}oL(){const a=this;return _.kf(function*(){var b;(b=a.hb)==null||b.hide();if(a.Qc||a.jc)a.Lj();else{a.YN();b=a.Bv();let c;yield(c=a.Ya)==null?void 0:c.Aa(b!=null?b:a.sourceElement,b?600:a.LIa)}})}dh(){const a=
this;return _.kf(function*(){if(x$(a,a.Sa)){let b;yield(b=a.Ya)==null?void 0:b.Ja(700)}})}yta(){const a=this;return _.kf(function*(){const b=yield a.hc();b instanceof _.Ey&&(yield b.yta())})}RP(){return this.YQ.RP(this.Ka().el())}Ip(a){_.Mu(this.oa.current(),"PgO4Pc").toArray().forEach(b=>{b.contains(a.targetElement.el())&&(this.mb=b)})}Jp(a){this.Ka().find(".QbMJkd-UUyOHe-eteedb").toArray().forEach(b=>{b.contains(a==null?void 0:a.targetElement.el())&&!Bxm(this,a,new _.sp(b))&&(this.rb=b)})}Hd(){return _.kf(function*(){})}KS(a){a.data.jHc<
2&&(Fxm(this),this.dh())}Ee(){const a=this.oa.current().wb()||this.window.getDocument().documentElement,b=a.getElementsByClassName("E4R9Oc");return b.length>0?b[0]:a}Yn(){const a=this.Ee();let b;((b=this.XN)==null?void 0:b.Iqa)!==a&&(this.XN={Iqa:a,Oj:_.xMc(a)});return this.XN.Oj}Mz(){}Es(){return!1}zj(){const a=(this.Ja?1:-1)*(this.RP().width+10);kxm(this.oa,[-a,0,a],(b,c)=>{wxm(b.wb(),c)})}gC(){var a=0;this.Qh.nya&&(a=3);var b=fxm(this.jn,this.jn.Ga||"");if(b>=0){var c=null;this.oa.current().children().get(0)&&
(c=this.Ga()[b]);var d;if(c=c==null?void 0:(d=c.Mk())==null?void 0:d.getViewerType()){if(d=this.jn.oa,d.indexOf("-")>0&&(d=d.substring(0,d.indexOf("-"))),_.Auc.includes(c)||_.Buc.includes(d))this.Um=!0}else this.Um=!1;this.showViewer(b,a)}else a=`In render no metadata with cardId ${this.jn.Ga||null}`,(b=_.or.oa)&&b.oa(Error(a),`${a} (results.length='${this.Ga()?this.Ga().length:"null"}
              , historyParam=' + ${_.Io(this.jn.getData("hp"))}
              , initialStreamId=' + ${this.jn.Ga||null}
              , query=' + ${this.jn.getQuery()})`)}Ye(){}prefetch(a){const b=this;return _.kf(function*(){if(!b.Tg.has(a)){b.Tg.add(a);try{yield _.Zyd(b.vS,a)}catch(c){}_.Cq(()=>b.Tg.delete(a),5E3)}})}DS(){this.od(3)}W1(){x$(this,this.Sa)&&this.showViewer(this.Ea+1,5)}C2(){x$(this,this.kb)&&this.showViewer(this.Ea-1,6)}m1(a){a=a.data;const b=a.index;x$(this,b)&&this.Ea!==b&&(this.Od({element:a.jGb}),this.showViewer(b,10))}showViewer(a,b){const c=this;return _.kf(function*(){if(c.Qh.meb())yield c.Qh.RCa(!0),
yield c.showViewer(a,b);else{Hxm(c,0,!1);var d;(d=c.hb)==null||d.update(!0,!0,a,c.Ga().length);c.Vh();yield Gxm(c,a,b);c.Aa&&bxm(c.Ml,c.Aa,c.Ka().wb().getElementsByTagName("img"));d=c.Ga();var e=d[a];yield Lxm(c,e,c.jn.clusterId,b);var f;c.window.getDocument().dispatchEvent(new CustomEvent("viewerUpdated",{detail:{id:gxm(c.jn),k:a,vhid:e==null?void 0:e.wk(),vid:c.jn.oa,r:e==null?void 0:(f=e.XP())==null?void 0:f.Yc(),av:Mxm(b)}}));Pxm(c,a,b);c.sourceElement=c.Qh.Na;c.Ek();if(!c.IH&&!_.Tt(c.Ko.oa())){let g;
yield Cxm(c,(g=c.fe())!=null?g:void 0)}f=d.map(g=>_.Wu(_.Vu(_.Su(new _.Wt,g==null?void 0:g.Mk()),g==null?void 0:g.wk()),g==null?void 0:g.XP()));_.$e(c.Ka().el(),"bBWxY",f);Qxm(c);c.Hd()}})}Nv(){_.Ix(this.Db,{Mc:_.bh(this.Na().el(),26)})}IG(){_.Ix(this.Db,{Mc:_.bh(this.Oe().el(),3)});this.Qh.RCa()}yk(){this.ej||(this.ej=setTimeout(()=>{this.Ka().wb().style.setProperty("--viewer-panel-height",`${this.Ka().el().clientHeight}px`);const a=this.RP().width;a!==this.zG&&(this.zj(),this.zG=a);this.ej=0}))}Vh(){if(!_.kWb){var a;
(a=this.qn)==null||_.LWb(a);this.qn=void 0}}kL(){return!this.Ee().scrollTop}wp(a){const b=a.event;if(!(this.jn.H0()||b.touches.length>1)){var c,d,e,f=((c=this.Ya)==null?0:c.Ea())?(e=(d=this.Ya)==null?void 0:d.Ga())!=null?e:0:0;c=b.touches[0];this.Qc=!1;this.La=c.clientX-f;this.Kb=c.clientY;this.Xa=f?2:0;this.ZN=b.timeStamp;this.mj=f;this.Oi=b.timeStamp;this.rb=this.mb=null;this.Cb=!1;this.Jp(a);this.aO=!this.rb&&Bxm(this,a);this.Ip(a);this.Xa===2&&(this.jn.Ea=!0,Wxm(this,b,b.timeStamp))}}nL(a){const b=
a.event;var c=b.touches[0];this.Qc=!1;if((c==null?void 0:c.clientX)<0||(this.La||0)<=16)this.Qc=!0,Yxm(this);else if(b.touches.length<1&&!this.jn.H0())this.Kb=this.La=null;else if(this.La===null&&c&&this.wp(a),this.state===2)b.preventDefault();else switch(a=b.touches[0].clientX-(this.La||0),c=b.touches[0].clientY-(this.Kb||0),this.Xa===0&&(Math.abs(a/c)>=1.5?Math.abs(a)>=6&&(this.Xa=2,this.jn.Ea=!0):Math.abs(c/a)>=1.5&&(this.Xa=1)),a=b.timeStamp,this.Xa){case 2:Wxm(this,b,a);break;case 0:b.preventDefault()}}YN(){if(!this.sourceElement||
_.XTc(this.sourceElement)){var a=this.JR,b=a.Sa;var c=(0,_.Ut)();c=_.z(c,31);b.call(a,c?this.Aa:null)}else this.sourceElement.scrollIntoView({inline:"nearest",block:"nearest"}),a=this.JR,_.Tt(a.Ko.oa())||(a.oa=a.Oj.Yv())}mL(a){a=a.event;if(a.touches.length===0)if(this.La===null)this.Kb=this.La=null;else if(a=a.timeStamp,this.Kb=this.La=null,this.state===1)switch(this.Xa){case 2:$xm(this,a)}}Qr(){const a=this;return _.kf(function*(){try{let b;yield(b=a.Ya)==null?void 0:b.Aa(a.sourceElement,a.LIa)}catch(b){_.Jb(Error("Br",
{cause:b}))}a.state=0;a.jn.Ja=!1;a.Ka().setStyle({position:""});yield a.od(21)})}Od({element:a}){this.sourceElement=a}rS(){return{element:this.sourceElement}}od(a){const b=this;return _.kf(function*(){const c=b.Na();c&&_.Ix(b.Db,{Mc:_.bh(c.el(),a)});yield Sxm(b)})}Ux(){const a=this;return _.kf(function*(){a.Qh.Rna()&&(yield Sxm(a))})}Na(){return _.Mu(this.oa.current(),"tqp7ud")}Oe(){return _.Mu(this.oa.current(),"Cdl0yb")}lL(a){a.event.touches.length===0&&Yxm(this)}HS(a){const b=a.data.timeStamp;
(a=a.data.offset.x)&&Vxm(this,a,b)}JS(a){const b=a.data.timeStamp,c=a.data.offset.x;a.data.Ygb?Yxm(this):c&&$xm(this,b)}f1(a){this.hC=a.data}eU(a){this.Cc=a.data}i1(a){(this.Kf=a.data)||this.HEa.unsubscribe()}hc(){const a=this;return _.kf(function*(){a.uc||(a.uc=yield bym(a));return a.uc})}uS(){return _.kf(function*(){})}p_(){return this.W$}FS(){return this.ZK}Edb(){let a;(a=this.oa.lN())==null||a.hide();let b;(b=this.oa.next())==null||b.hide()}Pjb(){let a;(a=this.oa.lN())==null||a.show();let b;(b=
this.oa.next())==null||b.show()}zOa(){const a=_.tp(this.oa.current(),".FyHeAf");return a.isEmpty()?_.tp(this.Ka(),"[jsname=YQKdAf]"):a}o_(){return this.tS}Fya(){let a,b;return(b=(a=this.Ga()[this.Ea].Mk())==null?void 0:a.getViewerType())!=null?b:0}Lj(){if(this.jc){this.jc=!1;this.Ek();this.sourceElement&&(this.sourceElement.style.opacity="1");var a=this.tS.wb();a&&(a.style.transformOrigin="");for(const b of[this.oa.lN(),this.oa.next()])a=b.wb(),a.style.display="block",a.style.opacity="",a.style.visibility=
""}}Ek(){_.jUc();let a;(a=uxm)==null||a.remove();uxm=null}Cr(){const a=this;return _.kf(function*(){const b=yield a.hc();b instanceof _.Ey&&(yield b.Fb())})}get Gf(){return this.Ja?this.kb:this.Sa}get Tl(){return this.Ja?this.Sa:this.kb}Ga(){return this.jn.Aa()}Y0(){this.Fya();return this.Um}};_.y$.prototype.$wa$tRyKAe=function(){return this.Y0};_.y$.prototype.$wa$yArZRd=function(){return this.Ga};_.y$.prototype.$wa$Q6YbSb=function(){return this.Cr};_.y$.prototype.$wa$MYe5Uc=function(){return this.Ek};
_.y$.prototype.$wa$JdBUhf=function(){return this.Lj};_.y$.prototype.$wa$MXIqkf=function(){return this.Fya};_.y$.prototype.$wa$xSjSX=function(){return this.o_};_.y$.prototype.$wa$GEPTmf=function(){return this.zOa};_.y$.prototype.$wa$VuVBb=function(){return this.Pjb};_.y$.prototype.$wa$VWlsfb=function(){return this.Edb};_.y$.prototype.$wa$rUm1qb=function(){return this.FS};_.y$.prototype.$wa$MoDOK=function(){return this.p_};_.y$.prototype.$wa$geL4Eb=function(){return this.uS};
_.y$.prototype.$wa$iH8nrf=function(){return this.hc};_.y$.prototype.$wa$IRuuWd=function(){return this.i1};_.y$.prototype.$wa$JcQbHe=function(){return this.eU};_.y$.prototype.$wa$hTA2he=function(){return this.f1};_.y$.prototype.$wa$hGQO5e=function(){return this.JS};_.y$.prototype.$wa$Cw6uhb=function(){return this.HS};_.y$.prototype.$wa$YPcXab=function(){return this.lL};_.y$.prototype.$wa$DUmD7e=function(){return this.Oe};_.y$.prototype.$wa$ev8l7c=function(){return this.Na};
_.y$.prototype.$wa$I2OR7b=function(){return this.Ux};_.y$.prototype.$wa$dsJZzf=function(){return this.rS};_.y$.prototype.$wa$AOmjrc=function(){return this.Qr};_.y$.prototype.$wa$wk6gCc=function(){return this.mL};_.y$.prototype.$wa$axxrud=function(){return this.YN};_.y$.prototype.$wa$oIUeFe=function(){return this.nL};_.y$.prototype.$wa$TRapdd=function(){return this.wp};_.y$.prototype.$wa$b4iS2b=function(){return this.kL};_.y$.prototype.$wa$yBLDjf=function(){return this.Vh};
_.y$.prototype.$wa$mhSdVe=function(){return this.yk};_.y$.prototype.$wa$uLRcHe=function(){return this.IG};_.y$.prototype.$wa$LvQSUe=function(){return this.Nv};_.y$.prototype.$wa$x7os4c=function(){return this.m1};_.y$.prototype.$wa$dYRl4b=function(){return this.C2};_.y$.prototype.$wa$awLsX=function(){return this.W1};_.y$.prototype.$wa$E2e5Sd=function(){return this.DS};_.y$.prototype.$wa$ycRj9d=function(){return this.Ye};_.y$.prototype.$wa$D5BN=function(){return this.gC};_.y$.prototype.$wa$V94cRb=function(){return this.zj};
_.y$.prototype.$wa$WFrkbb=function(){return this.Es};_.y$.prototype.$wa$FvSfLc=function(){return this.Yn};_.y$.prototype.$wa$PK2OVe=function(){return this.Ee};_.y$.prototype.$wa$vJLmKc=function(){return this.KS};_.y$.prototype.$wa$xd9j7b=function(){return this.Hd};_.y$.prototype.$wa$cPE6G=function(){return this.Jp};_.y$.prototype.$wa$t2kiJb=function(){return this.Ip};_.y$.prototype.$wa$MLHG2b=function(){return this.yta};_.y$.prototype.$wa$CLTwce=function(){return this.dh};
_.y$.prototype.$wa$qAf8Hf=function(){return this.xt};_.y$.prototype.$wa$kZfvAf=function(){return this.Bv};_.y$.prototype.$wa$a7cIt=function(){return this.fe};_.y$.prototype.$wa$CNNeqb=function(){return this.yd};_.y$.prototype.$wa$IaQd1e=function(){return this.tW};_.av(_.qbb,_.y$);
_.y$.prototype.Mz=function(a){var b=this.jn;b.Yda||b.oa!==_.z2a.id(1)?this.jn.oa==="regis"?(a=a.split("-"),a.length<2||_.$e(document.body,"JAJ25d",`${a[0]}-${a[1]}`)):_.$e(document.body,"JAJ25d"):_.$e(document.body,"JAJ25d",a)};_.y$.prototype.Ye=function(){var a=this.Ga();if(this.Ea>0){const b=_.Ixm(a[this.Ea-1]);b&&this.prefetch(b)}this.Ea+1<a.length&&(a=_.Ixm(a[this.Ea+1]))&&this.prefetch(a)};_.y$.prototype.$wa$ycRj9d=function(){return this.Ye};
_.y$.prototype.Es=function(){return this.Pe!=null&&this.Pe.Es()};_.y$.prototype.$wa$WFrkbb=function(){return this.Es};_.y$.prototype.Hd=function(){const a=this;return _.kf(function*(){a.Pe==null&&(a.Pe=yield _.mg(_.Iq,a.Mj()))})};_.y$.prototype.$wa$xd9j7b=function(){return this.Hd};




_.l();
});
// Google Inc.
