loaded_h_0(function(_){var window=this;
_.kYr=_.x("oWVrne",[]);
_.t("oWVrne");
var lYr=class extends _.m{constructor(a){super(a)}getQuery(){return _.A(this,1)}setQuery(a){return _.Sf(this,1,a)}Zg(){return _.xj(this,1)}sB(){return _.A(this,68)}};lYr.prototype.ob="A7MAsf";_.mYr=class extends _.ih{static Sa(){return{jsdata:{jRe:lYr}}}constructor(a){super();this.data=a.jsdata.jRe}};_.Gr(_.kYr,_.mYr);
_.v();
_.t("oUlnpc");
_.jYr=new _.Me(_.hZa);
_.v();
_.MXr=_.x("vRe0ve",[]);
_.t("vRe0ve");
_.NXr=class extends _.co{};_.Oe(_.MXr,_.NXr);
_.v();
_.GXr=_.x("pj8IAe",[_.Iq]);
_.t("pj8IAe");
var HXr,IXr,JXr;HXr={Tlf:"ip",RBf:"ss"};IXr=["ss","ip"];JXr=async function(a,b){for(const c of IXr){const d=b.find(e=>e.oac()===c);if(d){d.oXc();break}}document.body.style.opacity&&(document.body.style.opacity="");for(const c of a.Aa)c()};_.KXr=async function(a,b){try{_.y(await _.y(b.cWc()));let c;(c=a.oa.get(b.oac()))==null||c.resolve(b)}finally{_.y()}};
_.LXr=class extends _.co{static Sa(){return{service:{Cc:_.cv}}}constructor(a){super();this.oa=new Map;this.Aa=new Set;this.logger=this.I_=null;this.Cc=a.service.Cc;a=new _.Zt(this.Cc.location.hash);for(const b of Object.values(HXr))a.oa.get(b)&&this.oa.set(b,_.re());this.oa.size>0&&Promise.all(Array.from(this.oa.values()).map(b=>b.promise)).then(b=>JXr(this,b));this.I_=(0,_.Tn)(()=>{document.body.style.opacity&&(document.body.style.opacity="")},5E3)}Ub(){super.Ub();this.I_&&((0,_.Un)(this.I_),this.I_=
null)}};_.Oe(_.GXr,_.LXr);
_.v();
_.RYr=_.x("ogmBcd",[_.hZa,_.Iq,_.GXr,_.MXr,_.kYr,_.sPe]);
var OYr;_.PYr=function(a){var b=new OYr;b.context.set("arc_id",a);return b};_.QYr=function(a,b){switch(b){case "partial":case "all":a.context.set("ffilt",b)}return a};OYr=class{constructor(){this.context=new Map}build(){return this.context}setQuery(a){this.context.set("q",a);return this}};
var uYr,vYr;_.tYr={};uYr=null;vYr=_.re();_.tYr.IIe=function(a){uYr||(uYr=a,vYr.resolve(uYr))};_.tYr.kUa=function(){return uYr};_.tYr.ROb=function(){return vYr.promise};
var wYr;wYr=function(a,b,c){return b.lub(c).filter(d=>{const e=d.LX();return!(e in a.oa)||d.items.length!=a.oa[e].items.length})};_.xYr=function(a,b){(0,_.tYr.ROb)().then(c=>{const d=wYr(a,c,b);Object.keys(a.oa).length>0&&c.iFb(d);return c.DOc(d)}).then(c=>{for(const d of c)a.oa[d.LX()]=d})};_.yYr=class extends _.Le{constructor(){super();this.oa={}}};
var zYr=class{Xfc(){return""}Nib(){return""}};_.AYr=function(a,b){a.Ca=b};_.BYr=function(a,b){a.Da=b};_.CYr=function(a){const b=a.oa();if(b){var c=a.rJa.Nib(a.Sp,a.urlParams);a.Ba.reset(b,c);a.state=1}};
_.FYr=function(a,{Sp:b,urlParams:c,triggerElement:d,gia:e}={}){if(a.state!==3){var f=a.oa();f&&(a.state=3,b!=null&&(a.Sp=b),c!=null&&(a.urlParams=c),b=a.rJa.Xfc(a.Sp,a.urlParams),c=a.rJa.Nib(a.Sp,a.urlParams),a.Ba.fetch(f,a.Sp,a.urlParams,d,b,c,()=>{a.QKa&&a.QKa()},g=>{a.Aa&&a.Aa(g)},()=>{a.state=4;typeof a.Ha==="function"&&a.Ha();let g=_.Nf(document.body,f);g&&typeof a.Ka==="function"&&(g=a.Ka());return _.tf(g)},()=>{_.DYr(a)},()=>{a.Ea&&a.Ea()},{aU:a.aU,ijc:a.ijc,Oxb:a.Oxb,gia:e}).then(void 0,g=>
{_.EYr(a,g)}))}};_.DYr=function(a){_.xl.remove(a.oa(),"yp");a.state=2;typeof a.Ca==="function"&&a.Ca();a.Ma?_.xYr(a.Na,a.oa()):_.tf()};_.EYr=function(a,b){a.state=5;typeof a.Da==="function"&&a.Da(b)};
_.IYr=class extends _.Le{constructor(a,{Pja:b=!1,Jz:c=!1,Sp:d,rJa:e,urlParams:f,lQa:g=!1,aU:h=!1,ijc:k=!1,q2c:l=!1,Oxb:n=!1}={}){super();this.oa=a;this.Ma=!1;this.Da=this.QKa=this.Ka=this.Ha=this.Ea=this.Ca=this.Aa=null;this.Sp=d||new Map;this.rJa=e||new zYr;this.urlParams=f||new Map;this.Na=new _.yYr;this.aU=h;this.ijc=k;this.Oxb=n;this.state=c?5:b?2:1;this.Ba=g?_.GYr():_.HYr(l)}};_.HYr=function(){throw Error("Dx");};_.GYr=function(){throw Error("Ex");};
var JYr=function(a,b){a.containerId=b},KYr=function(a,b,c){return b().then(d=>{d&&(a.attach(),c())})},LYr=function(a,b,c,d,e,f={}){return c().then(g=>{a.oa=()=>{if(e){const h=new _.vyc(e);_.Nyc(h,b);_.Byc(h,b)}};g?(a.attach(),a.SOc(),d()):!e||(f==null?0:f.ijc)||e.log()})},MYr=class{constructor(a){this.q2c=a;this.node=null}SOc(){this.oa&&(this.oa(),this.oa=void 0)}reset(a,b){(0,_.Ky.reset)(a);b&&_.gwc.remove(b)}fetch(a,b,c,d,e,f,g,h,k,l,n,q={}){if(e&&(e=_.gwc.get(e)))return this.q2c&&JYr(e,`arc-${b.get("arc_id")}`),
this.node=e,n&&n(),KYr(this,k,l);let r;return(0,_.Ky.fetch)(a,b,d,c,u=>{r=u},g).then(u=>{f&&_.hwc(f,u);this.node=u;return LYr(this,a,k,l,r,q)})}attach(){return this.node?(this.node.apply(),!0):!1}};_.HYr=a=>new MYr(a);
var NYr=class{reset(a,b){_.Jy(a);b&&_.lBc(a,b)}fetch(a,b,c,d,e,f,g,h,k,l,n,{aU:q=!1,gia:r=!1,Oxb:u=!1}={}){!e&&f&&_.lBc(a,f);this.eIb=a;const {context:B,urlParams:G}=_.pwc(a,{trigger:d,Bqb:b,additionalParams:c});this.Zm={context:B,trigger:d,urlParams:G,Ss:f?new _.Gy(f):void 0,aOa:h,onReady:k,aU:q,QKa:g,gia:r,Oxb:u};this.cacheKey=f;this.Rsa()&&n&&n();return _.Hy(this.eIb,this.Zm).then(L=>{L&&l()})}Rsa(){return!!this.eIb&&!!this.cacheKey&&_.jBc(this.eIb,this.cacheKey)}attach(){if(this.Zm&&this.Rsa())return this.Zm.onReady=
()=>!0,_.Hy(this.eIb,this.Zm),!0;this.Zm?this.eIb?this.cacheKey?_.Yd(Error("Fx"),{level:0,zf:{src:"prog"}}):_.Yd(Error("Gx"),{level:0,zf:{src:"prog"}}):_.Yd(Error("Hx"),{level:0,zf:{src:"prog"}}):_.Yd(Error("Ix"),{level:0,zf:{src:"prog"}});return!1}SOc(){}};_.GYr=()=>new NYr;
_.oYr=function(){if(!_.pe("s"))return!0;try{window.openDatabase("","","",0)}catch(a){return!0}return!1};
_.CNg=class extends _.m{constructor(a){super(a)}Xk(){return _.A(this,1)}};_.DNg=[0,_.E,_.xk,[0,_.E],_.xk,_.E];_.ENg=_.Hb(_.DNg);
_.yNg=!!(_.uh[28]>>14&1);_.zNg=!!(_.uh[28]>>15&1);_.ANg=!!(_.uh[28]>>16&1);
var MFg,NFg;MFg=function(a){return a?a>=4?4:a>=3?3:a>=2?2:1:1};NFg=function(a,b,c,d){a=a.split("?")[0];d=MFg(d);b=b?b:0;c=c?c:0;var e=b*d;const f=c*d;e=Math.min(1,2048/(e?e:1),2048/(f?f:1));b=Math.floor(b*e);c=Math.floor(c*e);return`${a}?scale=${d}`+(c?`&h=${c}`:"")+(b?`&w=${b}`:"")};
_.OFg=function(a,b,c){const d=MFg(_.ca.devicePixelRatio),e=NFg(a.getAttribute("data-bsrc"),b,c,d);_.Hc([(0,_.Sb)`data-`],a,"data-bsrc",e);const f=()=>{a.removeEventListener("load",f,!1);a.style.display="";_.Fh(a.offsetHeight);a.style.zIndex="1";a.removeAttribute("height");a.removeAttribute("width");var g=_.ca.SCALE_MAP!==!1;d!==1&&g&&(c||(c=a.height/d),b||(b=a.width/d));c&&a.setAttribute("height",String(c));b&&a.setAttribute("width",String(b));(g=a.nextElementSibling)&&_.Im(g,!0)};a.addEventListener("load",
f,!1)};
var eOb;_.cOb=function(a){_.Bv.oa("iehc",a)};_.dOb=function(a){_.Bv.oa("r",a)};eOb=function(a,b,c){return _.Bv.subscribe(a,c!==null?d=>{d&&d===_.om(c,"xpdbox")&&b(d)}:b)};_.fOb=function(a,b){return eOb("hc",a,b||null)};_.gOb=function(a,b){return eOb("es",a,b||null)};_.hOb=function(a,b){return eOb("ef",a,b||null)};_.iOb=function(a,b){return eOb("cs",a,b||null)};_.jOb=function(a,b){return eOb("cf",a,b||null)};_.Cv=function(a){return _.Bv.FH(a)};_.Bv=new _.Av;_.kOb=function(a){_.Bv.oa("es",a)};
_.lOb=function(a){_.Bv.oa("ef",a)};_.mOb=function(a){_.Bv.oa("cs",a)};_.nOb=function(a){_.Bv.oa("cf",a)};
var PFg,QFg,RFg,UFg,XFg,YFg,ZFg,$Fg,WFg;PFg=function(a,b){for(b=new RegExp("(?:^|\\s)"+b+"(?:$|\\s)");a;){if(b.test(a.className))return a;a=a.parentElement}return null};QFg=function(a){const b={};if(!a.hasAttribute("data-vs"))return null;a.getAttribute("data-vs").split(",").forEach(c=>{c=c.split(":");b[c[0]]=c[1]});return b};_.TFg=function(a){a||(a=_.Ol("lu_vs"));a.length&&(RFg(),_.Ja(a,_.SFg))};RFg=async function(){try{_.y(await _.y(UFg())).addListener(_.VFg)}finally{_.y()}};
UFg=async function(){return _.Ne(_.Jq,_.Qb().oa)};
XFg=function(a){const b=QFg(a);if(!b)return null;const c=_.om(a,b.r);if(!c)return null;if(c.offsetWidth===0&&c.offsetHeight===0)return WFg(a),null;if(b.lukp!==void 0&&b.lukp){a=PFg(c,"kno-mrg");var d=PFg(c,"kno-mrg-m");d&&(d.style.width="auto",d.style.height="auto");a&&((d=a.getElementsByClassName("img-kc-m")[0])&&d.offsetHeight&&(c.style.height=d.offsetHeight+"px"),a=a.offsetWidth-(d?d.offsetWidth:0),a>0&&(c.style.width=`${a}px`))}a=0;b.w!==void 0&&(a=Math.floor(c.offsetWidth*parseFloat(b.w)));d=
0;b.h!==void 0&&(d=Math.floor(c.offsetHeight*parseFloat(b.h)));a&&d&&b.mhwr!==void 0&&(d=Math.max(d,a*parseFloat(b.mhwr)));return new _.Gl(a,d)};_.SFg=function(a){_.Hc([(0,_.Sb)`data-`],a,"data-bsrc",a.getAttribute("data-bsrc").split("&")[0]);var b=XFg(a);if(b&&(_.OFg(a,b.width,b.height),(b=QFg(a))&&b.o==="1"&&YFg.indexOf(a)===-1&&YFg.push(a),a.getAttribute("data-bsrc")!==a.getAttribute("src"))){if(!(a instanceof HTMLImageElement))throw Error("sq");a.src=a.getAttribute("data-bsrc")}};
_.VFg=function(){_.Ja(YFg,_.SFg)};YFg=[];ZFg=[];$Fg=[];WFg=function(a){ZFg.indexOf(a)===-1&&(ZFg.push(a),$Fg.push(_.hOb(()=>{_.SFg(a)})),$Fg.push(_.jOb(()=>{_.SFg(a)})))};
_.DTe=function(a,b){var c=new _.xTe,d=_.Te(a,"graftType");c.oa=d;c=_.yTe(c,_.Te(a,"asyncType"));d=_.Te(a,"asyncActions");c.Aa=d;d=_.Te(a,"asyncRclass");c.Ha=d;d=_.Te(a,"asyncContextRequired");c.Ba=d;c=_.zTe(_.ATe(_.BTe(c,_.Te(a,"asyncFc")),_.Te(a,"asyncFcv")),_.Te(a,"asyncOns"));a=_.Te(a,"asyncElrc");c.Da=a;b&&_.CTe(c,b);return c};_.yTe=function(a,b){a.Ka=b;return a};_.BTe=function(a,b){a.Ca=b;return a};_.ATe=function(a,b){a.Ma=b;return a};_.zTe=function(a,b){a.Ea=b;return a};
_.CTe=function(a,b){a.xma=b;return a};
_.xTe=class{build(){const a=_.Xl("DIV");this.id&&(a.id=this.id);this.xma&&_.Se(a,"ved",this.xma);this.oa&&_.Se(a,"graftType",this.oa);this.Ka&&_.Se(a,"asyncType",this.Ka);this.Aa&&_.Se(a,"asyncActions",this.Aa);this.Ha&&_.Se(a,"asyncRclass",this.Ha);this.Ba&&_.Se(a,"asyncContextRequired",this.Ba);this.Ca&&_.Se(a,"asyncFc",this.Ca);this.Ma&&_.Se(a,"asyncFcv",this.Ma);this.Ea&&_.Se(a,"asyncOns",this.Ea);this.Da&&_.Se(a,"asyncElrc",this.Da);_.Se(a,"jiis","up");return a}kd(a){this.id=a;return this}};
var P1c,X1c,M1c,N1c,S1c,Z1c,T1c,O1c,W1c,Y1c,b2c,Q1c,R1c,U1c,V1c,$1c;P1c=function(){M1c(N1c(),!1);O1c(!1)};X1c=function(a){if(Q1c)R1c.add(a);else{a=N1c(new Set([a]));let {key:b,value:c}=S1c();c=T1c(a,c,!0);U1c=d=>{d=N1c(d);c.current.A8a=Object.assign(c.current.A8a,d);V1c.set(b,c,"h")};Q1c=(0,_.Tn)(W1c,100);M1c(a,!0)}};M1c=function(a,b){let {key:c,value:d}=S1c();d=T1c(a,d,b);V1c.set(c,d)};
N1c=function(a){const b={};if(a){for(const c of a)(a=Y1c.get(c))&&(b[c]=a());return b}for(const [c,d]of Y1c)b[c]=d();return b};S1c=function(){const {metadata:a,url:b}=_.hf(),c=a?String(a.pushId):b;var d=V1c.get(c);d===null&&(d=V1c.get(b));d=_.cf(d)?d:{};return{key:c,value:{current:Z1c(d.current),last:Z1c(d.last)}}};Z1c=function(a){return a&&typeof a==="object"&&typeof a.A8a==="object"&&typeof a.sic==="number"?a:{A8a:{},sic:-1}};
T1c=function(a,b,c){b.current.sic!==$1c&&(b.last=b.current,b.current={A8a:{},sic:$1c});b.current.A8a=c?Object.assign(b.current.A8a,a):a;return b};O1c=function(a=!0){$1c++;(0,_.Un)(Q1c);W1c(a)};W1c=function(a=!0){a&&U1c&&R1c.size&&U1c(R1c);U1c=null;R1c.clear();Q1c=null};_.a2c=function(){try{return _.Vl().y}catch(a){return 0}};Y1c=new Map;b2c=new Map;Q1c=null;R1c=new Set;U1c=null;V1c=_.mf("s",{name:"sr"});$1c=_.th("performance.timing.navigationStart",_.Mg())||_.zh();
_.Kpa.set("ps",{getState:function(a,b,c,d){d||P1c()},listener:()=>O1c()});_.he(_.Mg(),"pagehide",P1c);_.c2c=function(a,b,c){b=_.he(b,"scroll",()=>{X1c(a)});b2c.set(a,b);Y1c.set(a,c);return()=>{var {value:d}=S1c();d=(d.current.sic===$1c?d.last.A8a:d.current.A8a)[a];return d!==void 0?d:null}}("d",document,_.a2c);
_.t("ogmBcd");
var SYr=function(a,b,c,d){a=`${a}s`+d.get("start").toString();c.has("spp")&&(a+="p"+c.get("spp").toString());c.has("ref")&&(a+="-"+c.get("q").toString());return`${b}-${a}`},TYr=function(a,b){const c=["arc_id","next_id","inf","use_ac"];var d="cs deb ei ssi ssb sstk sxsrf".split(" ");let e="";for(const [f,g]of b.entries()){b=f;const h=g;d.indexOf(b)===-1&&(e=`${e}${b}=${h}&`)}e=`${e}async=`;for(const [f,g]of a.entries())a=f,d=g,c.indexOf(a)===-1&&(e=`${e}${a}:${d},`);return e},UYr=function(a){return!!a&&
typeof a.start==="number"&&!isNaN(a.start)&&typeof a.iY==="string"},VYr=function(){const a=[];_.mo((new _.lo([document])).find("[data-dc-hidden]").show().setData("dcHidden",null),b=>{_.rl(b.getData("ved"),"")&&a.push(new _.Nn(b.el(),"show"))});a.length>0&&_.Lv(a)},WYr=function(){return(new _.lo([document])).find("[data-dc-hidden]").size()>0},XYr=class extends _.m{constructor(a){super(a)}},YYr=class extends _.m{constructor(a){super(a)}},ZYr=function(a,b){a.Aa=b},$Yr=function(a,b){a.Ea=b},aZr=function(a,
b){a.Ha=b},bZr=function(a,b){a.QKa=b},cZr={name:"srpp"},dZr=_.Fb(_.CNg,_.DNg),eZr=class{constructor(a,b,c){this.RHb=a;this.eventId=b;this.oa=c}Xfc(a,b){return this.oa?TYr(a,b):SYr(this.RHb,this.eventId,a,b)}Nib(a,b){return this.oa?TYr(a,b):SYr(this.RHb,this.eventId,a,b)}};var fZr=class extends _.m{constructor(a){super(a)}};fZr.prototype.ob="mY34ac";fZr.prototype.Aa=_.Lb([0,_.C]);var gZr=["ssi","ssb"],hZr=new Set(["sei","tch"]),iZr=function(a){a.Ea?(a=a.Aj.oa.elapsedTime()-a.Ea,a=_.oua(a)):a=0;return a},jZr=function(a){a.Aj.lA("btfr",iZr(a));if(a.Ha){var b=a.Aj,c=b.lA;a=a.Aj.oa.elapsedTime()-a.Ha;c.call(b,"ftfr",_.oua(a))}},kZr=function(a){let b=a.requestData.RHb+a.start;a.JPa&&(b+="+"+a.JPa);return b},lZr=function(a,b=""){var c=_.QYr(_.PYr(kZr(a)).setQuery(a.requestData.query),a.requestData.resultType);c.context.set("start",a.start);c.context.set("ve_name","MoreResultsContainer");
c.context.set("use_ac",a.j$a);c=c.build();a.JPa&&!isNaN(a.JPa)&&c.set("spp",a.JPa);a.vHb&&c.set("inf",1);a.Mlb&&c.set("amw",!0);a.pRb&&c.set("ibs",!0);b!==""&&c.set("ictr",b);return c},nZr=function(a,b){const c=mZr(a);b&&(b=google.getLEI(b))&&c.set("lei",b);a.requestData.lGd&&a.requestData.mGd?c.set(a.requestData.lGd,a.requestData.mGd):a.requestData.query&&c.set("q",a.requestData.query);c.set("start",a.start);a.requestData.eGd!=="all"&&c.set("tbm",a.requestData.eGd);if(a.NPa){b=document.body.querySelectorAll("[data-ssb]");
var d;(b=((d=b[b.length-1])==null?void 0:d.getAttribute("data-ssb"))||null)?c.set("ssb",b):c.set("ssb","0")}_.xj(a.tlb,2)&&c.set("sstk",_.A(a.tlb,2)||"");a.Kxb!==""&&c.set("ssi",a.Kxb);a.dnc!==""&&c.set("gsessionid",a.dnc);a.wyb&&c.set("ipage","1");d=new _.yn(a.requestData.Oba);b=_.Gn(d,"ps");b!==void 0&&c.set("ps",b);if(_.Gn(d,"udm")==="49"){d=(d=_.Gn(new _.yn(a.requestData.Oba),"elid"))?dZr(_.Jh(d)):new _.CNg;b=_.Ol("HCMuk");var e=b.length>0?_.Te(b[b.length-1],"continuationToken")||void 0:void 0;
e&&(b=d,e=_.Eca(e),_.gj(b,2,e));d=_.xj(d,1)||_.zj(d,2)?_.Ad((0,_.ENg)(d),4):void 0;d!==void 0&&c.set("elid",d)}a.oRb&&c.set("bsr","1");return c},oZr=function(a,b){var c=0;const d=new Map;if(b)for(const [g,h]of b){b=g;var e=(new Blob([_.qNa.serialize(""+h,b)])).size;gZr.includes(String(b))&&d.set(b,e);c+=e}if(a)for(const [g,h]of a)b=g,e=(new Blob([_.qNa.serialize(""+h,b)])).size,gZr.includes(String(b))&&d.set(b,e),c+=e;d.set("TOTAL",c);if(d==null?0:d.has("TOTAL"))if(c=d.get("TOTAL"),!(c<15360)){b=
0;for(const [g,h]of d)e=h,g!=="TOTAL"&&(b+=e);if(!(c-b>15360))for(const g of gZr){let h;if(((h=a)==null?0:h.has(g))&&d.has(g)){const k=d.get(g);b=a;e=b.set;var f=new fZr;f=_.lh(f,1,k);e.call(b,g,_.Ad(f.Aa(),4));c-=k}if(c<15360)break}}},mZr=function(a){const b=new Map;(new _.yn(a.requestData.ULb)).oa.forEach((c,d)=>{hZr.has(d)||b.set(d,c)});return b},pZr=function(a){return a.oa.state!==4&&a.oa.state!==3&&a.oa.state!==2},qZr=function(a){let b;return(b=a.Ca)==null?void 0:b.promise},rZr=class{constructor(a,
b,c,d,{JPa:e,height:f,xyb:g=!0,lQa:h=!1,eventId:k,vHb:l=!1,Mlb:n=!1,pRb:q=!1,oRb:r=!1,NPa:u=!1,tlb:B,Kxb:G="",sXb:L=!1,gia:N=!1,j$a:T=!0,dnc:Z="",wyb:Y=!1}={}){this.requestData=b;this.start=c;this.iY=d;this.Ma=this.Da=!1;this.logger=null;this.Aj=new _.Eo("infs");this.Aj.start();this.JPa=e;this.height=f;this.Ka=g;this.vHb=l;this.pRb=q;this.oRb=r;this.Mlb=n;this.gia=N;this.NPa=u;this.tlb=B!=null?B:new XYr;this.Kxb=G;this.lQa=h;this.j$a=T;this.xyb=g;c=k||google.kEI;this.dnc=Z;this.wyb=Y;this.Aa=_.CTe(_.DTe(a).kd("arc-"+
kZr(this)),this.iY).build();!isNaN(this.height)&&this.height&&this.height>0&&_.Cm(this.Aa,this.height);this.oa=new _.IYr(()=>this.Aa,{rJa:b.F5d?new eZr(b.RHb,c,L):void 0,lQa:h,q2c:L});this.oa.Ma=!0;_.BYr(this.oa,()=>{this.Ba&&(_.an(this.Ba),this.Ba=null);this.Ca.reject()});_.AYr(this.oa,()=>{isNaN(this.height)||_.Cm(this.Aa,"");this.height=this.Aa.offsetHeight;_.Eq();this.Ba&&(_.an(this.Ba),this.Ba=null);const ea=this.Aa;if(this.Ka){const la=_.Pl("arc-ac",ea);if(la!=null){const oa=window.scrollX,
ha=window.scrollY;la.focus({preventScroll:!0});window.scrollTo(oa,ha)}}this.lQa||jZr(this);this.Aj.lA("btlr",iZr(this));this.Aj.Hc("ei",_.rwc(this.Aa.querySelector("div")));this.Aj.Hc(this.lQa?"ischp":"ischa",this.Da?"1":"0");this.xyb||this.Aj.log();this.Ca.resolve(_.Pl("arc-npt",ea)!=null)});$Yr(this.oa,()=>{this.Da=!0;this.Aj.lA("btch",iZr(this))});bZr(this.oa,()=>{this.Aj.lA("btfb",iZr(this))});ZYr(this.oa,()=>{this.Ma||(this.Ma=!0,jZr(this))});aZr(this.oa,()=>{this.Aj.lA("btlb",iZr(this))})}appendTo(a){a.appendChild(this.Aa)}fetch({trigger:a,
EMa:b=""}={}){this.Da=!1;if(this.oa.state===3&&this.Ca)return this.Ca.promise;this.Ha||(this.Ha=this.Aj.oa.elapsedTime());this.Ca=_.re();b=lZr(this,b);const c=nZr(this,a),d=this.gia;oZr(c,b);_.FYr(this.oa,{Sp:b,urlParams:c,triggerElement:a,gia:d});this.Ka&&(this.Ba=_.Zm(_.Lf(this.Aa).body,"focus",()=>{this.Ka=!1},!0));return this.Ca.promise}reset(){_.CYr(this.oa)}getQuery(){return this.requestData.query}};var sZr=function(){const {metadata:a,url:b}=_.hf();return{key:a?String(a.pushId):b,url:b}},tZr=class{constructor(){this.sessionStorage=_.mf("s",cZr)}};var uZr=function(a,b){b.forEach(c=>{a.WD.forEach((d,e)=>{d.Aa===c&&pZr(d)&&(_.Wy(a.Ba,d.Aa),d.fetch({EMa:a.EMa[e]}).then(void 0,f=>{throw Error("Lx`"+f);}))})})},wZr=function(a){return!vZr(a)||a.oa?!0:a.WD.length>=a.Axb},xZr=function(a,b){if(!a||!b)return b;a=(a=a.Aa)?(a=a.querySelector("div"))?_.Te(a,"stateToken"):null:null;if(a){var c=new XYr;a=_.Sf(c,2,a);b=_.ti(b,1);b=_.Sf(a,1,b)}return b},AZr=function(a,b,c,d,e,f=!1,g,h,k){var l=yZr(a);const n=a.Pmc&&!l&&a.Aa?0:l?l.start+a.fRc:a.u4b;var q=l||
a.u4b!==0?a.Pmc&&!l&&a.Aa?2:void 0:1;l=l?_.ud(_.Pl("arc-npt",l.Aa)):_.ud(a.rbb);return zZr(a,n,l,{JPa:q,xyb:b,vHb:c,pRb:d,oRb:e,NPa:f,tlb:g,Kxb:h,wyb:k})},yZr=function(a){return a.WD.length?a.WD[a.WD.length-1]:null},zZr=function(a,b,c,{JPa:d,XRe:e,xyb:f=!0,vHb:g=!1,pRb:h=!1,oRb:k=!1,NPa:l=!1,tlb:n,Kxb:q="",wyb:r=!1}={}){b=new rZr(a.rbb,a.requestData,b,c,{JPa:d,height:e,xyb:f,lQa:a.ntb,vHb:g,pRb:h,oRb:k,Mlb:a.Mlb,NPa:l,tlb:n,Kxb:q,sXb:a.sXb,gia:a.gia,j$a:a.j$a,dnc:_.rl(_.Xc("yNwwGb"),""),wyb:r});a.WD.push(b);
return b},BZr=function(a){(a=yZr(a))&&!a.Ea&&(a.Ea=a.Aj.oa.elapsedTime())},CZr=function(a){return a.WD.reduce((b,c)=>b+(pZr(c)?0:1),0)},DZr=function(a){return{WD:a.WD.filter(b=>b.JPa!==2).map(b=>({start:b.start,iY:b.iY,height:b.height})),Wne:a.oa,query:a.getQuery()}},vZr=function(a){return a.XXc&&!a.k7b},EZr=function(a,b,c,d,e,f){return new _.Df(g=>{b.WD.forEach(h=>{h=zZr(a,h.start,h.iY,{XRe:h.height,xyb:!1,tlb:f,wyb:d,NPa:e});h.appendTo(c);a.Ba.observe(h.Aa)});a.oa=b.Wne||!1;g()})},FZr=class{constructor(a){this.WD=
[];this.EMa={};this.oa=!1;this.rbb=a.rbb;this.requestData=a.requestData;this.u4b=a.u4b;this.XXc=a.XXc;this.k7b=a.k7b;this.Axb=a.Axb;this.Pmc=a.Pmc;this.Aa=a.eqe;this.ntb=a.ntb;this.Mlb=a.Mlb;this.sXb=a.sXb;this.gia=a.gia;this.j$a=a.j$a===void 0?!0:a.j$a;this.fRc=a.fRc;this.Ba=new _.Xy(_.Vy(b=>uZr(this,b)),{rootMargin:new _.cd(500,0,500,0)},{Bla:!1,Cla:!1})}NKa(a,b,c=!0,d=!1,e=!1,f=!1,g=!1,h=null,k,l="",n=!1){const q=()=>{var u=xZr(r,k);u=AZr(this,c,d,e,f,g,u,l,n);u.appendTo(a);this.oa=!1;return u.fetch({trigger:b,
EMa:this.EMa[this.WD.length-1]}).then(B=>{if(h){const G=xZr(yZr(this),k);G&&_.A(G,2)&&h(G==null?void 0:_.A(G,2))}this.oa=!B;this.Aa=!1})},r=yZr(this);if(r){if(pZr(r))return r.fetch({trigger:b,EMa:this.EMa[this.WD.length-1]});if(r.oa.state!==2){const u=qZr(r);if(u)return u.then(q)}}return q()}getQuery(){return this.requestData.query}};var GZr=function(){let a;return(a=_.hf().metadata)==null?void 0:a.pushId},KZr=function(a){a.oa=a.Ia("EvDH1d");a.Cb&&HZr(a,a.oa.el());const b=_.he(window,"scroll",()=>{IZr(a)}),c=_.he(window,"orientationchange",()=>{a.Aa=JZr(a);IZr(a)}),d=_.he(window,"resize",()=>{a.Aa=JZr(a);IZr(a)});let e;((e=google)==null?0:e.ishk)&&_.lba(google.ishk,b);a.addOnDisposeCallback(()=>{let f;((f=google)==null?0:f.ishk)&&_.za(google.ishk,b);_.an(b);_.an(c);_.an(d)});wZr(a.session)||a.Ha?a.E_.notify("AnqxQb"):a.E_.notify("yFBEId");
_.eK(a.gJ,!wZr(a.session));a.Aa=JZr(a);(0,_.tYr.ROb)().then(f=>a.l2=f);a.Ua&&IZr(a,!0)},HZr=function(a,b,c=!1,d=!1,e=!1,f=!1){LZr(a);if(a.loading)return _.tf();a.E_.notify("Rlvoif");a.loading=!0;const g=()=>{a.loading=!1;_.eK(a.gJ,!wZr(a.session));a.Ta&&VYr()};a.d5a.xKd(6,[]);return a.session.NKa(a.Ba(),b,c,d,e,f,a.NPa,a.rc,_.p(a.E_.data,XYr,70)||void 0,a.d5a.Ora(),a.Ka).then(()=>{a.Aa=JZr(a);a.Na();MZr(a);(0,_.se)(()=>{_.TFg()})}).then(void 0,()=>{a.session.oa||!wZr(a.session)?a.E_.notify("yFBEId"):
a.E_.notify("q8sV4d")}).then(g,g)},NZr=function(a){if(!a.Ea)return!1;a=a.getRoot().closest(_.io("jsname","ibnC6b"));return a.size()===0?!0:a.hasClass("pttBJc")},IZr=function(a,b=!1){document.activeElement!==a.getRoot().el().querySelector('[jsname="oHxHid"]')&&(OZr(a,b)&&(0,_.se)(()=>{HZr(a,a.oa.el(),!1,!0,!!_.z(a.E_.data,65),!!_.z(a.E_.data,86))}),window.scrollY+_.Tl().height>=Math.max(document.body.scrollHeight,document.body.offsetHeight)&&BZr(a.session))},JZr=function(a){const b=CZr(a.session)>
0?28:0,c=_.Tl().height;a:{let e=a.Yb;var d=_.p(a.E_.data,YYr,88);if(d&&(d=_.Bi(d,1,_.ag()),d.length)){a=e=d[Math.min(a.session.WD.length,d.length-1)];break a}switch(_.Tf(a.E_.data,64)){case "0PX":e=0;break;case "100PX":e=100;break;case "200PX":e=200;break;case "300PX":e=300;break;case "350PX":e=350;break;case "500PX":e=500;break;case "700PX":e=700;break;case "ONE_FOLD":e=c;break;case "TWO_FOLDS":e=c*2}switch(_.Tf(a.E_.data,57)){case "0PX":e=0;break;case "100PX":e=100;break;case "200PX":e=200;break;
case "300PX":e=300;break;case "350PX":e=350;break;case "700PX":e=700;break;case "ONE_FOLD":e=c;break;case "TWO_FOLDS":e=c*2}a=e}return(c-b+a)/(window.visualViewport?window.visualViewport.scale:1)},OZr=function(a,b=!1){if(!NZr(a))return!1;let c=!_.nqi();if(_.mqi(_.vS.O2b)||_.mqi(_.vS.xrc))c=!0;_.hf().url.includes("&csui=")&&(c=!1);var d=a.Ba().getBoundingClientRect().bottom;let e=a.Aa!=null&&a.Aa>=d;if(b){var f;b=(f=_.p(a.E_.data,YYr,88))!=null?f:new YYr;f=_.sd(b,2,-1);f>=0&&(e=_.Tl().height+f>=d)}if(d=
!a.loading)d=a.session,d=vZr(d)&&!d.oa&&!(d.WD.length>=d.Axb);d=d&&a.oa!=null;a=a.l2===void 0||!a.l2.t5a();return d&&c&&e&&a&&!WYr()},MZr=function(a){a.session.oa||!wZr(a.session)&&!a.Ha?a.E_.notify("yFBEId"):a.ntb||a.E_.notify("AnqxQb")},LZr=function(a){WYr()&&(a.Ta=!0,VYr())},PZr=async function(a,b,c){return EZr(a.session,b.IYb[0],a.Ba(),a.Ka,a.NPa,c).then(()=>{a.session.oa&&a.E_.notify("yFBEId");var d=a.gJ;for(const e of d.Aa)e();vZr(a.session)&&KZr(a);c&&_.xj(c,2)&&(c==null||_.A(c,2))})},H0=class extends _.Tr{static Sa(){return{service:{d5a:_.jYr,
location:_.cv,ZVb:_.LXr,BKd:_.NXr},model:{E_:_.mYr,gJ:_.tPe}}}constructor(a){super(a.Oa);this.Ea=!0;this.oa=void 0;this.Ha=!1;this.l2=this.Aa=void 0;this.Ta=this.NPa=this.Ua=this.Ka=this.ntb=this.loading=this.Ma=!1;this.rc=()=>{};this.logger=null;this.E_=a.model.E_;this.gJ=a.model.gJ;this.Cc=a.service.location;this.ZVb=a.service.ZVb;this.BKd=a.service.BKd;this.zd=new _.cn(this);this.Xd(this.zd);this.pushId=GZr();const b=this.E_.data;this.query=b.getQuery()||(_.zNg?"unused":"");this.Ka=_.z(b,76);var c=
{query:this.query,lGd:_.Tf(b,51),mGd:_.Tf(b,52),resultType:_.A(b,4)||"full",F5d:_.z(b,12),eGd:_.A(b,17,"all"),RHb:_.A(b,19),ULb:_.Tf(b,23),Oba:this.Cc.location.href};this.Pa=this.Ia("sgxt2d").el();this.Ha=!!_.z(b,71);this.NPa=!!_.z(b,89);c={rbb:this.Pa,requestData:c,u4b:_.sd(b,22,10)<0?_.sd(b,83,10):_.sd(b,22,10),XXc:!!_.z(b,7),k7b:!!_.z(b,82),Axb:_.sd(b,6),Pmc:!!_.z(b,25),eqe:!!_.z(b,24),ntb:!!_.z(b,27),Mlb:!!_.z(b,62),sXb:!!_.z(b,72),gia:!!_.z(b,27),j$a:!1,fRc:_.sd(b,83,10)};this.session=new FZr(c);
this.Cb=_.z(b,30);this.Yb=_.sd(b,5);_.z(b,18)&&(this.Ma=_.oYr());this.Ca=_.z(b,13)&&!this.Ma?new tZr:null;_.eK(this.gJ,!wZr(this.session));c=this.Da();_.KXr(this.ZVb,this);this.Ua=!!_.z(b,79);c||(_.rf("ip","",!0),vZr(this.session)&&KZr(this));this.d5a=a.service.d5a;this.ntb=!!_.z(b,27);let d;(d=_.p(b,XYr,70))==null||_.A(d,2)}Bb(a){HZr(this,a.data.triggerElement.el(),!0,!1,!1,_.z(this.E_.data,86))}Fb(){this.Ea=!1}qc(){this.Ea=!0}wb(){_.eK(this.gJ,!wZr(this.session))}Vb(){_.eK(this.gJ,!0)}Qb(a){if(NZr(this)){var b=
this.session;a=a.data;b.Axb!==a&&(a<b.WD.length?_.Yd(Error("Jx`"+a+"`"+b.WD.length),{level:3}):wZr(b)?b.oa||_.Yd(Error("Kx`"+a),{level:3}):b.Axb=a)}}Rb(a){a=a.data;this.session.EMa[a.DEe-1]=a.EMa}Wa(){this.session.k7b=!1;HZr(this,this.getRoot().el(),!0).then(()=>{vZr(this.session)&&!this.session.oa&&(KZr(this),_.eK(this.gJ,!0))})}Mb(a){a.data.unb==="mosaic"&&(this.oa||KZr(this),HZr(this,this.oa.el(),!1,!0,!!_.z(this.E_.data,65)))}Da(){if(!this.Ca)return null;var a=this.Ca;var b=this.query;const {key:c,
url:d}=sZr();a=a.sessionStorage.get(c)||a.sessionStorage.get(d);var e;if(e=a&&a.IYb&&a.IYb[0])e=a.IYb[0],e=!e||!Array.isArray(e.WD)||e.WD.length<1||e.query!==b?!1:e.WD.every(UYr);return(b=e?a:null)?b:null}Na(){if(this.Ca){_.rf("ip","1",!0);var a=this.Ca,b=this.Va();const c=sZr().key;a.sessionStorage.set(c,b,"h")}}Va(){const a=this.Da();if(!a)return{ei:google.kEI,IYb:[DZr(this.session)]};a.IYb[0]=DZr(this.session);return a}Ba(){return this.Ia("GDPwke").el()}Nb(){return this.Pa}hb(){return this.session}oac(){return"ip"}cWc(){const a=
this.Da();return a?PZr(this,a,_.p(this.E_.data,XYr,70)||void 0):Promise.resolve()}oXc(){const a=(0,_.c2c)();a!==null&&_.qC.fixedUiScrollTo(0,a)}};H0.prototype.$wa$beJeKe=function(){return this.oXc};H0.prototype.$wa$G6z2we=function(){return this.cWc};H0.prototype.$wa$B5e8i=function(){return this.oac};H0.prototype.$wa$gXhQp=function(){return this.hb};H0.prototype.$wa$wCLoc=function(){return this.Nb};H0.prototype.$wa$tB4sIc=function(){return this.Ba};H0.prototype.$wa$kPCoHe=function(){return this.Va};
H0.prototype.$wa$IrXPnf=function(){return this.Na};H0.prototype.$wa$DIGfRe=function(){return this.Da};H0.prototype.$wa$PoQGh=function(){return this.Mb};H0.prototype.$wa$vK2xWc=function(){return this.Wa};H0.prototype.$wa$teMyNc=function(){return this.Rb};H0.prototype.$wa$CYKeQe=function(){return this.Qb};H0.prototype.$wa$p5vRo=function(){return this.Vb};H0.prototype.$wa$VimORe=function(){return this.wb};H0.prototype.$wa$yAlzQb=function(){return this.qc};H0.prototype.$wa$cyaZJ=function(){return this.Fb};
H0.prototype.$wa$XV6jYd=function(){return this.Bb};_.Ie.getInstance().register(_.RYr,H0);




_.v();
_.SDx=_.x("Gg40M",[_.dr]);
_.t("Gg40M");
var TDx=class extends _.Tr{static Sa(){return{service:{Af:_.kw}}}constructor(a){super(a.Oa);this.Af=a.service.Af;const b=document.getElementById("rhs");a=document.getElementById("center_col");b&&a&&(0,_.se)(()=>{const c=new _.oo(b);if(_.hw(this.Af,c).size()>=1){var d=this.Ia("TCyEnb");d=_.WSb(this.Af,d);_.$Sb(this.Af,c,d)}})}Aa(){var a=document.getElementById("center_col");if(a){a=a.getElementsByClassName("WtZO4e");var b=this.Ia("nZDdGd");b.el().getAttribute("tabindex")==="0"&&a.length>0&&_.hw(this.Af,
_.so(a[0])).size()>0&&b.el().setAttribute("tabindex","-1");a=document.getElementsByClassName("TKiced");a.length>0&&_.XSb(this.Af,_.so(a[a.length-1])).focus()}}oa(){var a=document.getElementsByClassName("sW9g3e");if(a.length>0&&a[0]===document.activeElement&&(a=document.getElementsByClassName("WtZO4e"),a.length>0)){const b=document.createElement("div");b.classList.add("TKiced");_.so(a[0]).append(_.so(b))}}};TDx.prototype.$wa$yTpwFc=function(){return this.oa};TDx.prototype.$wa$dNTL7c=function(){return this.Aa};
_.Ie.getInstance().register(_.SDx,TDx);
_.v();
});
// Google Inc.
