loaded_h_0(function(_){var window=this;
var h1D,i1D;h1D=RegExp("tw-data-text|tw-data-placeholder");i1D=class{constructor(){this.oa=!1}};_.j1D=new i1D;
_.k1D=class{constructor(a,b){this.pre=a;this.oa=this.pre.firstElementChild;this.textarea=b||null}Zb(a){_.hm(this.oa,a);this.pre.className=this.pre.className.replace(h1D,"tw-data-text");this.pre.className.indexOf("tw-data-placeholder")>=0||this.oa.innerHTML.length!=0||(_.hm(this.oa,this.sS()),this.pre.className=this.pre.className.replace(h1D,"tw-data-placeholder"));this.textarea&&this.textarea.value!=a&&(this.textarea.value=a)}Wb(){return this.textarea?this.textarea.value:this.pre.className.indexOf("tw-data-text")>=
0?_.vHa(this.oa):""}sS(){return this.pre.getAttribute("data-placeholder")||""}XM(a){this.pre.setAttribute("data-placeholder",a);this.pre.className.indexOf("tw-data-placeholder")>=0&&_.hm(this.oa,a)}};
_.KeC=_.x("KSk4yc",[]);
_.HKr=!!(_.uh[48]>>18&1);_.IKr=!!(_.uh[48]>>19&1);_.JKr=!!(_.uh[48]>>20&1);_.KKr=!!(_.uh[48]>>21&1);_.LKr=!!(_.uh[48]>>22&1);_.MKr=!!(_.uh[48]>>23&1);_.NKr=!!(_.uh[48]>>25&1);_.OKr=!!(_.uh[48]>>26&1);_.PKr=!!(_.uh[48]>>27&1);_.QKr=!!(_.uh[48]>>28&1);_.RKr=!!(_.uh[48]>>29&1);_.SKr=!!(_.uh[49]&1);_.TKr=!!(_.uh[49]&2);_.D0=!!(_.uh[49]&4);_.UKr=!!(_.uh[49]&8);_.VKr=!!(_.uh[49]&16);_.WKr=!!(_.uh[49]&32);_.XKr=!!(_.uh[49]&64);_.YKr=!!(_.uh[49]&128);_.ZKr=!!(_.uh[49]&256);_.$Kr=!!(_.uh[49]&512);
_.aLr=!!(_.uh[49]&1024);_.bLr=!!(_.uh[49]&2048);_.cLr=!!(_.uh[49]&4096);_.dLr=!!(_.uh[49]&8192);_.eLr=!!(_.uh[49]>>14&1);_.fLr=!!(_.uh[49]>>15&1);_.gLr=!!(_.uh[49]>>16&1);_.hLr=!!(_.uh[49]>>17&1);_.iLr=!!(_.uh[49]>>18&1);
var c1c,a1c,b1c;
_.d1c=function(){var a=_.Hh?_.Il("center_col"):_.Il("rcnt");if(a===null)return[];var b=new Set;for(var c of a1c){var d=Array.prototype.slice.call(a.querySelectorAll(c[0]),0);for(var e of d)if(c.length===2&&c[1]==="PARENT")d=e.parentElement,d!==null&&b.add(d);else if(c.length===2&&c[1]==="DESCENDANTS"){if(d=e.childNodes,d!==null)for(var f of d)b.add(f)}else b.add(e)}a=Array.from(b);b=[];for(c=0;c<a.length;c++)if(a[c]instanceof HTMLElement){e=a[c];f=!0;d=e.getBoundingClientRect();if(e.offsetParent===null||
d.width===0||d.height===0)f=!1;if(f)for(d=0;d<a.length;d++)if(c!==d&&_.Nf(a[d],e)){f=!1;break}if(f)for(const g of b1c){if(g.length===2&&g[1]==="ANCESTORS")e.querySelector(g[0])!==null&&(f=!1);else if(g.length===2&&g[1]==="DESCENDANTS")for(d=e.parentElement;d;){if(d.matches(g[0])){f=!1;break}d=d.parentElement}else if(g.length===2&&g[1]==="PARENT"){if(d=e.childNodes,d!==null)for(const h of d)if(h.matches(g[0])){f=!1;break}}else if(e.matches(g[0])){f=!1;break}if(!f)break}f&&b.push(e)}return c1c(b)};
c1c=function(a){const b=[..._.Kl("*")];return a.sort((c,d)=>b.indexOf(c)-b.indexOf(d))};
a1c=[["#rso > div:not(.ULSxyf):not([jsname='TlEBqd']):not(.MjjYud):not(.hlcw0c)[class]"],["#rso div.ULSxyf:not(:only-of-type):not(:last-of-type)"],["#rso div.MjjYud:not(:only-of-type):not(:last-of-type):not(:has(div.grvXqb))"],["#rso div.hlcw0c:not(:only-of-type):not(:last-of-type)"],["#rso div.ULSxyf:not(:only-of-type):last-of-type:not(:nth-of-type(2))"],["#rso div.MjjYud:not(:only-of-type):last-of-type:not(:nth-of-type(2)):not(:has(div.grvXqb))"],["#rso div.hlcw0c:not(:only-of-type):last-of-type:not(:nth-of-type(2))"],
["#bres"],["[jsname='xQjRM']"],[".g-blk"],["[jsname='GDPwke'] div.MjjYud"],[".e6hL7d","DESCENDANTS"],[".kkCXT"],[".cu-container"],["#tvcap"],["#bottomads"],["[jsname='Ypkwb']"],[".yCYahc"]];b1c=[];
_.t("KSk4yc");
var HUE=function(a){return new _.cd(a.top,a.right,a.bottom,a.left)},IUE=function(a){const b=Object.values(a.getClientRects()).filter(c=>c.width>0);if(b.length===0)return HUE(a.range.getBoundingClientRect());a=HUE(b[0]);for(const c of b.slice(1))a.bottom!==c.bottom?a=HUE(c):a.right=c.right;return a},JUE=function(a){const b=Object.values(a.getClientRects()).filter(c=>c.width>0);if(b.length===0)return HUE(a.range.getBoundingClientRect());a=HUE(b[0]);for(const c of b.slice(1)){if(a.top!==c.top)break;
a.right=c.right}return a},KUE=!!(_.uh[66]&128);var LUE=class{constructor(a){this.range=a;const b=[];let c=a.startContainer;for(;c;){a:{var d;try{if(c.nodeType!==3||!_.Bf(c.parentNode)){var e=!1;break a}}catch(f){e=!1;break a}e=c.parentNode;if(d=e.tagName!=="STYLE".toString())d=_.Mg().getComputedStyle(e),d=!(d.getPropertyValue("position")!=="fixed"&&!e.offsetParent)&&d.getPropertyValue("display")!=="none"&&d.getPropertyValue("visibility")!=="hidden"&&d.getPropertyValue("user-select")!=="none"&&d.getPropertyValue("-moz-user-select")!=="none"&&d.getPropertyValue("-ms-user-select")!==
"none"&&d.getPropertyValue("-webkit-user-select")!=="none";e=d}e&&c.nodeValue.trim()&&b.push(c);if(c===a.endContainer)break;c=_.jHa(c)}this.oa=b}toString(){return this.oa.length===0?"":this.oa.map(a=>{let b=0,c=a.nodeValue.length;a===this.range.startContainer&&(b=this.range.startOffset);a===this.range.endContainer&&(c=this.range.endOffset);return a.nodeValue.substring(b,c).trim()}).filter(Boolean).join(" ")}getClientRects(){const a=document.createRange();var b=this.oa[0];const c=b===this.range.startContainer?
this.range.startOffset:0;if(typeof b!=="object")return a.getClientRects();a.setStart(b,c);b=this.oa[this.oa.length-1];a.setEnd(b,b===this.range.endContainer?this.range.endOffset:b.nodeValue.length);return a.getClientRects()}};var NUE=function(a){const b=_.Mg().getSelection();return b&&b.rangeCount!==0&&MUE(a,b)?a.Mb(b.getRangeAt(0)):(a.tooltip.Rd()&&a.oa(),null)},OUE=function(a,b,c){if(a.tooltip!==null&&a.tooltip.kb()!==null){var d=a.tooltip.kb().offsetWidth,e=a.tooltip.kb().offsetHeight,f=_.Mg(),g=IUE(b),h=JUE(b);b=!1;a.Ca&&a.Ca.y+20<g.bottom&&(b=!0);g.bottom+8+a.tooltip.kb().offsetHeight>f.innerHeight&&(b=!0);h.top+8+a.tooltip.kb().offsetHeight<f.innerHeight&&(b=!1);b?e=f.pageYOffset+h.top-8-e:(e=f.pageYOffset+g.bottom+
8,h=g);a.tooltip.setStyle("top",Math.round(e)+"px");g=_.Mg();e=g.innerWidth-16;{f=h.left;var k=h.right,l=a.Ca;h=f+8;const r=k-8;!l||h>=r?f=(f+k)/2:(f=l.x,f=f<h?h:f>r?r:f)}h=f;f=h-d/2;f<16?f=Math.min(16,h-12):f+d>e&&(f=Math.max(e-d,h+12-d));d=h-f;f+=g.pageXOffset;var {uUe:n,T3d:q}={uUe:f,T3d:d};c||a.tooltip.setStyle("left",Math.round(n)+"px");d=b;c=c?null:Math.round(q-6);a.Ka.isEmpty()||a.Ha.isEmpty()||(g=d?a.Ha:a.Ka,d=d?a.Ka:a.Ha,c&&g.setStyle("left",c+"px"),g.show(),d.hide());a.tooltip.setStyle("transform-origin",
q+"px "+(b?"bottom":"top"));a.Aa=null}},PUE=function(a){const b=a.Ya("YljVCc");(b.Rd()?_.po(b,'[role="button"], button, a'):_.po(a.Ya("ZmkZfc"),'[role="button"], button, a')).focus()},QUE=function(a,b){if(a.split(" ").length===1){var c=_.Mg().getSelection();if(c&&c.anchorNode&&c.focusNode&&c.anchorNode===c.focusNode){var d=c.anchorNode;a=null;d.textContent&&(b.set("ctif",d.textContent),(d=d.parentElement)&&d.textContent&&(b.set("ctif",d.textContent),a=d,(d.tagName==="B"||d.tagName==="EM")&&(d=d.parentElement)&&
d.textContent&&(b.set("ctif",d.textContent),a=d)));a!==null&&c.rangeCount>0?(c=c.getRangeAt(0),d=c.cloneRange(),d.selectNodeContents(a),d.setEnd(c.startContainer,c.startOffset),a=d.toString().length,d.setEnd(c.endContainer,c.endOffset),c=d.toString().length,b.set("slst",a),b.set("sled",c)):isNaN(c.anchorOffset)||isNaN(c.focusOffset)||(a=Math.max(c.anchorOffset,c.focusOffset),b.set("slst",Math.min(c.anchorOffset,c.focusOffset)),b.set("sled",a))}}},TUE=function(a,b){if(a.Da){a.Da=!1;var c=NUE(a),d=
c?c.toString().slice(0,a.Cb).trim():null;a.Ia("Uo0pef").toggle(b);d&&(a.Ta===-1||d.split(" ").length<=a.Ta)?RUE(a,()=>SUE(a,c,d)):a.tooltip.Rd()&&a.oa()}},UUE=function(a,b,c){if(!b||c.has(b))return!1;c.add(b);if(!a.hb&&b.tagName==="A".toString()||_.gIa(b)==="button"||b===a.Fb||b.id==="tw-container")return!0;const d=_.IHa(b,"zIndex");return d&&d.toString()!=="auto"&&d.toString()!=="0"||(_.NKr||KUE)&&b.getAttribute("jsname")==="dvXlsc"?!0:UUE(a,_.zf(b),c)},MUE=function(a,b){const c=new Set;b=b.getRangeAt(0);
let d=b.startContainer;for(;d;){try{if(d.nodeType!==3&&d.nodeType!==1)return!1}catch(e){return!1}if(d.parentElement&&UUE(a,d.parentElement,c))return!1;if(d===b.endContainer)break;d=_.jHa(d)}return!0},RUE=function(a,b){a.Aa&&((0,_.Un)(a.Aa),a.Aa=null);a.Aa=(0,_.Tn)(b,a.wb)},SUE=function(a,b,c){if(a.Ba!==null&&a.Ba.el()!==null){var d=new Map;d.set("rt","tc");d.set("sltx",c);QUE(c,d);_.Hy(a.Ba.el(),{context:d}).then(e=>{a.showTooltip(e,b);(0,_.Tn)(()=>_.Eq(),200)})}},VUE=class extends _.Tr{constructor(a){super(a.Oa);
this.Ul=[];this.Na=this.Pa=this.Da=!1;this.Ca=null;this.Ma=!1;this.Aa=null;this.Ea=!1;this.tooltip=this.Ya("suEOdc");this.tooltip.isEmpty()&&_.emb(this,"suEOdc").then(b=>this.tooltip=b);this.Ka=this.Ya("ojBOCb");this.Ha=this.Ya("GV5nwf");this.Ba=this.Ya("V4zgDf");this.Ba.isEmpty()&&_.emb(this,"V4zgDf").then(b=>this.Ba=b);this.Cb=_.Yc(this.getData("mcl"),0);this.Ta=_.Yc(this.getData("mwl"),-1);this.wb=_.Yc(this.getData("dl"),0);this.Fb=_.Il("result-stats");this.Mb=b=>new LUE(b);this.Bb=this.getData("cf").Lb();
this.hb=this.getData("ath").Lb();a=_.Mg();this.Ul.push(_.he(a,"mousedown",b=>{this.onMouseDown(b)},!1,this));this.Ul.push(_.he(a,"keydown",b=>{this.onKeyDown(b)},!1,this));this.Ul.push(_.he(a,"mouseup",b=>{this.onMouseUp(b)},!1,this));this.Ul.push(_.he(a,"keyup",()=>{this.onKeyUp()},!1,this));this.Ul.push(_.he(document,"selectionchange",()=>{this.bOa()},!1,this))}Ub(){this.Ul.forEach(a=>a&&_.an(a));this.Ul.length=0}Ua(){this.Ya("neDtlb").isEmpty()||(this.Ya("ZmkZfc").hide(),this.oa())}Nb(a){const b=
this.Ya("ZmkZfc");if(!b.isEmpty()&&!b.Rd()&&this.tooltip!==null){b.show();this.tooltip.addClass("lSNMte");this.Ya("YljVCc").hide();var c=NUE(this);c&&OUE(this,c,!0);PUE(this);this.Ea=!1;a=a.targetElement.el();_.Lv([new _.Nn(b.el(),"show")],{triggerElement:a})}}Wa(a){if(a.data.Aa()==="context_actions_dictionary"||a.data.Aa()==="context_actions_translate")this.Na=!0}Va(){this.Na=!1}onMouseDown(a){this.Pa=a=_.Nf(this.tooltip.el(),a.target);!a&&this.tooltip.Rd()&&this.oa()}onKeyDown(a){a.keyCode===27&&
(this.Ma=!0,this.oa());var b;if(b=a.shiftKey)b=a.keyCode,b=b===38||b===40||b===37||b===39;b&&(this.Ma=!1,this.oa());a.ctrlKey&&a.shiftKey&&a.key==="X"&&this.tooltip.Rd()&&PUE(this)}onMouseUp(a){const b=_.Nf(this.tooltip.el(),a.target);this.Pa=b;b||(this.Ca=a.clientX&&a.clientY?new _.Dl(a.clientX,a.clientY):null,TUE(this,!1))}onKeyUp(){const a=!this.tooltip.Rd()&&!this.Aa;!this.Ma&&a&&(this.Ca=null,TUE(this,!0))}bOa(){this.Da=!0;(_.Mg().getSelection()||"").toString()===""&&!this.Pa&&this.tooltip.Rd()&&
(this.oa(),this.Da=!1)}showTooltip(a,b){a&&!this.Ya("YljVCc").isEmpty()&&this.tooltip!==null&&this.tooltip.el()!==null&&(this.Bb||this.tooltip===null||(this.tooltip.show(),OUE(this,b,!1),this.tooltip.setStyle("opacity",.999),this.tooltip.setStyle("transform","scale(1)")),this.Ea||(_.Lv([new _.Nn(this.tooltip.el(),"show")],{}),this.Ea=!0))}oa(){this.tooltip!==null&&this.Ba!==null&&this.Ba.el()!==null&&this.Na!==!0&&(this.Aa&&((0,_.Un)(this.Aa),this.Aa=null),this.tooltip.setStyle("top",0),this.tooltip.setStyle("left",
0),this.tooltip.hide(),this.tooltip.setStyle("opacity",.001),this.tooltip.setStyle("transform","scale(0.1)"),this.tooltip.removeClass("lSNMte"),_.Jy(this.Ba.el()),this.Ea=!1)}};VUE.prototype.$wa$VvZoSb=function(){return this.Va};VUE.prototype.$wa$MlP2je=function(){return this.Wa};VUE.prototype.$wa$v9xSwd=function(){return this.Nb};VUE.prototype.$wa$Geh74d=function(){return this.Ua};VUE.prototype.$wa$k4Iseb=function(){return this.Ub};_.Ie.getInstance().register(_.KeC,VUE);

_.v();
_.ZEr=_.x("O9SqHb",[_.Tq,_.H6a]);
_.AEr=!!(_.uh[85]&8192);_.BEr=!!(_.uh[85]>>14&1);_.CEr=!!(_.uh[85]>>15&1);_.DEr=!!(_.uh[85]>>16&1);_.EEr=!!(_.uh[85]>>17&1);_.FEr=!!(_.uh[85]>>18&1);
_.t("O9SqHb");
var $Er=class extends _.Tr{static Sa(){return{service:{kc:_.Sz,yz:_.H5c}}}constructor(a){super(a.Oa);this.kc=a.service.kc;_.CEr&&(this.yz=a.service.yz)}async navigate(a){try{const b=!!a&&a.data||{},c=b.url,d=b.kEc;if(this.yz&&!d)try{this.trigger("JCifrc");_.y(await _.y(this.yz.transition(c.toString())));return}catch(e){_.y(),_.Yd(Error("hx`"+e))}this.kc.navigateTo(c,!1)}finally{_.y()}}};$Er.prototype.$wa$RySO6d=function(){return this.navigate};_.Ie.getInstance().register(_.ZEr,$Er);
_.v();
});
// Google Inc.
