_F_installCss(".mWcf0e{cursor:pointer}@media (forced-colors:active){.CNbPnc{background-color:ButtonFace;border:1px solid transparent;border-color:ButtonBorder;color:ButtonText}}.VfL2Y{position:relative;}.YQpX9d{cursor:pointer;position:relative;}.LRZwuc{display:inline-block}.BJ1Ird .LRZwuc{display:block}.nKHyTc{color:var(--IXoxUe);float:right;font-size:12px;line-height:16px;padding-bottom:4px}.eDGqNd{color:var(--IXoxUe);float:right;font-size:12px;line-height:16px}.k62gjb:hover,.k62gjb .W7GCoc:hover,.BJ1Ird{text-decoration:underline}sentinel{}");
loaded_h_0(function(_){var window=this;
_.MB=function(a,b){return _.Jg(a,2,b)};_.NB=function(a,b){return _.lh(a,14,b)};_.jUc=[0,_.C,-1,_.E,_.D,_.E,_.D,_.E,_.D];
var STc=[0,4,_.Nj,_.C,-3];_.TTc=[0,_.F,[0,STc,_.F,[0,STc,_.F,[0,_.E,STc,_.C]]],_.C,-1,[0,_.F,[0,_.E,_.Nj]],1,_.Nj];_.UTc=[0,[3,4],2,_.wk,[0,_.xk,_.Nj],_.wk,[0,_.F,_.RTc,_.Nj],[0,[1,2],_.wk,[0,_.Nj,-4,_.H],_.qk],-1,_.RTc];
_.OTc=[-5,{},_.H,_.Lj,_.D,_.H];
_.QTc=[0,_.F,_.OTc,[0,_.F,[0,_.H,_.Nj]],[0,_.H],_.D,[0,_.C,-2,_.Nj,1,_.E,-2],[0,[0,_.Nj,_.Ik,_.D]]];
_.PTc=[0,_.Qj,[0,_.F,[0,_.ik,_.Rj]],_.xk,_.Qj,-1];
var $Tc=[0,_.D];var aUc=[0,_.Nj,-3];_.bUc=[0,_.F,[0,_.H,1,_.H],_.F,[0,_.H,-1],_.H];var cUc=[0,_.H];var dUc=[0,_.Qj];_.eUc=[0,_.Uj,_.vk,[0,2,_.C,_.F,[0,_.Nj,-4,_.xk,_.Nj,dUc,[0,_.Nj,-3],_.xk],_.C,_.D],13,_.E,-1,_.C,-1,_.rk,1,_.xk,[0,_.C,-3],[0,_.Lj,-1,1,_.Lj,-1,_.D,_.Lj,_.E],_.xk,_.E,-1,_.F,[0,[3,4],_.E,-1,_.wk,dUc,_.wk,[0,_.Nj,_.xk],_.xk]];_.fUc=[0,_.PTc,_.eUc];_.gUc=[0,[0,_.F,[0,_.mk,_.Nj,_.nk,[0,_.Rj]]],_.WAb];var hUc=[0,_.mk,_.H,[0,[0,_.E,_.D,_.Nj,$Tc,_.C,_.E],_.F,[0,_.E,$Tc],_.F,[0,_.E,-1,_.H,$Tc,_.E,-1,_.D,[0,_.Ik],_.Nj,_.E,-2,_.D],_.F,[0,_.E,1,_.H,$Tc,_.Lj,_.D,_.Nj,_.D],_.F,[0,_.mk,_.E,-1,2,$Tc,_.D,_.mk,_.F,_.OTc,_.H],1,_.bUc,_.D,_.F,[0,_.E,_.Nj],_.D,_.QTc,_.gUc,4,_.D,cUc,_.F,[0,_.E,_.H],_.D,_.fUc,-1,_.D,-1],aUc,_.ek,_.E,_.F,[0,_.H,_.Qj,_.hk,1,_.xk],_.TTc,aUc,[0],4,[0,_.hk,_.H],_.UTc];_.iUc=[0,1,_.D,1,_.F,hUc,hUc,1,_.D,_.ZTc,_.H,_.WTc,1,[0,_.D],cUc,1,[0,_.D,_.E,_.D,_.C,_.E,-1,_.D,-2],[0,_.D],[0,_.H],[0,_.D],_.D,-2,1,_.D];
_.NTc={};
_.LTc=[0,3,_.hk,_.H,_.C];
var kUc=[0,_.H,_.F,[0,_.E,[0,_.E,-3],_.D,[0,_.H,_.C,_.E,-1,[0,_.E,-2,_.Nj,_.E,[0,_.ck]]],[0,_.E,-1,_.ck,_.C,-1,_.F,[0,_.E,-1,[0,_.C,-3],_.E,-2],_.E,-1],[0,_.C,-1,_.E,-1]]],lUc=[0,_.E,-3,_.H,1,_.H,[0,_.C,-1],_.ll,_.E,-1,[-11,{},_.E,-2,_.H,_.E,_.D,-1,_.E,[0,_.D,_.Lj,_.C],[0,_.D,3,_.ll]],_.D,_.rk,_.F,kUc,_.D,-1,[0,_.E,-2],_.C,_.H,_.D,_.E,[0,_.rk,_.hk,_.F,[0,_.E,_.hk]],_.H,_.D,-1,[0,_.H],_.C,[0,_.Nj,-1,1,_.E],[0,1,_.Nj,_.H,[0,_.mk,_.H,-1,[0,_.H,_.C],_.Nj,[0,_.E]],_.mk],[0,_.Ik,_.H],_.E,-1,_.D];var mUc=[0,_.ssb];var nUc=[0,_.F,[0,_.E,_.Gs,_.D,_.Gs,-1],_.F,mUc,_.F,[0,_.ssb],_.C,-1,_.F,[0,_.ssb],_.F,[0,_.ssb],_.F,[0,_.ssb],_.F,mUc];var oUc=[0,_.Gs,_.F,[0,_.C,-1],_.E,_.Gs,_.F,_.Gs];var pUc=[0,_.E,_.Gs];_.qUc=[2,4,6];_.rUc=function(a,b){return _.Sf(a,2,b)};_.sUc=function(a,b){return _.Sf(a,3,b)};_.tUc=class extends _.m{constructor(a){super(a)}getImageUrl(){return _.A(this,2)}Hn(){return _.xj(this,2)}Aa(){return _.ti(this,2)}};_.uUc=function(a){return _.Fj(a,8)};_.OB=class extends _.m{constructor(a){super(a,40)}Dfa(){return _.sd(this,16)}Uc(){return _.A(this,20)}qca(){return _.A(this,30)}};var vUc=[0,_.C,-3,_.E];var wUc=[0,_.xk,1,vUc];var xUc=[0,_.E,vUc];var BUc=[0,_.E,vUc,xUc,()=>yUc,_.F,()=>zUc,_.F,()=>AUc,_.D],DUc=[0,()=>yUc,_.F,()=>CUc,()=>yUc,vUc,()=>yUc,3,_.F,()=>AUc],EUc=[0,_.E,vUc,6,_.F,()=>AUc],GUc=[0,_.E,_.F,()=>zUc,()=>FUc,_.F,()=>AUc,vUc,xUc,_.E],yUc=[-11,{},[1,2,3,4,5,6,7,9,10],_.wk,()=>FUc,_.wk,()=>GUc,_.wk,()=>EUc,_.wk,()=>HUc,_.wk,()=>DUc,_.wk,[0,_.E,vUc,_.H],_.wk,()=>BUc,1,_.wk,[0,_.F,wUc,_.H],_.wk,wUc],CUc=[0,[1,2],_.wk,()=>yUc,_.wk,[0,_.C,-1,vUc],()=>yUc],IUc=[0,()=>yUc,_.F,()=>CUc],FUc=[0,_.D,-2,_.F,()=>yUc,vUc,xUc,()=>IUc,1,_.F,
()=>AUc,_.D],JUc=[0,_.F,()=>HUc],HUc=[0,[1,2,3,4,5,6,13,14,15,16,17,18,19],_.wk,()=>GUc,_.kk,_.Sj,_.Mj,_.qk,_.tk,6,_.wk,()=>JUc,_.qk,_.wk,()=>FUc,_.qk,_.tk,_.Zj,_.qk,vUc],zUc=[0,_.E,()=>HUc],AUc=[0,_.E,_.F,()=>zUc,vUc];var KUc=[0,[1],_.wk,[0,_.E,_.rk,_.E,[0,_.E,1,_.F,[0,_.E,[0,_.E,-3,_.F,[0,_.ck],_.E],_.D,_.C],_.F,yUc,_.H,-5,17,_.H],_.rk]];var LUc=[0,_.F,[0,_.E,_.H,[0,_.E,_.rk,-1],_.F,[0,_.E,-1],_.E,_.F,KUc],_.E,[0,_.C,_.E,-2,_.rk],_.F,KUc];var MUc=[0,_.rk,-2,_.F,[0,_.E,-2,_.D,_.C,_.E,-3],_.rk,_.D];var NUc=[0,_.E,-1,_.rk,_.E,_.F,[0,_.E]];var OUc=[0,_.E,_.Ik,_.E,_.Ik,-1,_.F,[0,_.E,_.H],_.C,_.F,[0,_.F,LUc],_.F,LUc,_.F,[0,_.E,_.H],_.E,[0,_.F,lUc,1,_.F,[0,_.H,_.E],[-23,_.NTc,_.E,_.D,_.E,-3,_.F,[0,_.E,_.H],1,_.D,_.iUc,_.D,_.E,-1,_.D,[0,_.E,-2],_.H,_.F,[0,_.E,-1],[0,_.E,_.D],_.E,-1,_.H,_.E],_.F,kUc,_.Ik,_.F,lUc,[0,_.F,[0,_.E,_.hk,_.E]],[0,_.F,[0,_.E,_.xk,_.LTc]],_.F,lUc,_.F,[0,_.E,_.Nj,-1,_.H,_.Nj],_.F,[0,_.E,_.C]],_.H,_.rk,_.H,[0,_.E,-2,_.C,_.D],_.rk,_.H,_.D,_.rk,-1,[0,_.F,NUc,NUc,_.F,[0,_.E],_.F,[0,_.E,_.F,NUc],_.F,NUc],_.E,_.F,[0,1,
_.H,_.E,-2,_.C,-1],_.rk,_.H,_.xk,_.C,[0,_.E,_.C,-1],_.D,-1,_.C,_.E,_.F,MUc,MUc,[0,_.E,-1],_.E,_.D];_.PUc=[0,_.E,-4,32,_.C,-1,_.E];_.QUc=[-40,{},_.PUc,[0,[0,[0,_.E,_.D,_.H,_.rk,_.H,_.E,_.C,_.Nj,-3,_.E,_.Ck,_.C,_.F,[0,_.E,-1],_.D,_.E,_.D,_.H,-2,_.Ck,_.Fk,_.H,_.Ck,_.E,_.ak,_.D,_.jUc,_.E,-2,_.H,_.Lj,_.lk,_.D,-1,_.E,[0,_.F,[0,_.E,_.mk],_.H,_.C],_.H,_.D,-1,_.C,_.E,-1,_.ck,-1,_.E,-4,_.Nj,_.Uj,_.Nj,_.D,-1],[0,_.H,-1]],_.mk,_.nk],[0,_.H,-3,LUc],OUc,LUc,2,_.Jj,_.Lk,_.rk,-1,[0,_.E,-3,_.F,[0,_.C,_.E,-1,_.H,_.F,[0,_.E,-1,_.H,_.D]],_.C],_.F,[0,_.E,_.H,_.D,_.E],_.F,[0,_.E,-1,_.H,-2],_.F,[0,_.qUc,_.E,_.wk,[0,_.C,-3],_.D,_.wk,[0,_.H],_.E,_.wk,
[0,_.E,-1]],[0,_.E,-1,[0,_.E,_.C,_.E,_.H,[0,_.F,[0,_.E,_.C,_.E],_.F,[0,_.E,-1,_.C]]]],_.C,_.E,_.Ik,_.E,-2,[0,_.E,-1,_.D,-1],[0,[9],_.E,-1,[0,_.E,_.F,[0,_.H,_.E,-2,_.C,_.E,-1],_.rk,-1],3,_.H,-1,_.wk,[0,_.is,oUc,1,nUc,_.F,pUc,[0,_.E,_.Gs,_.E,_.Uj],[0,_.E,_.ml],_.ll,[0,_.Nj],[0,_.E],_.ck,_.F,[0,oUc,nUc,_.F,pUc]],_.E,_.H,_.is],[0,[0,_.H,_.C,_.F,[0,_.Ik,_.E,-1],_.F,[0,_.Ik,_.E,-1],_.E,-2,_.C,-1,_.H,_.E,-3,_.D,_.E,-1,1,_.E,_.H,_.E,_.H,_.E,-1,_.H,_.E,_.D,_.E,-1,_.H,_.E,_.H,_.D,_.H]],_.F,[0,_.E,-2,[0,_.F,
[0,_.E,-1]],_.gk],[0,_.F,_.XAb],[0,_.E,-3,_.D,_.C,_.E,_.D,_.E,-1,_.C,-1,_.E,-1,_.C,-1,_.D,-4,_.E,-4],[0,_.E,-1,_.D,_.H],[0,[0,_.E,_.H,_.E],_.H,-1,_.E,_.F,[0,_.E,_.Nj],_.vn],_.E,_.D,-1,[0,_.E,_.H,_.C,-1],[-2,{},_.E],_.E,[0,OUc,-1,_.D,-1,_.E,_.C],[0,_.E,-2,_.rk,_.E,-1,_.rk,-1,1,_.E,_.D,_.E,_.D,_.E,-2,_.D,_.E,_.D],[0,_.H,_.is],[0,_.E]];_.OB.prototype.Aa=_.Lb(_.QUc);
_.pWc=function(a,b,c){return _.MTc(a,8,b,c)};
_.t("SMquOb");

_.v();
_.zWc=_.x("d5EhJe",[]);
_.qWc=function(a){return _.ti(a,9)};_.rWc=function(a,b){return _.Hg(a,20,b)};
_.aC=class extends _.m{constructor(a){super(a)}Fb(){return _.Wi(this,1)}Fm(){return _.Nd(this,1)}IH(){return _.Aj(this,1)}getAttribute(){return _.Tf(this,2)}setAttribute(a){return _.Sf(this,2,a)}Lf(){return _.Nd(this,2)}hasAttribute(){return _.xj(this,2)}Wa(){return _.Tf(this,14)}Ma(a){return _.Sf(this,14,a)}Fn(){return _.Nd(this,14)}RI(){return _.xj(this,14)}hb(){return _.Tf(this,3)}Pa(a){return _.Sf(this,3,a)}pv(){return _.Nd(this,3)}UI(){return _.xj(this,3)}Va(){return _.Tf(this,4)}Ta(a){return _.Sf(this,
4,a)}zp(){return _.Nd(this,4)}vd(){return _.xj(this,4)}qc(){return _.Tf(this,5)}Fe(a){return _.Sf(this,5,a)}Qo(){return _.Nd(this,5)}Nc(){return _.xj(this,5)}wg(){return _.Tf(this,15)}Fg(a){return _.Sf(this,15,a)}iN(){return _.Nd(this,15)}dX(){return _.xj(this,15)}Rb(){return _.Tf(this,6)}Qv(a){return _.Sf(this,6,a)}TY(){return _.Nd(this,6)}xc(){return _.xj(this,6)}Vb(){return _.Tf(this,7)}Pd(a){return _.Sf(this,7,a)}jk(){return _.Nd(this,7)}Kc(){return _.xj(this,7)}rc(){return _.Si(this,12)}uf(a){return _.lh(this,
12,a)}Yo(){return _.Nd(this,12)}Dd(){return _.nd(this,12)}Yb(){return _.Tf(this,8)}Ld(a){return _.Sf(this,8,a)}Bk(){return _.Nd(this,8)}Lc(){return _.xj(this,8)}qca(){return _.Tf(this,9)}Da(a){return _.Sf(this,9,a)}Wl(){return _.Nd(this,9)}wb(){return _.xj(this,9)}mB(){return _.Tf(this,10)}Ba(a){return _.Sf(this,10,a)}Ng(){return _.Nd(this,10)}tx(){return _.xj(this,10)}oF(){return _.Tf(this,11)}Ca(a){return _.Sf(this,11,a)}Gi(){return _.Nd(this,11)}lC(){return _.xj(this,11)}Na(){return _.Si(this,
13)}Aa(a){return _.lh(this,13,a)}Ai(){return _.Nd(this,13)}ZC(){return _.nd(this,13)}Qb(){return _.Ri(this,16)}Gd(a){return _.Jg(this,16,a)}Mk(){return _.Nd(this,16)}eF(){return _.qj(this,16)}Az(){return _.Ri(this,17)}wd(a){return _.Jg(this,17,a)}Vha(){return _.Nd(this,17)}yD(){return _.qj(this,17)}Ha(){return _.p(this,_.OB,19)}Ka(a){return _.Bb(this,_.OB,19,a)}WI(){return _.Nd(this,19)}zD(){return _.Oh(this,_.OB,19)}RT(){return _.Tf(this,21)}Ua(a){return _.Sf(this,21,a)}vK(){return _.Nd(this,21)}fF(){return _.xj(this,
21)}nS(){return _.Wi(this,20)}Kh(){return _.Nd(this,20)}Jc(){return _.Aj(this,20)}getViewerType(){return _.Wi(this,22)}Kp(a){return _.Hg(this,22,a)}Ap(){return _.Nd(this,22)}TI(){return _.Aj(this,22)}Qq(){return _.Si(this,23)}Cb(a){return _.lh(this,23,a)}Zk(){return _.Nd(this,23)}HH(){return _.nd(this,23)}Mb(){return _.Tf(this,24)}Bb(a){return _.Sf(this,24,a)}Mf(){return _.Nd(this,24)}Hu(){return _.xj(this,24)}bB(){return _.Tf(this,25)}Re(a){return _.Sf(this,25,a)}Ym(){return _.Nd(this,25)}Np(){return _.xj(this,
25)}};_.aC.prototype.ob="zEIyGd";
var tWc,uWc,wWc;_.sWc=function(a,b){return _.Hg(a,1,b)};tWc=_.Fb(_.OB,_.QUc);uWc=function(a){return _.Ad(a.Aa(),4)};_.vWc=function(a){try{if(a)return tWc(_.Jh(a))}catch(b){}return new _.OB};
wWc={Mt(){return"kpfb-stage kpfb-attr kpfb-tattr kpfb-ve kpfb-rval kpfb-rentity kpfb-secids kpfb-docid kpfb-lpage kpfb-tsourceid kpfb-lyricid kpfb-kpid kpfb-entityid kpfb-entityname kpfb-ftype kfig kfhi kpfb-ctx kpfb-ectx kpfb-ftag kpfb-vt kpfb-pid kpfb-bkt kpfb-rectx".split(" ")},Ik(a,b){a=new _.Kv(a.oa,b);_.Fv(a,"kpfb-stage",c=>_.sWc(b,c),b.Fm);_.Ev(a,"kpfb-attr",b.setAttribute,b.Lf);_.Ev(a,"kpfb-tattr",b.Ma,b.Fn);_.Ev(a,"kpfb-ve",b.Pa,b.pv);_.Ev(a,"kpfb-rval",b.Ta,b.zp);_.Ev(a,"kpfb-rentity",b.Fe,
b.Qo);_.Ev(a,"kpfb-secids",b.Fg,b.iN);_.Ev(a,"kpfb-docid",b.Qv,b.TY);_.Ev(a,"kpfb-lpage",b.Pd,b.jk);_.Fv(a,"kpfb-tsourceid",b.uf,b.Yo);_.Ev(a,"kpfb-lyricid",b.Ld,b.Bk);_.Ev(a,"kpfb-kpid",b.Da,b.Wl);_.Ev(a,"kpfb-entityid",b.Ba,b.Ng);_.Ev(a,"kpfb-entityname",b.Ca,b.Gi);_.Fv(a,"kpfb-ftype",b.Aa,b.Ai);_.Gv(a,"kfig",b.Gd,b.Mk);_.Gv(a,"kfhi",b.wd,b.Vha);_.Dv(a,"kpfb-ctx",b.Ka,_.vWc,b.WI);_.Ev(a,"kpfb-ectx",b.Ua,b.vK);_.Fv(a,"kpfb-ftag",c=>_.rWc(b,c),b.Kh);_.Fv(a,"kpfb-vt",c=>b.Kp(c),b.Ap);_.Fv(a,"kpfb-pid",
b.Cb,b.Zk);_.Ev(a,"kpfb-bkt",b.Bb,b.Mf);_.Ev(a,"kpfb-rectx",b.Re,b.Ym)},Vk(a,b){b=new _.Kv(b.oa,a);_.Iv(b,a.IH,a.Fb,"kpfb-stage");_.Hv(b,a.hasAttribute,a.getAttribute,"kpfb-attr");_.Hv(b,a.RI,a.Wa,"kpfb-tattr");_.Hv(b,a.UI,a.hb,"kpfb-ve");_.Hv(b,a.vd,a.Va,"kpfb-rval");_.Hv(b,a.Nc,a.qc,"kpfb-rentity");_.Hv(b,a.dX,a.wg,"kpfb-secids");_.Hv(b,a.xc,a.Rb,"kpfb-docid");_.Hv(b,a.Kc,a.Vb,"kpfb-lpage");_.Iv(b,a.Dd,a.rc,"kpfb-tsourceid");_.Hv(b,a.Lc,a.Yb,"kpfb-lyricid");_.Hv(b,a.wb,a.qca,"kpfb-kpid");_.Hv(b,
a.tx,a.mB,"kpfb-entityid");_.Hv(b,a.lC,a.oF,"kpfb-entityname");_.Iv(b,a.ZC,a.Na,"kpfb-ftype");_.Jv(b,a.eF,a.Qb,"kfig");_.Jv(b,a.yD,a.Az,"kfhi");_.FOb(b,a.zD,a.Ha,uWc,"kpfb-ctx");_.Hv(b,a.fF,a.RT,"kpfb-ectx");_.Iv(b,a.Jc,a.nS,"kpfb-ftag");_.Iv(b,a.TI,a.getViewerType,"kpfb-vt");_.Iv(b,a.HH,a.Qq,"kpfb-pid");_.Hv(b,a.Hu,a.Mb,"kpfb-bkt");_.Hv(b,a.Np,a.bB,"kpfb-rectx")}};var xWc;xWc=null;_.yWc=class extends _.tw{constructor(a,b){super(a);new _.zw(this);this.Rn=_.rw(b,this,new _.qw(wWc))}static Cm(){return _.aC}static Nm(a){return xWc?xWc:xWc=_.pw().then(b=>{b=new _.yWc(_.aC,b);b.initialize(a);return b})}};_.To.zEIyGd=_.So;
_.t("d5EhJe");
var AWc;AWc=async function(a,b,c,d=!0){try{if(b){const e=_.y(await _.y(b));e.GRb(4)&&(d?_.y(await _.y(e.nsa())):_.y(await _.y(e.NHc())))}c&&a.getState()!==c&&a.Vh(c,!1,!0)}finally{_.y()}};
_.BWc=class extends _.ih{static Sa(){return{oe:{state:_.yWc}}}constructor(a){super();this.oa=[];this.kba=void 0;this.ij=a.oe.state;this.ij.listen((b,c,d)=>{if(c==="IaLTGb")if(d.reason===1)this.oa.pop();else{this.oa.push({});this.Vh(b,!1,!0);return}this.notify("iiAWKb",b)});this.Ha=this.ij.transition((b,c)=>{const d=c.newState;c.Dve&&d.Da(_.qWc(b));return d})}Aa(){this.notify("iiAWKb",this.ij.get())}getState(){return this.ij.get()}Vh(a,b=!0,c=!1){a=_.HTb({newState:a,Dve:b});c&&(a=a.and(_.Zy,{replace:!0}));
a=this.Ha.run(a);c||this.oa.push(a)}goBack(a){AWc(this,this.oa.pop(),a).then()}Ea(){this.oa.length>0?this.goBack():this.reset()}Da(a){this.kba=a}Ba(){return this.kba}reset(){this.oa.length>0&&AWc(this,this.oa[0],new _.aC,!0).then();this.oa=[];this.Vh(new _.aC,!1,!0);this.kba=void 0}};_.Gr(_.zWc,_.BWc);
_.v();
_.DZc={erc:["BC","AD"],B5c:["Before Christ","Anno Domini"],g7c:"JFMAMJJASOND".split(""),J7c:"JFMAMJJASOND".split(""),KGb:"January February March April May June July August September October November December".split(" "),nab:"January February March April May June July August September October November December".split(" "),RGb:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),vtc:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),XGb:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
wtc:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SGb:"Sun Mon Tue Wed Thu Fri Sat".split(" "),V2b:"Sun Mon Tue Wed Thu Fri Sat".split(" "),h7c:"SMTWTFS".split(""),TGb:"SMTWTFS".split(""),ttc:["Q1","Q2","Q3","Q4"],ltc:["1st quarter","2nd quarter","3rd quarter","4th quarter"],R1b:["AM","PM"],KIa:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],oab:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],Uqc:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],
M$a:6,Ttc:[5,6],oGb:5};_.yC=_.DZc;
_.yC={erc:["\u0434\u043e \u043d. \u044d.","\u043d. \u044d."],B5c:["\u0434\u043e \u0420\u043e\u0436\u0434\u0435\u0441\u0442\u0432\u0430 \u0425\u0440\u0438\u0441\u0442\u043e\u0432\u0430","\u043e\u0442 \u0420\u043e\u0436\u0434\u0435\u0441\u0442\u0432\u0430 \u0425\u0440\u0438\u0441\u0442\u043e\u0432\u0430"],g7c:"\u042f\u0424\u041c\u0410\u041c\u0418\u0418\u0410\u0421\u041e\u041d\u0414".split(""),J7c:"\u042f\u0424\u041c\u0410\u041c\u0418\u0418\u0410\u0421\u041e\u041d\u0414".split(""),KGb:"\u044f\u043d\u0432\u0430\u0440\u044f \u0444\u0435\u0432\u0440\u0430\u043b\u044f \u043c\u0430\u0440\u0442\u0430 \u0430\u043f\u0440\u0435\u043b\u044f \u043c\u0430\u044f \u0438\u044e\u043d\u044f \u0438\u044e\u043b\u044f \u0430\u0432\u0433\u0443\u0441\u0442\u0430 \u0441\u0435\u043d\u0442\u044f\u0431\u0440\u044f \u043e\u043a\u0442\u044f\u0431\u0440\u044f \u043d\u043e\u044f\u0431\u0440\u044f \u0434\u0435\u043a\u0430\u0431\u0440\u044f".split(" "),
nab:"\u044f\u043d\u0432\u0430\u0440\u044c \u0444\u0435\u0432\u0440\u0430\u043b\u044c \u043c\u0430\u0440\u0442 \u0430\u043f\u0440\u0435\u043b\u044c \u043c\u0430\u0439 \u0438\u044e\u043d\u044c \u0438\u044e\u043b\u044c \u0430\u0432\u0433\u0443\u0441\u0442 \u0441\u0435\u043d\u0442\u044f\u0431\u0440\u044c \u043e\u043a\u0442\u044f\u0431\u0440\u044c \u043d\u043e\u044f\u0431\u0440\u044c \u0434\u0435\u043a\u0430\u0431\u0440\u044c".split(" "),RGb:"\u044f\u043d\u0432. \u0444\u0435\u0432\u0440. \u043c\u0430\u0440. \u0430\u043f\u0440. \u043c\u0430\u044f \u0438\u044e\u043d. \u0438\u044e\u043b. \u0430\u0432\u0433. \u0441\u0435\u043d\u0442. \u043e\u043a\u0442. \u043d\u043e\u044f\u0431. \u0434\u0435\u043a.".split(" "),
vtc:"\u044f\u043d\u0432. \u0444\u0435\u0432\u0440. \u043c\u0430\u0440\u0442 \u0430\u043f\u0440. \u043c\u0430\u0439 \u0438\u044e\u043d\u044c \u0438\u044e\u043b\u044c \u0430\u0432\u0433. \u0441\u0435\u043d\u0442. \u043e\u043a\u0442. \u043d\u043e\u044f\u0431. \u0434\u0435\u043a.".split(" "),XGb:"\u0432\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u044c\u0435 \u043f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a \u0432\u0442\u043e\u0440\u043d\u0438\u043a \u0441\u0440\u0435\u0434\u0430 \u0447\u0435\u0442\u0432\u0435\u0440\u0433 \u043f\u044f\u0442\u043d\u0438\u0446\u0430 \u0441\u0443\u0431\u0431\u043e\u0442\u0430".split(" "),
wtc:"\u0432\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u044c\u0435 \u043f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a \u0432\u0442\u043e\u0440\u043d\u0438\u043a \u0441\u0440\u0435\u0434\u0430 \u0447\u0435\u0442\u0432\u0435\u0440\u0433 \u043f\u044f\u0442\u043d\u0438\u0446\u0430 \u0441\u0443\u0431\u0431\u043e\u0442\u0430".split(" "),SGb:"\u0432\u0441 \u043f\u043d \u0432\u0442 \u0441\u0440 \u0447\u0442 \u043f\u0442 \u0441\u0431".split(" "),V2b:"\u0432\u0441 \u043f\u043d \u0432\u0442 \u0441\u0440 \u0447\u0442 \u043f\u0442 \u0441\u0431".split(" "),
h7c:"\u0412\u041f\u0412\u0421\u0427\u041f\u0421".split(""),TGb:"\u0412\u041f\u0412\u0421\u0427\u041f\u0421".split(""),ttc:["1-\u0439 \u043a\u0432.","2-\u0439 \u043a\u0432.","3-\u0439 \u043a\u0432.","4-\u0439 \u043a\u0432."],ltc:["1-\u0439 \u043a\u0432\u0430\u0440\u0442\u0430\u043b","2-\u0439 \u043a\u0432\u0430\u0440\u0442\u0430\u043b","3-\u0439 \u043a\u0432\u0430\u0440\u0442\u0430\u043b","4-\u0439 \u043a\u0432\u0430\u0440\u0442\u0430\u043b"],R1b:["AM","PM"],KIa:["EEEE, d MMMM y\u202f'\u0433'.","d MMMM y\u202f'\u0433'.",
"d MMM y\u202f'\u0433'.","dd.MM.y"],oab:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],Uqc:["{1} '\u0432' {0}","{1} '\u0432' {0}","{1}, {0}","{1}, {0}"],M$a:0,Ttc:[5,6],oGb:3};var EZc,FZc,GZc,JZc,LZc;EZc=RegExp("^((?:[-+]\\d*)?\\d{4})(?:(?:-?(\\d{2})(?:-?(\\d{2}))?)|(?:-?(\\d{3}))|(?:-?W(\\d{2})(?:-?([1-7]))?))?$");FZc=/^(\d{2})(?::?(\d{2})(?::?(\d{2})(\.\d+)?)?)?$/;GZc=/Z|(?:([-+])(\d{2})(?::?(\d{2}))?)$/;_.HZc=function(a,b){switch(b){case 1:return a%4!=0||a%100==0&&a%400!=0?28:29;case 5:case 8:case 10:case 3:return 30}return 31};
_.IZc=function(a,b){b=b||new Date(_.zh());var c;if(c=a.getDate()==b.getDate()){c=b||new Date(_.zh());if(b=a.getMonth()==c.getMonth())b=c||new Date(_.zh()),b=a.getFullYear()==b.getFullYear();c=b}return c};
_.KZc=function(a,b){b=_.ka(b);var c=b.indexOf("T")==-1?" ":"T";b=b.split(c);if((c=JZc(a,b[0]))&&!(c=b.length<2)){{c=b[1];b=c.match(GZc);let e;b&&(c=c.substring(0,c.length-b[0].length),b[0]==="Z"?e=0:(e=Number(b[2])*60+Number(b[3]),e*=b[1]=="-"?1:-1));var d=c.match(FZc);if(d){if(b){b=a.getYear();c=a.getMonth();const f=a.getDate(),g=Number(d[1]),h=Number(d[2])||0,k=Number(d[3])||0,l=d[4]?Number(d[4])*1E3:0;(d=b>=0&&b<100)&&(b+=400);b=Date.UTC(b,c,f,g,h,k,l);d&&(b-=126227808E5);a.setTime(b+e*6E4)}else a.setHours(Number(d[1])),
a.setMinutes(Number(d[2])||0),a.setSeconds(Number(d[3])||0),a.setMilliseconds(d[4]?Number(d[4])*1E3:0);c=!0}else c=!1}}return c};
JZc=function(a,b){var c=b.match(EZc);if(!c)return!1;const d=Number(c[2]),e=Number(c[3]),f=Number(c[4]);b=Number(c[5]);const g=Number(c[6])||1;a.setFullYear(Number(c[1]));f?(a.setDate(1),a.setMonth(0),a.add(new _.zC("d",f-1))):b?(a.setMonth(0),a.setDate(1),c=a.getDay()||7,a.add(new _.zC("d",(c<=4?1-c:8-c)+(Number(g)+7*(Number(b)-1))-1))):(d&&(a.setDate(1),a.setMonth(d-1)),e&&a.setDate(e));return!0};
_.zC=function(a,b,c,d,e,f){typeof a==="string"?(this.oa=a=="y"?b:0,this.qI=a=="m"?b:0,this.JD=a=="d"?b:0,this.hours=a=="h"?b:0,this.minutes=a=="n"?b:0,this.oT=a=="s"?b:0):(this.oa=a||0,this.qI=b||0,this.JD=c||0,this.hours=d||0,this.minutes=e||0,this.oT=f||0)};_.aa=_.zC.prototype;
_.aa.Qj=function(a){const b=Math.min(this.oa,this.qI,this.JD,this.hours,this.minutes,this.oT);var c=Math.max(this.oa,this.qI,this.JD,this.hours,this.minutes,this.oT);if(b<0&&c>0)return null;if(!a&&b==0&&c==0)return"PT0S";c=[];b<0&&c.push("-");c.push("P");(this.oa||a)&&c.push(Math.abs(this.oa)+"Y");(this.qI||a)&&c.push(Math.abs(this.qI)+"M");(this.JD||a)&&c.push(Math.abs(this.JD)+"D");if(this.hours||this.minutes||this.oT||a)c.push("T"),(this.hours||a)&&c.push(Math.abs(this.hours)+"H"),(this.minutes||
a)&&c.push(Math.abs(this.minutes)+"M"),(this.oT||a)&&c.push(Math.abs(this.oT)+"S");return c.join("")};_.aa.equals=function(a){return a.oa==this.oa&&a.qI==this.qI&&a.JD==this.JD&&a.hours==this.hours&&a.minutes==this.minutes&&a.oT==this.oT};_.aa.clone=function(){return new _.zC(this.oa,this.qI,this.JD,this.hours,this.minutes,this.oT)};_.aa.isZero=function(){return this.oa==0&&this.qI==0&&this.JD==0&&this.hours==0&&this.minutes==0&&this.oT==0};_.aa.getInverse=function(){return this.times(-1)};
_.aa.times=function(a){return new _.zC(this.oa*a,this.qI*a,this.JD*a,this.hours*a,this.minutes*a,this.oT*a)};_.aa.add=function(a){this.oa+=a.oa;this.qI+=a.qI;this.JD+=a.JD;this.hours+=a.hours;this.minutes+=a.minutes;this.oT+=a.oT};
_.AC=function(a,b,c){typeof a==="number"?(this.date=LZc(a,b||0,c||1),MZc(this,c||1)):_.cf(a)?(this.date=LZc(a.getFullYear(),a.getMonth(),a.getDate()),MZc(this,a.getDate())):(this.date=new Date(_.zh()),a=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),MZc(this,a))};LZc=function(a,b,c){b=new Date(a,b,c);a>=0&&a<100&&b.setFullYear(b.getFullYear()-1900);return b};_.aa=_.AC.prototype;_.aa.RKa=_.yC.M$a;_.aa.deb=_.yC.oGb;
_.aa.clone=function(){const a=new _.AC(this.date);a.RKa=this.RKa;a.deb=this.deb;return a};_.aa.getFullYear=function(){return this.date.getFullYear()};_.aa.getYear=function(){return this.getFullYear()};_.aa.getMonth=function(){return this.date.getMonth()};_.aa.getDate=function(){return this.date.getDate()};_.aa.getTime=function(){return this.date.getTime()};_.aa.getDay=function(){return this.date.getDay()};_.aa.getUTCFullYear=function(){return this.date.getUTCFullYear()};_.aa.getUTCMonth=function(){return this.date.getUTCMonth()};
_.aa.getUTCDate=function(){return this.date.getUTCDate()};_.aa.getUTCDay=function(){return this.date.getDay()};_.aa.getUTCHours=function(){return this.date.getUTCHours()};_.aa.getUTCMinutes=function(){return this.date.getUTCMinutes()};_.aa.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};_.aa.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};_.aa.setFullYear=function(a){this.date.setFullYear(a)};_.aa.setYear=function(a){this.setFullYear(a)};
_.aa.setMonth=function(a){this.date.setMonth(a)};_.aa.setDate=function(a){this.date.setDate(a)};_.aa.setTime=function(a){this.date.setTime(a)};_.aa.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};_.aa.setUTCMonth=function(a){this.date.setUTCMonth(a)};_.aa.setUTCDate=function(a){this.date.setUTCDate(a)};
_.aa.add=function(a){if(a.oa||a.qI){var b=this.getMonth()+a.qI+a.oa*12,c=this.getYear()+Math.floor(b/12);b%=12;b<0&&(b+=12);const d=Math.min(_.HZc(c,b),this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.JD&&(c=this.getYear(),b=c>=0&&c<=99?-1900:0,c=new Date(c,this.getMonth(),this.getDate(),12),a=new Date(c.getTime()+a.JD*864E5),this.setDate(1),this.setFullYear(a.getFullYear()+b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),MZc(this,a.getDate()))};
_.aa.Qj=function(a){var b=this.getFullYear();const c=b<0?"-":b>=1E4?"+":"";return[c+_.Wk(Math.abs(b),c?6:4),_.Wk(this.getMonth()+1,2),_.Wk(this.getDate(),2)].join(a?"-":"")};_.aa.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};_.aa.toString=function(){return this.Qj()};var MZc=function(a,b){a.getDate()!=b&&(b=a.getDate()<b?1:-1,a.date.setUTCHours(a.date.getUTCHours()+b))};_.AC.prototype.valueOf=function(){return this.date.valueOf()};
_.BC=function(a,b){return a.getTime()-b.getTime()};_.CC=function(a){const b=new _.AC(2E3);return JZc(b,a)?b:null};_.DC=function(a,b,c,d,e,f,g){this.date=typeof a==="number"?new Date(a,b||0,c||1,d||0,e||0,f||0,g||0):new Date(a&&a.getTime?a.getTime():_.zh())};_.Ah(_.DC,_.AC);_.aa=_.DC.prototype;_.aa.getHours=function(){return this.date.getHours()};_.aa.getMinutes=function(){return this.date.getMinutes()};_.aa.getSeconds=function(){return this.date.getSeconds()};_.aa.getMilliseconds=function(){return this.date.getMilliseconds()};
_.aa.getUTCDay=function(){return this.date.getUTCDay()};_.aa.getUTCHours=function(){return this.date.getUTCHours()};_.aa.getUTCMinutes=function(){return this.date.getUTCMinutes()};_.aa.getUTCSeconds=function(){return this.date.getUTCSeconds()};_.aa.getUTCMilliseconds=function(){return this.date.getUTCMilliseconds()};_.aa.setHours=function(a){this.date.setHours(a)};_.aa.setMinutes=function(a){this.date.setMinutes(a)};_.aa.setSeconds=function(a){this.date.setSeconds(a)};_.aa.setMilliseconds=function(a){this.date.setMilliseconds(a)};
_.aa.setUTCHours=function(a){this.date.setUTCHours(a)};_.aa.setUTCMinutes=function(a){this.date.setUTCMinutes(a)};_.aa.setUTCSeconds=function(a){this.date.setUTCSeconds(a)};_.aa.setUTCMilliseconds=function(a){this.date.setUTCMilliseconds(a)};_.aa.add=function(a){_.AC.prototype.add.call(this,a);a.hours&&this.setUTCHours(this.date.getUTCHours()+a.hours);a.minutes&&this.setUTCMinutes(this.date.getUTCMinutes()+a.minutes);a.oT&&this.setUTCSeconds(this.date.getUTCSeconds()+a.oT)};
_.aa.Qj=function(a){const b=_.AC.prototype.Qj.call(this,a);return a?b+"T"+_.Wk(this.getHours(),2)+":"+_.Wk(this.getMinutes(),2)+":"+_.Wk(this.getSeconds(),2):b+"T"+_.Wk(this.getHours(),2)+_.Wk(this.getMinutes(),2)+_.Wk(this.getSeconds(),2)};_.aa.equals=function(a){return this.getTime()==a.getTime()};_.aa.toString=function(){return this.Qj()};_.aa.clone=function(){const a=new _.DC(this.date);a.RKa=this.RKa;a.deb=this.deb;return a};_.NZc=function(a){const b=new _.DC(2E3);return _.KZc(b,a)?b:null};
var P8d=function(a){const b={};a=a.replace(/\r/g,"").split("\n");for(let c=0;c<a.length;c++){const d=a[c],e=d.indexOf(":");e<0||(b[d.substring(0,e)]=d.substring(e+2,d.length))}return b},Q8d=function(a,b){for(const c in a)if(c.toLowerCase()===b.toLowerCase())return a[c]},R8d=function(a,b){for(const c in a)if(c.toLowerCase()===b.toLowerCase()){delete a[c];break}},T8d=function(a){a=_.xc(a);for(let b=0;b<S8d.length;++b){const c=S8d[b],d=Q8d(a,c);d&&(a["X-Goog-Upload-Header-"+c]=d,R8d(a,c))}return a},
U8d=function(a){a=_.xc(a);R8d(a,"X-Goog-Upload-Status");return a},V8d=class{constructor(a){this.oa=a}};var W8d=function(){_.fe.call(this)};_.Ah(W8d,_.fe);var X8d=function(a){_.Vm.call(this,a)};_.Ah(X8d,_.Vm);var Y8d=function(a){_.Vm.call(this,a)};_.Ah(Y8d,_.Vm);var Z8d=function(a,b,c){c===void 0&&(c=a.size);return a.slice?a.slice(b,c):null};_.de(function(){if(!_.ca.Blob)return!1;const a=new Uint8Array(100);let b;try{b=new Blob([a])}catch(c){return!1}return b.size!=100?!1:!0});var $8d=_.de(function(){if(!_.ca.Blob)return!1;const a=new Uint8Array(100);let b;try{b=new Blob([a])}catch(c){return!1}return Z8d(b,0,1)===null?!1:!0});var a9d=class extends _.mr{constructor(){super()}X1a(){const a=_.mr.prototype.X1a.call(this);a.upload&&(a.upload.onprogress=(0,_.ie)(this.oa,this));return a}oa(a){this.dispatchEvent(a)}};var b9d=function(a){let b=250*Math.pow(a.mwc,a.oa);a.Ba>=0&&(b=Math.min(b,a.Ba));return b},c9d=function(a,b){const c=a.oa+1;if(a.Tzb>0&&c>a.Tzb)return!1;c==0?b():a.Aa=_.mn(()=>{a.Aa=null;b()},b9d(a),a);a.oa=c;return!0},d9d=class{constructor(){this.oa=-1;this.Aa=null;this.Ba=6E4;this.Tzb=-1;this.mwc=2}reset(){this.Aa&&_.on(this.Aa);this.oa=-1}};var S8d=["Content-Length","Content-Type","Content-Encoding","Transfer-Encoding"];var e9d=function(){_.fe.call(this);this.Sl=this.He=null;this.M_a=!1;this.Ea=null;this.oa=this.Aa=0;this.Ca=new d9d;this.Ca.Tzb=6;this.Ca.Ba=6E4;this.Ma=null;this.Gn=new _.cn(this);this.Xd(this.Gn);this.Wa=this.Ba=null;this.Pa=void 0;this.hb=this.Na=this.Da=null;this.Ka=!1;this.Mb=0;this.Va=this.Ua=this.Ta=null;this.Ha=!1;this.wb=null};_.Ah(e9d,W8d);_.aa=e9d.prototype;_.aa.run=function(){f9d(this)};_.aa.aFc=function(){return this.Aa};_.aa.c0a=function(){return this.Ta};_.aa.qfb=function(){return this.Ua};
_.aa.bA=function(){return this.Va};_.aa.Q6c=function(){return this.Ma};_.aa.cancel=function(){if(this.He!="Response received"&&this.He!="Error"){this.Gn.removeAll();this.Sl&&this.Sl.abort();this.Ca.reset();var a=this.He==="Paused"?this.wb:this.He;if(a==="Upload"||a==="Query")a=new a9d,a.setWithCredentials(this.M_a),a.send(this.Ea.oa,"POST","",{"X-Goog-Upload-Command":"cancel"});this.He="Cancel";this.Aa=0;this.dispatchEvent(new X8d("s"))}};_.aa.pause=function(){this.Ha=!0};
var f9d=function(a){const b=a.He;a.Ha?(a.Ha=!1,a.wb=b,a.He="Paused"):c9d(a.Ca,()=>{switch(a.He){case "Start":a.Sl=new a9d;var c=_.xc(a.Da);a.Ba.size!=null&&(c["Content-Length"]=a.Ba.size);c=T8d(c);c["X-Goog-Upload-Protocol"]="resumable";c["X-Goog-Upload-Command"]="start";a.Gn.removeAll();a.Gn.listen(a.Sl,"complete",a.Cb);a.Sl.setWithCredentials(a.M_a);a.Sl.send(a.Wa,a.Pa,a.Na,c);a.dispatchEvent(new Y8d("u"));break;case "Upload":c=a.Ea.oa;var d=a.Ba.size;if($8d()){var e=a.hb;var f=a.oa+e>=d;d=Z8d(a.Ba,
a.oa,f?d:a.oa+e)}else a.oa=0,d=a.Ba,f=!0;a.Sl=new a9d;a.Sl.setWithCredentials(a.M_a);a.Gn.removeAll();a.Gn.listen(a.Sl,"progress",a.Nb);e=(0,_.ie)(a.Fb,a,a.oa+d.size,f);a.Gn.listen(a.Sl,"complete",e);a.dispatchEvent(new Y8d("u"));f=Object.assign({},a.Da||{},{"X-Goog-Upload-Command":"upload"+(f?", finalize":""),"X-Goog-Upload-Offset":a.oa});a.Sl.send(c,"POST",d,f);break;case "Query":a.Sl=new a9d;a.Gn.removeAll();a.Gn.listen(a.Sl,"complete",a.Bb);c=Object.assign({},a.Da||{},{"X-Goog-Upload-Command":"query"});
a.Sl.send(a.Ea.oa,"POST","",c);a.dispatchEvent(new Y8d("u"));break;default:throw Error("wm");}})||g9d(a,"Transfer encountered too many consecutive failures.")},g9d=function(a,b){a.He="Error";a.Ma=b;a.dispatchEvent(new X8d("r"))};
e9d.prototype.Cb=function(a){const b=a.target;b.getStatus();this.dispatchEvent(new Y8d("v"));if(h9d(b))i9d(this,b);else if(j9d(b)){a=P8d(a.target.getAllResponseHeaders());for(var c in a)_.fa(c.toLowerCase(),"x-goog-upload-header-");this.dispatchEvent(new X8d("q"));c=Q8d(a,"X-Goog-Upload-URL");a=(a=Q8d(a,"X-Goog-Upload-Chunk-Granularity"))?parseInt(a,10):1;c===void 0||isNaN(a)||a<=0?g9d(this,"Server returned invalid headers."):(this.hb=Math.floor(1073741824/a)*a,this.Ea=new V8d(c),this.dispatchEvent(new X8d("t")),
this.He="Upload",this.Ca.reset(),f9d(this))}else f9d(this)};e9d.prototype.Nb=function(a){this.Aa=this.oa+a.loaded;this.dispatchEvent(new X8d("o"))};e9d.prototype.Fb=async function(a,b,c){try{const d=c.target;d.getStatus();this.dispatchEvent(new Y8d("v"));k9d(d)||d.getStatus()==404?(this.Aa=a,i9d(this,d)):j9d(d)?b?g9d(this,"Got a non-final success response after issuing a finalize command."):(this.oa=this.Aa=a,this.Ca.reset(),f9d(this)):(this.Ka=d.getStatus()==400,this.He="Query",f9d(this))}finally{_.y()}};
e9d.prototype.Bb=function(a){const b=a.target;b.getStatus();this.dispatchEvent(new Y8d("v"));h9d(b)?(b.getStatus()===200&&(this.Aa=this.Ba.size),i9d(this,b)):j9d(b)?(a=P8d(a.target.getAllResponseHeaders()),a=parseInt(Q8d(a,"X-Goog-Upload-Size-Received"),10),isNaN(a)?g9d(this,"Server did not respond with current offset."):a<this.oa?g9d(this,"Server lost bytes! Expected an offset of at least "+this.oa+", but got an offset of "+a+"."):this.Ka&&this.oa===a?g9d(this,"Server returned the same offset as the last failed upload attempt."):
(this.Ka=!1,this.oa<a&&this.Ca.reset(),this.oa=this.Aa=a,this.He="Upload",f9d(this))):f9d(this)};
var i9d=function(a,b){a.Ta=b.getStatus();const c=P8d(b.getAllResponseHeaders());a.Ua=U8d(c);a.Va=b.bA();a.He="Response received";a.dispatchEvent(new X8d("p"))},j9d=function(a){const b=a.getStatus();a=P8d(a.getAllResponseHeaders());a=Q8d(a,"X-Goog-Upload-Status");return b===200&&a==="active"},k9d=function(a){a=P8d(a.getAllResponseHeaders());return Q8d(a,"X-Goog-Upload-Status")==="final"},h9d=function(a){if(k9d(a))return!0;a=a.getStatus();return a>=400&&a<500};var l9d=class extends W8d{constructor(a,b,c,d){super();this.Aa=c;this.Ua=a;this.Ta="POST";this.Na=b;this.Pa=d;this.Ma=0;a=new _.AC;this.Ba="uploader-"+_.kEa()+"-"+a.Qj();this.oa=null;this.Ca=0;this.Ka=this.Ha=this.Ea=null;this.He="Ready";this.Da=null;this.Gn=new _.cn(this);this.Xd(this.Gn)}run(){var a=_.xc(this.Na);this.Aa.length!=null&&(a["Content-Length"]=this.Aa.length);a=T8d(a);a["X-Goog-Upload-Protocol"]="multipart";a["Content-Type"]="multipart/related; boundary="+this.Ba;this.He="Transferring";
this.oa=new a9d;this.Gn.removeAll();this.Gn.listen(this.oa,"progress",this.Wa);this.Gn.listen(this.oa,"complete",this.Va);var b=this.oa,c=b.send,d=this.Ua,e=this.Ta;const f="--"+this.Ba+'\r\nContent-Disposition: form-data; name="metadata"\r\n\r\n'+(this.Pa+"\r\n--")+this.Ba+'\r\nContent-Disposition: form-data; name="Filedata"\r\nContent-Transfer-Encoding: binary\r\n\r\n'+this.Aa+"\r\n--"+this.Ba+"--\r\n";this.Ma=f.length-this.Aa.length;c.call(b,d,e,f,a)}aFc(){return this.Ca}c0a(){return this.Ea}qfb(){return this.Ha}bA(){return this.Ka}Q6c(){return this.Da}cancel(){this.He!=
"Complete"&&this.He!="Error"&&(this.Gn.removeAll(),this.oa&&this.oa.abort(),this.He="Cancel",this.dispatchEvent(new X8d("s")))}pause(){}Wa(a){this.Ca=Math.max(0,a.loaded-this.Ma);this.dispatchEvent(new X8d("o"))}Va(a){var b=a.target.getStatus();b===void 0||b===-1?(this.Da="Connection broken before response was received.",this.He="Error",this.dispatchEvent(new X8d("r"))):(this.Ea=b,a=a.target,b=P8d(a.getAllResponseHeaders()),this.Ha=U8d(b),this.Ka=a.bA(),this.He="Complete",this.dispatchEvent(new X8d("p")))}};_.m9d=function(a,b,c,d,e=!1,f){if(typeof c==="string"||c instanceof String)return new l9d(a,b,c,d);f=new e9d(f);f.Wa=a;f.Pa="POST";f.Da=b;f.Ba=c;f.Mb=c.size;f.Na=d;e&&(f.M_a=e);f.He="Start";return f};
_.N8d=class extends _.m{constructor(a){super(a,3)}getViewerType(){return _.xi(this,1)}Kp(a){return _.Hg(this,1,a)}};_.O8d=new _.Pg("cinoBd",class extends _.m{constructor(a){super(a)}},_.N8d,[_.yq,!0,_.zq,"/ViewerService.WriteFootprint"]);
var K8d;K8d=class extends _.m{constructor(a){super(a)}SDa(){return _.xi(this,2)}getUrl(){return _.A(this,3)}Rc(){return _.xj(this,3)}yd(){return _.ti(this,3)}getTitle(){return _.A(this,4)}setTitle(a){return _.Sf(this,4,a)}ld(){return _.xj(this,4)}jj(){return _.A(this,5)}getUniqueId(){return _.sd(this,7)}};
_.L8d=class extends _.m{constructor(a){super(a)}u8(){return _.ai(this,27)}hgb(){return _.zj(this,27)}YNb(){return _.A(this,11)}Pu(){return _.xi(this,18)}wZ(){return _.$f(this,K8d,24,_.ag())}pja(){return _.Rh(this,K8d,24)}K$(){return _.xi(this,26)}};_.M8d=function(a){return _.p(a,_.L8d,4)};
_.J8d=_.x("T1HOxc",[_.Fo]);
_.y8d=[1,4,5];_.z8d=function(a){return _.Sf(a,16,google.kEI)};_.A8d=function(a,b){return _.Sf(a,1,b)};_.B8d=function(a,b){return _.Sf(a,2,b)};_.C8d=function(a,b){return _.Sf(a,4,b)};_.D8d=function(a,b){return _.Sf(a,3,b)};_.E8d=function(a,b){return _.lh(a,11,b)};_.F8d=function(a,b){_.Sf(a,12,b)};_.G8d=function(a,b){return _.Sf(a,6,b)};
_.H8d=class extends _.m{constructor(a){super(a)}Dfa(){return _.sd(this,28)}jJ(){return _.A(this,4)}oF(){return _.A(this,3)}getAttribute(){return _.A(this,5)}setAttribute(a){return _.Sf(this,5,a)}hasAttribute(){return _.xj(this,5)}TY(){return _.Nd(this,14)}getDescription(){return _.A(this,6)}Oh(){return _.ti(this,6)}jy(){return _.p(this,_.OB,32)}nS(){return _.xi(this,33)}};_.I8d=[0,_.E,-6,_.D,2,_.C,_.E,-5,_.gk,_.rk,1,_.C,1,_.H,_.E,-1,_.rk,-1,_.C,_.E,-2,_.QUc,_.H,[0,_.E,-1,[0,_.C,-2],_.E,-1,_.D,[0,_.E,-1,[0,_.H,_.E,-18,_.vk,[0,21,_.E,-1]]],_.E,-1,_.F,[0,_.E,-1]],_.xk,[0,_.C,_.E,-1,_.D,_.E],_.xk,_.F,[0,_.y8d,_.tk,_.QUc,_.C,_.tk,-1],_.xk];_.xn[191450109]=_.I8d;
_.PWc=!!(_.uh[41]>>28&1);_.QWc=!!(_.uh[41]>>29&1);_.RWc=!!(_.uh[42]&1);_.SWc=!!(_.uh[42]&2);_.TWc=!!(_.uh[42]&4);_.UWc=!!(_.uh[42]&8);_.VWc=!!(_.uh[42]&16);_.WWc=!!(_.uh[42]&32);_.XWc=!!(_.uh[42]&64);_.YWc=!!(_.uh[42]&128);_.ZWc=!!(_.uh[42]&256);_.$Wc=!!(_.uh[42]&512);_.aXc=!!(_.uh[42]&1024);_.bXc=!!(_.uh[42]&2048);_.cXc=!!(_.uh[42]&4096);_.dXc=!!(_.uh[42]&8192);_.eXc=!!(_.uh[42]>>14&1);_.fXc=!!(_.uh[42]>>15&1);_.gXc=!!(_.uh[42]>>16&1);_.hXc=!!(_.uh[42]>>17&1);_.iXc=!!(_.uh[42]>>18&1);
_.jXc=!!(_.uh[42]>>19&1);
var $Uc;$Uc=[0,_.E,-1];
_.QB=class extends _.m{constructor(a){super(a)}mB(){return _.Tf(this,2)}oF(){return _.Tf(this,3)}qca(){return _.Tf(this,4)}Aa(){return _.ti(this,4)}Dfa(){return _.Si(this,8)}Ht(){return _.Tf(this,10)}UK(){return _.ti(this,10)}Qq(){return _.Si(this,12)}jy(){return _.p(this,_.OB,14)}getAttribute(){return _.Tf(this,15)}setAttribute(a){return _.Sf(this,15,a)}hasAttribute(){return _.xj(this,15)}nS(){return _.Wi(this,20)}getViewerType(){return _.Wi(this,21)}Kp(a){return _.Hg(this,21,a)}};_.aVc=[30,32];
_.QB.prototype.ob="vST7rb";_.bVc=[0,_.aVc,_.D,_.E,-2,_.rk,_.H,_.E,_.C,_.E,-1,_.H,_.C,_.E,_.QUc,_.E,_.rk,1,_.C,_.E,_.H,-1,_.xk,_.D,-1,_.E,_.D,_.E,_.D,-1,_.tk,_.D,_.wk,$Uc];
_.FWc=function(a){return _.ei(a,_.tUc,1)};_.GWc=class extends _.m{constructor(a){super(a)}getName(){return _.Tf(this,1)}Le(a){return _.Sf(this,1,a)}Qg(){return _.xj(this,1)}getValue(){return _.Tf(this,2)}tB(){return _.Tf(this,2)}setValue(a){return _.Sf(this,2,a)}clearValue(){return _.Nd(this,2)}hasValue(){return _.xj(this,2)}Xg(){return _.ti(this,2)}};_.eC=function(a){var b=new _.QB;return _.Sf(b,2,a)};_.fC=function(a,b){return _.Sf(a,3,b)};_.gC=function(a,b){return _.Sf(a,4,b)};
_.hC=function(a){return _.Wi(a,6)};_.iC=function(a,b){return _.Hg(a,6,b)};_.mC=function(a){return _.Wi(a,11)};_.HWc=function(a,b){return _.lh(a,12,b)};_.IWc=function(a,b){return _.Sf(a,13,b)};_.JWc=function(a,b){return _.Bb(a,_.OB,14,b)};_.KWc=function(a,b){return _.lh(a,18,b)};_.nC=function(a,b){return _.Hg(a,20,b)};_.oC=function(a,b){return _.Jg(a,24,b)};_.LWc=function(a){return _.Jg(a,26,!0)};_.MWc=function(a,b){return _.ji(a,32,_.aVc,b)};_.NWc=function(a){return _.Jg(a,31,!0)};
var oXc,pXc;_.lXc=function(a){var b=a.closest(_.io("jsname","aadvhe"));if(b){var c=_.rl(b.getData("proxy"),"");a=_.rl(b.getData("rootname"),"");const d=_.rl(b.getData("fbrtdan"),"");b=_.rl(b.getData("fbrtdav"),"");if(c){c=new _.lo([_.Jl(c)]);let e=new _.lo([]);a&&(e=c.closest(_.io("jsname",a)));d&&b&&(e=c.closest(_.POa(d,b)));e.first()||(e=_.kXc(c));return e.first()?e:void 0}}};
_.kXc=function(a){let b=a.closest(_.POa("kpfbroot"));b.first()||(b=a.closest(_.ho("EyBRub")));(a=_.rl(b.getData("kpid"),""))&&(b=new _.lo(Array.from(document.querySelectorAll(`[data-kpid="${a}"]`))));return b};_.mXc=function(a){let b;return(b=_.lXc(a))!=null?b:_.kXc(a)};
_.nXc=function(a,b=!1){switch(a.nodeType){case Node.ELEMENT_NODE:const c=window.getComputedStyle(a);if(c.display==="none"||Number(c.opacity)<.01||_.xl.contains(a,"gmlSVb")||b&&a.getAttribute("aria-hidden")==="true")return"";if(a.tagName==="BR")return b?" ":"\n";a=Array.from(a.childNodes).map(d=>_.nXc(d,b)).join(b?" ":"");c.display!=="block"||b||(a=`
${a}
`);return b?a.replace(/\s+/g," ").trim():a;case Node.TEXT_NODE:return a.nodeValue.replace(/\s+/g," ").trim();default:return""}};_.qXc=function(a,b){return oXc(a,new _.$Aa(pXc(b)))};_.rXc=function(a,b){return _.Sf(a,27,b)};oXc=_.ria(_.bVc);pXc=_.Hb(_.bVc);
_.t("T1HOxc");
var s9d,t9d,u9d,v9d,w9d,x9d,y9d,z9d,A9d,p9d,r9d,B9d,C9d,D9d,E9d,F9d,J9d,K9d,L9d,M9d,N9d,O9d,P9d,Q9d,S9d,U9d,V9d,W9d,X9d,Y9d,Z9d,o9d,$9d;_.n9d=function(a,b){let c,d,e=(a==null?void 0:(c=a.iRe)==null?void 0:(d=c.el())==null?void 0:d.outerHTML)||"";e=e.replaceAll(b,"");a.Smc=new Blob([`<!DOCTYPE html>\n${e}`],{type:"text/html"});return a};
_.q9d=function(a){const b=a.getData("proxy").Lb()&&(a.getData("rootname").Lb()||a.getData("fbrtdan").Lb()&&a.getData("fbrtdav").Lb()),c=[];if(!_.TWc)return c;const d=_.mXc(a);d.size()>0&&_.mo(d,e=>{e==null||e.find("[jsname=KTP9Gb]").each(f=>{f=new _.oo(f);if(b||_.kXc(f).equals(d)){var g=_.rl(f.getData("ffd"),"");g&&(g=o9d(g),c.push(g));if(g=_.rl(f.getData("ffdb"),""))f=new p9d,f=_.ej(f,4,_.y8d,g),c.push(f)}})});return c};
s9d=function(a,b){const c=[];document.body.querySelectorAll(`[jsname=${a}]`).forEach(d=>{var e=c.push;var f=new r9d;d=d.getAttribute("href")||"";f=_.Sf(f,1,d);f=_.Sf(f,2,b);e.call(c,f)});return c};t9d=function(){return[...s9d("OYkqOb","/search"),...s9d("D2tCC","MagiLRO"),...s9d("pJjOnd","Async")]};u9d=class extends _.m{constructor(a){super(a)}getStatus(){return _.xi(this,1)}Dl(){return _.Aj(this,1)}};
v9d=class extends _.m{constructor(a){super(a)}getScrollWidth(){return _.sd(this,3)}getScrollHeight(){return _.sd(this,4)}};w9d=class extends _.m{constructor(a){super(a)}};x9d=class extends _.m{constructor(a){super(a)}zTa(){return _.xi(this,2)}Kfb(){return _.A(this,4)}};y9d=class extends _.m{constructor(a){super(a)}getHeight(){return _.sd(this,2)}dh(){return _.nd(this,2)}getWidth(){return _.sd(this,3)}lj(){return _.nd(this,3)}Hj(){return _.si(this,3)}};z9d=function(a,b){_.Sf(a,17,b)};
A9d=function(a,b){_.Sf(a,30,b)};p9d=class extends _.m{constructor(a){super(a)}jy(){return _.p(this,_.OB,2)}};p9d.prototype.ob="FUsGEc";r9d=class extends _.m{constructor(a){super(a)}};B9d=class extends _.m{constructor(a){super(a)}};C9d=function(a,b){return _.Sf(a,1,b)};D9d=function(a){return _.Jg(a,6,!!document.body.dataset.dt)};E9d=function(a){var b=new B9d;b=_.Sf(b,1,window.navigator.userAgent);b=_.Sf(b,2,window.navigator.platform||"");return _.Bb(a,B9d,7,b)};
F9d=class extends _.m{constructor(a){super(a)}bW(){return _.A(this,1)}Qxa(){return _.xj(this,1)}Uc(){return _.A(this,8)}};_.G9d=function(a,b){return _.lh(a,1,b)};_.H9d=function(a,b){return _.Sf(a,2,b)};_.I9d=class extends _.m{constructor(a){super(a)}Qq(){return _.sd(this,1)}};J9d=function(a,b){return _.Jg(a,8,b)};K9d=function(a,b){return _.Sf(a,25,b)};L9d=function(a,b){_.Sf(a,13,b)};M9d=function(a,b){_.Sf(a,14,b)};N9d=function(a,b){_.Sf(a,15,b)};O9d=function(a,b){_.lh(a,21,b)};
P9d=function(a,b){_.Sf(a,17,b)};Q9d=function(a,b){return _.jj(a,18,b)};_.R9d=function(a,b){return _.lj(a,19,b)};S9d=function(a,b){_.Sf(a,31,b)};_.T9d=function(a,b){return _.Bb(a,_.OB,32,b)};U9d=function(a,b){_.gj(a,35,b)};V9d=function(a,b){return _.Hg(a,33,b)};W9d=function(a,b){_.Bb(a,F9d,34,b)};X9d=function(a,b){return _.Bb(a,_.I9d,36,b)};Y9d=class{};Z9d=function(a){var b=t9d();return _.mi(a,10,r9d,b)};o9d=_.Ob(p9d);$9d=_.Hb(_.I8d);var a$d=class extends _.m{constructor(a){super(a)}getKey(){return _.A(this,1)}qf(a){return _.Sf(this,1,a)}getValue(){return _.A(this,2)}setValue(a){return _.Sf(this,2,a)}clearValue(){return _.Nd(this,2)}hasValue(){return _.xj(this,2)}Xg(){return _.ti(this,2)}};var b$d=class extends _.m{constructor(a){super(a)}Qc(){return _.A(this,1)}};var c$d=class extends _.m{constructor(a){super(a)}};var d$d=new _.Pg("AouTef",class extends _.m{constructor(a){super(a)}},c$d,[_.yq,!1,_.zq,"/FeedbackService.SubmitFeedback"]);var e$d=class extends _.m{constructor(a){super(a)}mB(){return _.A(this,1)}Ou(){return _.vi(this,3)}lp(){return _.xi(this,4)}getAttribute(){return _.A(this,7)}setAttribute(a){return _.Sf(this,7,a)}hasAttribute(){return _.xj(this,7)}jJ(){return _.p(this,_.uHb,10)}},f$d=[8,9];e$d.prototype.ob="FJ7EAe";var g$d=class extends _.m{constructor(a){super(a)}};g$d.prototype.ob="HCpCab";new _.gh(g$d);var h$d=class extends _.m{constructor(a){super(a)}getStatus(){return _.p(this,_.iu,1)}Dl(){return _.Oh(this,_.iu,1)}};h$d.prototype.ob="IcozSe";new _.gh(h$d);var i$d=new _.Pg("IHXYOd",h$d,g$d,[_.yq,!1,_.zq,"/UgkContributionsService.WriteFactualFeedback"]);var j$d=class extends _.m{constructor(a){super(a)}};var k$d=_.Cb(1002,_.N8d,j$d);var m$d,n$d,p$d,r$d,u$d,s$d,t$d,w$d,l$d,x$d,v$d,o$d,z$d,q$d;
m$d=function(a,b,c,d){var e=Date.now();a=a.Id;var f=a.Ac,g=d$d.getInstance;var h=l$d("force_authority_for_cards")&&l$d("force_mothership");var k=[(new a$d).qf("dtype").setValue("d3af"),(new a$d).qf("rtext").setValue((c.Va()||"").substring(0,_.gXc?1E3:200)),(new a$d).qf("rved").setValue(_.ti(c,3))];c.getAttribute()!=="image"&&c.getAttribute()!=="secondary image"||k.push((new a$d).qf("all_locales").setValue("true"));var l=new b$d;var n=_.ti(c,10);l=_.Sf(l,1,n);e=_.xg(l,2,e);d=_.Sf(e,3,d);e=b.Bb();d=
_.Sf(d,11,e);e=b.Ka();d=_.Sf(d,4,e);e=b.Da();d=_.Sf(d,5,e);c=_.ti(c,2);c=_.Sf(d,6,c);k=_.ki(c,7,k);b=b.Ha();b=[_.jj(k,8,b)];k=new c$d;b=_.ki(k,1,b);h=_.Jg(b,2,h);f.call(a,g.call(d$d,h))};n$d=function(a){var b=/^data:([^;]+);base64,(.*)$/.exec(a);if(!b)return null;a=b[1];b=atob(b[2]);const c=new Uint8Array(new ArrayBuffer(b.length));for(let d=0;d<b.length;d++)c[d]=b.charCodeAt(d);return new Blob([c],{type:a})};
p$d=function(a){const b=[];a.tagName==="IMG"&&a.getAttribute("src")!==null?b.push(o$d(a,a.getAttribute("data-attrid")==="SGEGenerativeImage")):(new _.lo([a])).find("img").each(c=>{c.getAttribute("src")&&b.push(o$d(c,a.getAttribute("data-attrid")==="SGEGenerativeImage"))});return b};
r$d=async function(a,b,c=!1){var d;const e=a.Meb(!!(b==null?0:(d=b.kba)==null?0:d.Smc),!(b==null||!b.MSc));let f;d=q$d(a,c,!!(b==null?0:(f=b.kba)==null?0:f.Smc));a.Aa||(a.Aa=new Y9d);let g,h;if((b==null?0:b.kba)&&(b==null?0:(h=b.kba)==null?0:h.Smc))a=b.kba.Smc;else if(b==null?0:b.kxb)a=b.kxb.blob;else if(b==null?0:b.MSc)a=b.MSc;else return _.Yd(Error("zm")),Promise.resolve(null);g=_.m9d(d,e,a,"",c);c=new Promise(k=>{g.listenOnce("p",()=>{g.c0a()!==200?(_.Yd(Error("Am")),g.bA()&&(b.errorMessage=g.bA(),
k(b))):g.bA()&&(b.cia=g.bA(),k(b))})});g.run();return c};
u$d=function(a,b,c,d,e,f,g=!1,h=!1,k=!1,l=!1,n,q){h&&(b.Mb()||b.Wa(),b.Rb()||b.hb());const r=s$d(a,b,c,e,n,f,h);let u,B;if(!e.SKe&&((u=r.jy())==null?0:(B=_.uUc(u))==null?0:B.has("where_to_vote_reference_address"))){let G,L;(G=r.jy())==null||(L=_.uUc(G))==null||L.delete("where_to_vote_reference_address")}e=_.Mra(r.serialize());f=a.Ba.get(e)||0;if(g&&f>0)return _.Yd(Error("xm")),Promise.resolve();if(!g&&f>=10)return _.Yd(Error("ym")),Promise.resolve();a.Ba.set(e,f+1);if(a.Sua().Z7c&&(l$d("force_oversize_fb_upload")||
r.serialize().length>2048)&&l)return g=new Blob([$9d(r)],{type:"application/x-protobuf"}),Promise.resolve({MSc:g}).then(G=>r$d(a,G,!1)).then(G=>{var L=new _.OB;if(_.Oh(r,_.OB,32)){var N=r.jy(),T;if(T=_.Oh(N,_.L8d,4))T=_.M8d(N),T=_.xj(T,1);T&&(T=new _.L8d,N=_.M8d(r.jy()),N=_.A(N,1),T=_.Sf(T,1,N),_.Bb(L,_.L8d,4,T))}T=new w9d;G=_.Sf(T,1,G.cia);T=new u9d;T=_.Hg(T,1,1);G=_.ji(G,4,_.qUc,T);_.mh(L,14,w9d,G);L=_.T9d(V9d(new _.H8d,_.Lg(r,33)),L);t$d(a,L,b,c,d,k,q)});t$d(a,r,b,c,d,k,q);return Promise.resolve()};
s$d=function(a,b,c,d,e,f,g){a=X9d(_.R9d(Q9d(_.G8d(_.C8d(_.D8d(_.B8d(_.A8d(K9d(J9d(_.z8d(new _.H8d),b.Ma()),b.Cb()||""),b.Da()),b.Ka()),(c.oF()||b.oF()||"").substring(0,100)),c.mB()||b.Pa()).setAttribute((c.getAttribute()||"").substring(0,100)),d.comments),b.Ha()),b.Ua()),_.H9d(_.G9d(new _.I9d,c.Qq()||b.Qq()||a.Qq(!1)),c.Mb()||b.wb()||"KNOWLEDGE_PANEL"));var h=_.Tf(c,3);if(h!==null){try{var k=_.Jla((0,_.Ola)(h.substring(1)))||0}catch(q){k=-1}k!==-1?_.E8d(a,k):/^\d+$/.test(h)&&_.E8d(a,Number(h))}h=
_.au().mutable();for(var l of h)l.length===2&&l[0].substring(0,4)==="kpfb"&&h.delete(l[0]);W9d(a,Z9d(D9d(E9d(C9d(new F9d,h.toString())))));d.iNa!=null&&_.Hg(a,23,d.iNa);d.F5a&&_.Sf(a,29,d.F5a);d.u7a!==""&&_.Sf(a,24,d.u7a);c.Nc()&&L9d(a,c.qc());l=(c.wg()||"").split(",").filter(q=>q!=="");l.length>0&&_.lj(a,26,l);c.xc()&&M9d(a,c.Rb());c.Kc()&&N9d(a,c.Vb());c.Dd()&&O9d(a,c.rc());c.Lc()&&P9d(a,c.Yb());c.vd()&&_.F8d(a,(_.ti(c,4)||"").substring(0,_.gXc?1E3:200));S9d(a,((g?v$d():_.vf("q")||v$d())||"").substring(0,
200));g=new _.OB;c.zD()&&(g=c.Ha());b.Va()&&z9d(g,b.Fb());b=e.filter(q=>(q==null?void 0:q.kxb)&&(q==null?void 0:q.cia)).map(q=>{let r;var u=new x9d;u=_.Sf(u,1,q.cia);q=((r=q.kxb)==null?void 0:r.M4a)||0;return _.Hg(u,2,q)});b.length>0&&(_.mi(g,12,x9d,b),b=b.map(q=>_.A(q,1)),_.qCa(g,10,b));e=e.filter(q=>q==null?void 0:q.kba).map(q=>{var r,u,B,G;var L=new w9d;L=_.Sf(L,1,q==null?void 0:q.cia);L=_.Sf(L,5,q==null?void 0:q.errorMessage);var N=new v9d,T=((r=q.kba)==null?void 0:r.wIa)||0;r=_.lh(N,1,T);N=((u=
q.kba)==null?void 0:u.J4)||0;u=_.lh(r,2,N);r=((B=q.kba)==null?void 0:B.scrollWidth)||0;B=_.lh(u,3,r);q=((G=q.kba)==null?void 0:G.scrollHeight)||0;G=_.lh(B,4,q);return _.ji(L,2,_.qUc,G)});e.length>0&&_.mi(g,14,w9d,e);c.wb()&&A9d(g,_.qWc(c));_.T9d(a,g);if(c.fF()){var n;U9d(a,_.Fca(_.Jh((n=c==null?void 0:_.ti(c,21))!=null?n:"")))}if(c.Np()){let q;U9d(a,_.Fca(_.Jh((q=c==null?void 0:_.ti(c,25))!=null?q:"")))}n=d.Phd||[];n.length>0&&_.lj(a,27,n);d=d.lEb||"";d!==""&&_.Sf(a,7,d);c.Jc()&&V9d(a,c.nS());f.length>
0&&_.mi(a,38,p9d,f);return a};t$d=function(a,b,c,d,e,f=!1,g){g===void 0?w$d(a,b,c,e,f,_.Lg(d,22)):g(b)};
w$d=function(a,b,c,d,e=!1,f=0){e?(d=(new _.N8d).Kp(f),c=d.oa,e=new j$d,b=_.Bb(e,_.H8d,1,b),b=c.call(d,k$d,b),a.Id.fetch(_.O8d.getInstance(b))):c.Qb()?(d=new e$d,c=_.ti(b,4),d=_.Sf(d,1,c),d=_.Hg(d,4,3),c=_.ti(b,2),d=_.Sf(d,5,c),c=_.ti(b,1),d=_.Sf(d,6,c).setAttribute(_.ti(b,5)),b=_.ji(d,9,f$d,b),d=new g$d,b=_.Bb(d,e$d,1,b),a.Id.Ac(i$d.getInstance(b))):(c=_.Pf(new _.Ln({path:"/fp_204",sendDataInUrl:!0})).Hc("authuser",x$d()),d&&a.oa?c.Hc("kefb",a.oa(b)).Hc("kpfbftype","1").log():c.Hc("kefb",b.serialize()).log())};
l$d=function(a){return _.vf("opts").split(",").includes(a)};x$d=function(){let a;try{a=_.ul(_.Xc("QrtxK")).toString()}catch(b){a="0"}return a};v$d=function(){const a=_.au();return a.has("q")?a.get("q"):""};
_.y$d=async function(a,b,c,d,e=!1,f,g,h=!1){try{const l={comments:b.getDescription()||"",u7a:b.Ua()||"",iNa:b.Ta()||0,F5a:null,Phd:null,lEb:void 0},n=_.rWc((new _.aC).Ca(b.Na()).Ba(b.Pa()).setAttribute(b.Ba()).Pa(b.Wa()).Ta(b.Va()).Ka(b.jy()).Da(b.Aa()),b.Ca());b.Ma()&&n.Ua(_.Ad(_.Lh(b.Ka()),4));var k=b.Da();k=!(k===40||k===41||k===42);const q=c.Ba(b.Qq()||c.Ta()).Aa(b.Ha()||c.Na());_.y(await _.y(a.submit(q,n,!1,l,d,k,!1,!1,e,void 0,h,f,g)));return Promise.resolve()}finally{_.y()}};
o$d=async function(a,b){const c=a.src;return b?Promise.resolve(z$d(a)):c.startsWith("data")&&(b=n$d(c))?Promise.resolve({kxb:{blob:b,width:a.naturalWidth,height:a.naturalHeight,M4a:5}}):Promise.resolve(null)};
z$d=async function(a){try{let b;const c=(b=a.naturalHeight)!=null?b:512;let d;const e=(d=a.naturalWidth)!=null?d:512,f=Math.max(e,c),g=_.uVb((new _.Pw).setSize(f),!0),h=`${_.Vw(a.getAttribute("src"),g,!1)}?alr=yes`,k=_.y(await _.y(fetch(h,{credentials:"include",headers:{accept:"text/plain"}}))),l=_.y(await _.y(k.text())),n=_.y(await _.y(fetch(l,{credentials:"include",headers:{accept:"image/png"}})));return{kxb:{blob:_.y(await _.y(n.blob())),width:e,height:c,M4a:4}}}finally{_.y()}};
q$d=function(a,b=!1,c=!1){a.Sua().Y7c&&c||a.Sua().Z7c?(a=new URL("https://content-push.googleapis.com/upload/"),l$d("dev_upload")&&(a=new URL("https://cda-push-dev.sandbox.googleapis.com/upload/"))):(a=b?new URL("https://push.clients6.google.com/upload/"):new URL("https://content-push.googleapis.com/upload/"),b&&a.searchParams.append("authuser",x$d()));return a.toString()};
_.A$d=class extends _.co{static Sa(){return{service:{ze:_.sr}}}Sua(){return{Y7c:_.YWc,TZd:_.dXc,Z7c:_.eXc}}constructor(a){super();this.Aa=this.oa=void 0;this.Ba=new Map;this.Id=a.service.ze}async submit(a,b,c,d,e,f=!1,g=!1,h=!1,k=!1,l,n=!1,q,r){if(a.Ca())return m$d(this,a,b,d.comments),Promise.resolve();let u=[];var B;let G,L;const N=(L=b==null?void 0:(B=b.Ha())==null?void 0:(G=_.M8d(B))==null?void 0:_.p(G,y9d,29))!=null?L:new y9d;if(_.xj(N,1)&&(b==null?void 0:b.getAttribute())!=="MagiThumbsFeedback"&&
(B=n$d(_.A(N,1)))){u.push(Promise.resolve({kxb:{blob:B,width:N.getWidth(),height:N.getHeight(),M4a:3}}));let T,Z;b!=null&&(T=b.Ha())!=null&&(Z=_.M8d(T))!=null&&_.Nd(Z,29)}if(typeof l!=="undefined"){for(const T of l.toArray())T.removeAttribute("ispicked"),u.push(...p$d(T));u.length>10&&(u=u.splice(0,10))}q&&this.Sua().Y7c&&u.push(Promise.resolve({kba:q}));return Promise.all(u).then(T=>{const Z=[];T.forEach(Y=>{Y&&Z.push(r$d(this,Y,n))});return Promise.all(Z)}).then(T=>u$d(this,a,b,c,d,e,f,g,h,k,T,
r))}Qq(a){return a?l$d("force_authority_for_cards")?1330975:410953:100334}Meb(a=!1,b=!1){const c={};this.Sua().TZd&&a?(Object.assign(c,{"Push-ID":"feeds/loa3rt3fvy5xx7"}),Object.assign(c,{Authorization:"Basic KHJvSjQpYkEkMV4tSmUhYTp0MTE1Vi03cjM0WWRJJWha"}),l$d("dev_upload")&&(Object.assign(c,{"Push-ID":"feeds/bbjvt56ztlogsn"}),Object.assign(c,{Authorization:"Basic clM1NDJKQ0BNJChTVy1wRzpeQihHNzM2WUV5LSljVm8l"}))):b?(Object.assign(c,{"Push-ID":"feeds/adoees42x656aq"}),Object.assign(c,{Authorization:"Basic KSh4Q3MkdjZAN012RF5GODpzVmEwN1JoIV5AOTdCM2FR"}),
l$d("dev_upload")&&(Object.assign(c,{"Push-ID":"feeds/zxkv6m5qbxjibk"}),Object.assign(c,{Authorization:"Basic XktWTCprMil4RDUtN0hXJDo5XjRBNTg5KDh4KjdrLWYh"}))):(Object.assign(c,{"Push-ID":"feeds/kxlwurp47nhro2"}),Object.assign(c,{"X-Tenant-Id":"feedback-image"}),Object.assign(c,{Authorization:"Basic ZmVlZGJhY2staW1hZ2U6dzJ5ODk3RVVqQ1FMMS1K"}),l$d("dev_upload")&&Object.assign(c,{"Push-ID":"feeds/emr3dam5suxspk"}));if(a=_.ila())a=_.xLa(new _.yLa,a),a=_.ALa(a),a=(new _.BLa).setContext(a),a=_.Ad(a.Aa(),
4),Object.assign(c,{"X-Client-Pctx":a});return c}};_.Oe(_.J8d,_.A$d);
_.v();
_.OWc=_.x("zx30Y",[_.zWc,_.Qk]);
_.dC=class extends _.m{constructor(a){super(a)}Ca(){return _.Ri(this,1)}mB(){return _.Tf(this,2)}Pa(){return _.ti(this,2)}oF(){return _.Tf(this,3)}Ma(){return _.Kg(this,4)}Wa(){var a=_.bC();_.Sf(this,5,a)}Mb(){return _.xj(this,5)}Da(){return _.ti(this,5)}hb(){var a=_.cC();_.Sf(this,6,a)}Rb(){return _.xj(this,6)}Ka(){return _.ti(this,6)}Bb(){return _.ti(this,36)}Ha(){return _.Bi(this,8,_.ag())}qca(){return _.Tf(this,9)}Ua(){return _.Di(this,10,_.ag())}Qb(){return _.Ri(this,13)}Cb(){return _.Tf(this,
14)}Va(){return _.xj(this,16)}Fb(){return _.ti(this,16)}Qq(){return _.Si(this,23)}Ba(a){return _.lh(this,23,a)}Ta(){return _.si(this,23)}wb(){return _.Tf(this,24)}Aa(a){return _.Sf(this,24,a)}Na(){return _.ti(this,24)}jy(){return _.p(this,_.OB,25)}};_.dC.prototype.ob="owslKd";
_.DWc=function(a,b){return _.Sf(a,2,b)};_.EWc=function(a,b){return _.Sf(a,3,b)};
_.CWc=_.x("xQIwbc",[]);
_.t("zx30Y");
var tXc,yXc,CXc,uXc,vXc,wXc;
_.sXc=function(a,b,c){const d=a.Wa()||"",e=_.si(a,13)===5||_.si(a,13)===17||_.si(a,13)===18?"MagiGeneralFeedback":"GeneralFeedback";c=_.rWc(_.sWc(new _.aC,2).setAttribute(a.getAttribute()||d||e).Pa(a.hb()||(c==null?void 0:_.nl(c))).Ka(a.Ha()).Ua(_.ti(a,21)).Aa(a.Na()||1).Ma(d).Gd(!0),a.nS()||0).Kp(a.getViewerType()||0);a.wb()&&c.Da(_.qWc(a));_.xj(b,2)?c.Ba(b.mB()):c.Ba("unknown");_.xj(b,3)?c.Ca(b.oF()):c.Ca("Unknown Entity");_.nd(b,23)&&c.Cb(b.Ta());_.xj(b,24)&&c.Bb(b.Na());return c};
_.pC=function(a,b){return a.closest(_.POa(b)).getData(b)};tXc=function(a){const b=new Map;a.split("~;&").forEach(c=>{const [d,...e]=c.split("~:&");d!==""?b.set(d,e.join("~:&")):_.Yd(Error("dh`"+c))});return b};
yXc=function(a,b,c){var d=_.rWc(_.sWc(new _.aC,2).setAttribute("").Pa(_.rl(_.pC(b,"ved"),"")).Ta(_.nXc(_.eh(b)).replace(/\n{3,}/g,"\n\n").trim()).Ka(a.Ha()).Ua(_.ti(a,21)).Aa(a.Na()||1).Ma(a.Wa()||""),a.nS()||0).Kp(a.getViewerType()||0);a.wb()&&d.Da(_.qWc(a));a=_.pC(b,"fbmain");a.Lb()&&(a=uXc(_.BAa(_.rl(a,""))),a.mB()&&d.Ba(a.mB()),a.oF()&&d.Ca(a.oF()),_.Tf(a,7)&&d.Ma(_.Tf(a,7)),_.hC(a)&&d.Aa(_.hC(a)),a.Qq()&&d.Cb(a.Qq()),_.Tf(a,13)&&d.Bb(_.Tf(a,13)),a.jy()&&d.Ka(a.jy()),a.getAttribute()&&d.setAttribute(a.getAttribute()),
a.nS()&&_.rWc(d,a.nS()),a.getViewerType()&&d.Kp(a.getViewerType()));a=_.pC(b,"attrid");a.Lb()&&d.setAttribute(_.nl(a));a=_.pC(b,"rentity");a.Lb()&&d.Fe(_.nl(a));a=_.pC(b,"secids");a.Lb()&&d.Fg(_.nl(a));a=_.pC(b,"docid");a.Lb()&&d.Qv(_.nl(a));a=_.pC(b,"tsourceid");a.Lb()&&d.uf(_.tl(a));a=_.pC(b,"lpage");a.Lb()&&d.Pd(_.nl(a));a=_.pC(b,"lyricid");a.Lb()&&d.Ld(_.nl(a));a=_.pC(b,"entityid");a.Lb()?d.Ba(_.nl(a)):_.xj(c,2)?d.Ba(c.mB()):d.Ba("unknown");a=_.pC(b,"entityname");a.Lb()?d.Ca(_.nl(a)):_.xj(c,3)?
d.Ca(c.oF()):d.Ca("Unknown Entity");_.pC(b,"himg").Lb()&&d.wd(!0);c=_.pC(b,"ftag");c.Lb()&&_.rWc(d,_.tl(c));c=_.pC(b,"ftype");c.Lb()&&d.Aa(_.tl(c));c=_.pC(b,"fpid");c.Lb()&&d.Cb(_.tl(c));c=_.pC(b,"fbkt");c.Lb()&&d.Bb(_.nl(c));if(c=_.rl(_.pC(b,"fbctx"),""))c=_.vWc(c),c=(a=d.Ha())?vXc(a,new _.$Aa(wXc(c))):c,d.Ka(c);(c=_.rl(_.pC(b,"ectx"),""))&&d.Re(c);if(c=_.rl(_.pC(b,"soriId"),""))a=_.FWc(_.xXc(d)),_.Sf(a,1,c);if(c=_.rl(_.pC(b,"fburl"),""))a=_.xXc(d),_.mj(a,9,c);c=_.Yc(_.pC(b,"ons"),0);c>0&&(a=_.xXc(d),
_.lh(a,16,c));if(b=_.rl(_.pC(b,"psd"),""))c=tXc(b),c.size>0&&(b=_.xXc(d),_.vCa(b,8,c));return d};_.zXc=function(){const a=_.so(document.documentElement.cloneNode(!0));a.find("[jsname=uZkjhb]").remove();a.find("[class=gb_s]").remove();return{iRe:a,wIa:window.innerWidth,J4:window.innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight}};
_.AXc=function(a,b=""){if(_.Wi(a,1)===2){var c=a.oF()||"",d=a.getAttribute()||"";a=a.hb()||"";c!==""&&c!=="Unknown Entity"&&d!==""&&a!==""||_.Yd(Error("fh`"+JSON.stringify({entityName:c,attribute:d,visualElement:a})+"`"+b))}};_.BXc=function(a,b){return _.$Oa(_.mXc(a),c=>c.getData(b).Lb()).size()>0};CXc=function(a,b){const c=b?"-1":"0";b?_.jm(a)&&(a.setAttribute("tabindex",c),a.setAttribute("kp-feedback-enabled","true")):a.getAttribute("kp-feedback-enabled")&&(a.setAttribute("tabindex",c),a.removeAttribute("kp-feedback-enabled"))};
_.DXc=function(a){return _.BXc(a,"kefbFhsOptin")};_.xXc=function(a){return _.ei(a,_.OB,19)};uXc=_.Ob(_.QB);vXc=_.ria(_.QUc);wXc=_.Hb(_.QUc);var EXc=new Set(["TABLE","THEAD","TBODY","TFOOT","TR"]),FXc=function(a,b,c){b.find(".gmlSVb").remove();var d=_.pC(b,"attrid").string("")==="images universal";const e=a.pI.Ca();c=(c&&d?a.Ha:d?a.Ma:e?a.Ea:a.Ka).el().cloneNode(!0);_.Af(c,a.getRoot().el());EXc.has(b.el().tagName)&&(b=_.po(b,"TD, TH").first());var f,g,h;let k;if(d=b.Sc("data-report-feedback-about-context")||((f=b.find("[data-report-feedback-about-context]").first()||b.closest("[data-report-feedback-about-context]").first())==null?void 0:
f.Sc("data-report-feedback-about-context"))||b.Sc("aria-label")||((g=b.find("[aria-label]").first())==null?void 0:g.Sc("aria-label"))||_.nXc(b.el(),!0)||((h=b.closest("[aria-label]").first())==null?void 0:h.Sc("aria-label"))||((k=b.find("img[alt]").first())==null?void 0:k.Sc("alt")))f=`${c.getAttribute("aria-label")} ${d}`,c==null||c.setAttribute("aria-label",f);b.el().appendChild(c);a:{f=b;if(!_.xj(a.pI,2)&&!_.xj(a.pI,3)&&(g=_.pC(f,"entityid").string(""),h=_.pC(f,"entityname").string(""),g===""&&
h==="")){a=!0;break a}f=_.pC(f,"attrid").string("");a=f===""?!0:a.pI.Ca()?f.endsWith("sideways")||f==="description"||f==="VisualDigestWebResult"||f==="VisualDigestSocialMediaResult"||f==="VisualDigestVideoResult":!1}a&&b.find(".gmlSVb").hide()},GXc=function(a,b){CXc(a.el(),b);const c=a.el().closest('[role="listitem"] [role="button"],\n      [role="listitem"] [role="link"]');c&&CXc(c,b);_.mo(a.children(),d=>{b?d.el().setAttribute("inert",""):d.el().removeAttribute("inert")})},HXc=function(a,b){if(!a.Aa||
!_.ti(a.pI,9)||_.qWc(a.model.getState())===_.ti(a.pI,9)){var c=_.pC(a.container,"ved");if(!c.Lb()){var d=a.getRoot().closest(_.ho("kp-wholepage-osrp")).first();d&&(c=_.pC(d,"ved"))}d=a.model.getState();c=_.sXc(d,a.pI,c);_.AXc(c,b?"General feedback is passively picked due to no reportable":"General feedback is picked by the end user.");a.model.Vh(c)}},IXc=class extends _.Tr{static Sa(){return{Ot:{Hpa:_.CWc},model:{Nda:_.BWc},jsdata:{pI:_.dC},service:{Tb:_.Gu}}}constructor(a){super(a.Oa);this.oa=null;
this.Ca=this.getData("fhs").Lb()||_.DXc(this.getRoot());this.Aa=_.VWc;this.Yh=this.Ba=null;this.model=a.model.Nda;a.Ot.Hpa&&(this.model=a.Ot.Hpa);this.pI=a.jsdata.pI;this.Tb=a.service.Tb;this.container=_.mXc(this.getRoot());this.Ea=this.Ia("Y4HEvc");this.Ka=this.Ia("TlHsMd");this.Ma=this.Ia("rP5Phe");this.Ha=this.Ia("yW3Mac");this.getRoot().getData("ubs").Lb()&&_.mo(this.container.find(".PZPZlf"),b=>{b.addClass("PZPZlf")});window.MutationObserver&&(this.Yh=new MutationObserver(b=>{const c=[];for(const d of b)for(const e of Array.from(d.addedNodes))e.nodeType===
Node.ELEMENT_NODE&&c.push(e);c.forEach(d=>{d=new _.oo(d);d.hasClass("PZPZlf")?FXc(this,d,!1):_.mo(d.find(".PZPZlf"),e=>{FXc(this,e,!1)})})}))}Da(a){if(_.Wi(a.data,1)===1){if(this.Aa&&_.ti(this.pI,9)&&_.qWc(a.data)!==_.ti(this.pI,9))return;var b=this.container.find(".PZPZlf");b.toArray().length===1?_.mo(b,f=>{GXc(f,!0);FXc(this,f,!0)}):_.mo(b,f=>{GXc(f,!0);FXc(this,f,!1)});this.Yh!=null&&_.mo(this.container,f=>{f.el()&&this.Yh.observe(f.el(),{childList:!0,subtree:!0})});_.mo(this.container,f=>{_.Mf(f.el(),
"u6JqG",{el:f.el()})});_.zp(this.Tb.oa(),this.getRoot().el(),1).log(!0);const e=this.container.find(".PZPZlf .gmlSVb").filter(_.Jm);if(this.Ba===2&&e.size()<=1)this.Ca?this.model.goBack(new _.aC):this.model.Vh(new _.aC,!1,!0);else if(e.size()===0)HXc(this,!0);else if(e.size()===1)e.click();else if(this.oa){var c;let f,g;(c=this.oa)==null||(f=c.find(".gmlSVb"))==null||(g=f.first())==null||g.focus();this.oa=null}else{let f,g;b==null||(f=b.find(".gmlSVb"))==null||(g=f.first())==null||g.focus();var d;
(c=(d=_.mXc(this.getRoot()))==null?void 0:d.el())&&_.Mf(c,"zXxgMc");this.container.addClass("i1eWpb")}}else(d=(b=_.mXc(this.getRoot()))==null?void 0:b.el())&&_.Mf(d,"q0F3r"),this.container.hasClass("i1eWpb")&&(this.container.removeClass("i1eWpb"),_.zp(this.Tb.oa(),this.getRoot().el(),2).log(!0),_.mo(this.container.find(".PZPZlf"),e=>{GXc(e,!1);e.find(".gmlSVb").remove()})),this.container.find(".mWcf0e").focus(),this.Yh&&this.Yh.disconnect();this.Ba=_.Wi(a.data,1)}Ub(){this.Yh&&this.Yh.disconnect();
super.Ub()}Na(a){a.event.preventDefault();_.yp(this.Tb.oa(),this.getRoot().el()).log(!0);this.oa=a=a.targetElement.closest(".PZPZlf");this.getRoot().getData("epu").Lb()&&a.each(c=>{(c.tagName==="IMG"||(new _.lo([c])).find("img").size()>0)&&c.setAttribute("ispicked","")});const b=this.model.getState();a=yXc(b,a,this.pI);_.AXc(a,"A reportable is picked.");this.model.Vh(a)}Pa(){HXc(this,!1)}};IXc.prototype.$wa$A5IKQb=function(){return this.Pa};IXc.prototype.$wa$Yf8WW=function(){return this.Na};
IXc.prototype.$wa$k4Iseb=function(){return this.Ub};IXc.prototype.$wa$dsoI0b=function(){return this.Da};_.Ie.getInstance().register(_.OWc,IXc);
_.v();
_.O$d=_.x("Wo3n8",[_.zWc,_.J8d,_.B$d]);
_.D$d=function(a,b){return _.Hg(a,1,b)};_.E$d=function(a,b){return _.Sf(a,4,b)};_.F$d=function(a,b){return _.Sf(a,5,b)};_.G$d=function(a,b){return _.lj(a,9,b)};_.H$d=function(a,b){return _.lh(a,10,b)};_.I$d=function(a,b){return _.Bb(a,_.OB,11,b)};_.J$d=function(a,b){return _.lh(a,12,b)};_.K$d=function(a,b){return _.Sf(a,13,b)};_.L$d=function(a,b){return _.Sf(a,16,b)};_.M$d=function(a,b){return _.Hg(a,17,b)};
_.N$d=class extends _.m{constructor(a){super(a)}Ta(){return _.Wi(this,1)}Da(){return _.Lg(this,1)}getDescription(){return _.Tf(this,2)}Oh(){return _.ti(this,2)}Ua(){return _.Tf(this,3)}oF(){return _.Tf(this,4)}Na(){return _.ti(this,4)}jJ(){return _.Tf(this,5)}Pa(){return _.ti(this,5)}getAttribute(){return _.Tf(this,6)}setAttribute(a){return _.Sf(this,6,a)}hasAttribute(){return _.xj(this,6)}Ba(){return _.ti(this,6)}Wa(){return _.ti(this,7)}Va(){return _.ti(this,8)}Dfa(){return _.Si(this,10)}jy(){return _.p(this,
_.OB,11)}Ka(){return _.hCa(this,15)}Ma(){return _.$h(this,15)}Qq(){return _.Si(this,12)}Ha(){return _.Tf(this,13)}qca(){return _.Tf(this,16)}Aa(){return _.ti(this,16)}nS(){return _.Wi(this,17)}Ca(){return _.Lg(this,17)}};_.N$d.prototype.ob="L1uh1";
_.U7d=function(a){_.bn(window,"oEdeHf",!1,{LKa:a})};
_.t("Wo3n8");
var mae=function(a,b){return _.ej(a,30,_.aVc,b)},nae=function(a,b){return _.lh(a,28,b)},oae=function(a,b){a.oa=b},pae=[19,20];var qae=function(a,b){return _.mh(a,1,_.H8d,b)},rae=class extends _.m{constructor(a){super(a)}};var uae=function(a,b){if(!b.Aa()||!a.data.Aa()||b.Aa()===a.data.Aa()){sae(a,_.IWc(_.HWc(_.MWc(mae(_.rXc(new _.QB,_.ti(b,18)),_.Pi(b,19,pae)),_.vg(b,_.GWc,20,pae)),_.si(b,12)),_.ti(b,13)));var c=_.q9d(a.getRoot()),d=(new _.dC).Ba(_.si(a.data,12)).Aa(_.ti(a.data,13)),e=_.rl(a.getData("ofbl"),"").split(",").includes(String(b.Ca())),f=void 0;b.Ba()==="survey feedback"&&(f=_.zXc(),f=_.n9d(f,_.ti(b,21)||""));_.y$d(a.Mua,b,d,c,e,f,g=>tae(a,g),a.getData("eau").Lb()).then(()=>{_.Jf(document.body,"aly1V")},
()=>{_.Jf(document.body,"BBnXJ")})}},sae=function(a,b){var c=_.ti(b,27)||null;a.getRoot().setData("proxy",c);if(c){c=_.si(b,12)||0;c=c>0?c.toString():null;const d=_.ti(b,13)||null;a.getRoot().setData("pid",c);a.getRoot().setData("bkt",d);_.Pi(b,30,_.aVc)&&a.getRoot().setData("rootname",_.Pi(b,30,_.aVc)||"");(b=_.vg(b,_.GWc,32,_.aVc))&&_.ti(b,1)&&b.Xg()&&(a.getRoot().setData("fbrtdan",_.ti(b,1)||""),a.getRoot().setData("fbrtdav",b.Xg()||""))}},tae=function(a,b){var c=_.T9d(nae(_.E8d(_.R9d(_.D8d(_.C8d(new _.H8d,
_.ti(a.data,2)),_.ti(a.data,3)).setAttribute(_.ti(a.data,15)),_.Di(a.data,5,_.ag())),_.si(a.data,18)),_.si(a.data,8)),a.data.jy());c=qae(qae(new rae,c),b);c=vae(a.data,_.Lg(a.data,6)).set("kefb",wae(c));const d=_.au().has("aioh"),e=a.getData("aioh").Lb();(d||e)&&c.set("aioh","1");var f;let g;(b=(f=b.jy())==null?void 0:(g=_.M8d(f))==null?void 0:_.ti(g,1))&&c.set("mstk",b);let h;f=(h=a.Wa)!=null?h:a.Pn;a=()=>{};_.Hy(f,{urlParams:c}).then(a,a);return!0},zae=function(a,b){if(b.Aa()!==a.data.Aa()){if(a.data.Aa()!==
"glbl"||a.oa!==b.Aa())a.notify("iiAWKb",new _.aC),_.Jy(a.Pn),a.sJ=!1}else _.Lg(b,11)===3?xae(a,b):yae(a,b)},xae=function(a,b){const c=_.qXc(a.data,b);b=()=>{a.notify("hwO9Gd",c)};a.loadAsync(c).then(b,b)},yae=function(a,b){a.sJ=!0;Aae&&a.model.Da(_.zXc());oae(a.Mua,f=>wae(qae(new rae,f)));const c=_.qXc(a.data.clone(),b);sae(a,c);const d=_.Lg(c,6)||1,e=_.Lg(c,20)||0;b=a.getRoot().getData("cdoc").Lb()||_.Kg(c,26)?"":null;a.getRoot().setData("cdoc",b);b=()=>{var f;let g=_.rWc(_.sWc(new _.aC,1).Da(c.Aa()).Aa(d).Ma(_.ti(c,
7)||""),e).setAttribute(_.ti(c,15)).Pa((f=_.si(c,18))==null?void 0:f.toString()).Ka(c.jy());if((_.Lg(c,6)===5||_.Lg(c,6)===17||_.Lg(c,6)===18||_.Lg(c,6)===23||_.Lg(c,6)===30)&&a.DNa.Mya){f=_.xXc(g);f=_.ei(f,_.L8d,4);var h=[..._.Di(f,14,_.ag())];h=Bae(a,h);f=_.qCa(f,14,h);_.Sf(f,1,a.DNa.Mya)}_.nd(c,8)&&(f=_.xXc(g),h=_.si(c,8),_.lh(f,16,h));_.xj(c,25)&&(f=_.xXc(g),h=_.ti(c,25),_.Sf(f,19,h));_.$h(c,22)&&g.Ua(_.Ad(_.Lh(_.$h(c,22)),4));if(a.Va||_.Kg(c,24))f=_.mXc(a.getRoot()).first(),h=_.pC(f,"ved"),g=
_.sXc(g,_.DWc(_.EWc(new _.dC,_.ti(c,3)),_.ti(c,2)).Ba(_.si(c,12)).Aa(_.ti(c,13)),h).Ta(_.nXc(_.eh(f)).trim().substring(0,1E3));f=a.Ba||_.Kg(c,31)||!1;a.model.Vh(g,!1,f)};a.loadAsync(c).then(b,b)},Bae=function(a,b){a=a.getRoot().closest('[jsname="ZLxsqf"]').kb();if(!a)return[];const c=[];a.querySelectorAll('[jsname="fBMxqf"]').forEach(d=>{(d=d.getAttribute("data-mfiui"))&&!b.includes(d)&&c.push(d)});return c},Cae=function(a,b){let c;(b==null?0:b.Aa())&&((c=a.data)==null?0:c.Aa())&&(b==null?void 0:
b.Aa())!==a.data.Aa()||(a.Ca?a.model.goBack(new _.aC):a.model.Vh(new _.aC,!1),a.sJ&&(_.U7d("fe"),a.sJ=!1))},vae=function(a,b){const c=new Map;c.set("kpfbauth",_.Kg(a,1)===!0?"1":"0");c.set("kpfbverticalid",_.Di(a,5,_.ag()).join(","));_.xj(a,2)&&c.set("kpfbentity",_.ti(a,2)||"");_.xj(a,3)&&c.set("kpfbentityname",_.ti(a,3)||"");_.xj(a,9)&&c.set("kpfbosrpuivertical",_.ti(a,9)||"");_.xj(a,10)&&c.set("hl",a.UK()||"ru");b&&c.set("kpfbftype",b.toString());return c},wae=function(a){a=a.serialize();a=(new TextEncoder).encode(a);
a=(new _.lae(a)).PJa();return _.Ad(a,4)},Dae=class extends _.Tr{static Sa(){return{model:{Nda:_.BWc},Ot:{Hpa:_.CWc},Hf:{aT:_.QB},service:{Mua:_.A$d,DNa:_.C$d},xwa:{Pn:"GkjeIf"}}}constructor(a){super(a.Oa);this.Wa=this.Ya("WKijSd").el();this.Ca=this.getData("fhs").Lb()||_.DXc(this.getRoot());this.Va=this.getData("sps").Lb();this.Aa=0;this.oa=void 0;this.Ba=this.getData("dst").Lb();this.sJ=!1;this.model=a.model.Nda;a.Ot.Hpa&&(this.model=a.Ot.Hpa);let b;this.data=((b=a.Hf)==null?void 0:b.aT)||_.vl(this.getData("maindata"),
_.QB);this.Mua=a.service.Mua;this.DNa=a.service.DNa;this.Pn=a.xwa.Pn;this.initialize()}initialize(){var a=this.model.getState();a.Fb()&&_.qWc(a)===this.data.Aa()?(_.AXc(a,"Restore state on page refresh"),a=()=>{this.model.Aa()},this.loadAsync(this.data).then(a,a)):_.Fi(this.data,5)!==1||_.Ei(this.data,5,0)!=="SHOPPING"||_.Aj(this.data,6)&&_.hC(this.data)!==1&&_.hC(this.data)!==0||_.iC(this.data,4)}Ua(a){a=a.data?_.Nb(_.N$d,a.data):new _.N$d;uae(this,a)}Da(a){uae(this,a.data)}Ta(a){return tae(this,
a.data)}Ma(a){a=a.data?_.Nb(_.QB,a.data):new _.QB;zae(this,a)}Ka(a){zae(this,a.data)}Ha(a){a=a.data?_.Nb(_.QB,a.data):new _.QB;Cae(this,a)}Ea(a){Cae(this,a.data)}Na(){this.getRoot().toggleClass("OvsyId",!1);_.U7d("do")}Pa(){this.getRoot().toggleClass("OvsyId",!0);_.U7d("dc");_.U7d("fe");this.sJ=!1}loadAsync(a){const b=_.Lg(a,6)||1,c=vae(a,b),d=_.ti(a,27);let e;const f=this.Aa!==b||d&&this.oa!==d||((e=_.Kg(a,29))!=null?e:!1)||_.Lg(a,20)===114;let g,h;if(((g=a.jy())==null?0:(h=_.M8d(g))==null?0:_.A(h,
1))&&_.Lg(a,20)===114){let k,l;c.set("mstk",((k=a.jy())==null?void 0:(l=_.M8d(k))==null?void 0:_.A(l,1))||"")}if(f)return this.Aa=b,this.oa=d,_.Hy(this.Pn,{urlParams:c});this.Aa=b;this.oa=d;return _.ryc(this.Pn,{urlParams:c})}};Dae.prototype.$wa$KyxjCd=function(){return this.Pa};Dae.prototype.$wa$CqUGrf=function(){return this.Na};Dae.prototype.$wa$hRwSgb=function(){return this.Ea};Dae.prototype.$wa$s5CUif=function(){return this.Ha};Dae.prototype.$wa$MlP2je=function(){return this.Ka};
Dae.prototype.$wa$FbhRG=function(){return this.Ma};Dae.prototype.$wa$naa5ve=function(){return this.Ta};Dae.prototype.$wa$UhDUnd=function(){return this.Da};Dae.prototype.$wa$KGQHJd=function(){return this.Ua};var Aae=_.YWc;_.Ie.getInstance().register(_.O$d,Dae);

_.v();
_.y2s=_.x("T5VV",[]);
_.t("T5VV");
var z2s=function(a){switch(a){case 0:return"BLUR";case 4:return"OFF";case 1:case 2:case 3:return"FILTER";default:return"UNKNOWN"}},A2s=class extends _.Tr{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.Yc(this.getData("ssc"),-1);this.Aa=_.Qg(this.getData("ssl"),!1);this.Ba=_.rl(this.getData("ssor"),"");typeof window.google!=="undefined"&&(window.google.sss=z2s(this.oa),window.google.sso=this.Aa,window.google.ssor=this.Ba)}};_.Ie.getInstance().register(_.y2s,A2s);
_.v();
_.yMq=_.x("aDVF7",[]);
_.t("aDVF7");
var zMq=class extends _.Tr{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.rl(this.getData("len"),"");typeof window.google!=="undefined"&&(a=this.oa.slice(-1),window.google.len=a===","?this.oa.slice(0,-1):this.oa)}};_.Ie.getInstance().register(_.yMq,zMq);
_.v();
_.qcC=_.x("rhYw1b",[]);
_.t("rhYw1b");
var DME=class extends _.Tr{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.rl(this.getData("dmd"),"");this.deviceType=_.rl(this.getData("dvt"),"");a=_.Y0(1);const b=_.Y0(0);a=Math.max(a,b);this.Ba=a<=800?"xs":a<=1E3?"s":a<=1300?"m":a<=2E3?"l":"xl";this.Aa=_.Qg(this.getData("iscsc"),!1);typeof window.google!=="undefined"&&(window.google.dvs=this.Ba,window.google.dmd=this.oa,window.google.dvt=this.deviceType,this.Aa&&(window.google.iscsc="1"))}};_.Ie.getInstance().register(_.qcC,DME);
_.v();
_.t("M6QgBb");

_.v();
_.t("wV5Pjc");
_.tFb={name:"iss"};_.Hu=new _.Me(_.br);
_.v();
var bqe;bqe=function(a){var b=a.target;if(b.tagName==="IMG"){var c;a=(c=_.qua(a))!=null?c:_.rua.now();b.setAttribute("data-ilt",Math.floor(a+_.gg).toString());c=b["data-ilc"];b["data-ilc"]=void 0;if(c)for(b=0;b<c.length;b++)c[b]()}};_.dqe=function(){if(google.iml)return!1;const a=document.documentElement;a.addEventListener("load",bqe,cqe);a.addEventListener("error",bqe,cqe);google.iml={de:a,gol:bqe,o:cqe};return!0};var cqe={capture:!0,passive:!0};
_.$pe=_.x("EO13pd",[_.hr,_.Tq,_.a0a,_.b0a,_.br]);
_.Ype=class extends _.m{constructor(a){super(a)}};_.Zpe=class extends _.m{constructor(a){super(a)}getInteractionVed(){return _.A(this,4)}};
_.Upe=function(a){_.bn(window,"attn_viewer_open",!1,a)};_.Vpe=function(){_.bn(window,"attn_viewer_close",!1,null)};
_.t("EO13pd");
var eqe,fqe,gqe,hqe,iqe,jqe,mqe,nqe,oqe,pqe,qqe,rqe,sqe,tqe,uqe,vqe,wqe,xqe,yqe,zqe,Aqe,Cqe,Dqe,Eqe,Gqe,Kqe,Fqe,Hqe,Lqe,Iqe,Jqe;eqe=class extends _.m{constructor(a){super(a)}};fqe=class extends _.m{constructor(a){super(a)}xX(){return _.A(this,1)}};gqe=class extends _.m{constructor(a){super(a)}};hqe=class extends _.m{constructor(a){super(a)}};iqe=class extends _.m{constructor(a){super(a)}Aa(a){return _.Sf(this,1,a)}};jqe=[1,2,3,4];_.kqe=function(a,b){return _.Jg(a,1,b)};_.lqe=class extends _.m{constructor(a){super(a)}};
mqe=function(a,b){_.Bb(a,eqe,10,b)};nqe=function(a,b){return _.Bb(a,_.Nz,14,b)};oqe=function(a,b){return _.Bb(a,_.Ez,1,b)};pqe=class extends _.m{constructor(a){super(a)}lz(){return _.p(this,_.Ez,1)}};qqe=function(a){var b=new pqe;return _.Bb(b,_.Ez,1,a)};rqe=function(a,b){return _.Jg(a,2,b)};sqe=function(a,b){return _.Sf(a,3,b)};tqe=function(a,b){return _.Bb(a,_.yz,4,b)};uqe=function(a,b){_.Bb(a,_.wG,2,b)};vqe=function(a,b){_.Bb(a,eqe,3,b)};
wqe=class extends _.m{constructor(a){super(a)}Fca(){return _.$f(this,_.nG,1,_.ag())}};xqe=function(a,b){return _.Bb(a,_.Nz,1,b)};yqe=class extends _.m{constructor(a){super(a)}};zqe=function(a,b){return _.ji(a,14,_.Ooe,b)};Aqe=function(a,b){return _.ji(a,16,_.Ooe,b)};_.Bqe=function(a,b){return _.ji(a,17,_.Ooe,b)};Cqe=function(a){var b=new _.Poe;return _.ji(b,18,_.Ooe,a)};Dqe=_.Ob(_.Ype);Eqe=_.Ob(_.Zpe);
Gqe=function(a){_.hg(a,{preload:{H6f:_.Tpe}});const b=a.Ab("J7OdWb").el();b.ephUSe=()=>{a.Cfc=!1};_.Lv([new _.Nn(b,"insert")],{triggerElement:b});_.Hy(b,a.dLa()).then(c=>{a.jbb=!0;a.Cfc=c}).catch(c=>{a.Cfc=!1;(_.sma(c)||_.tma(c))&&Fqe(a);throw c;})};Kqe=function(a,b){b.subscribe(_.Poe.prototype.Ca,(c,d)=>Hqe(a,c,d)).subscribe(_.Poe.prototype.Ba,c=>Iqe(c)).subscribe(_.Poe.prototype.Aa,c=>Jqe(c))};Fqe=function(a){_.Zm(window,"pageshow",b=>{b.persisted&&!a.jbb&&Gqe(a)})};
Hqe=async function(a,b,c){try{_.y(await _.y(new Promise(google.dclc)));const d=a.cFd.find(g=>g.tnb.Aa().some(h=>_.Sne(h)===_.A(b,1))),e=new wqe;let f;((f=a.config)==null?0:_.Oh(f,eqe,123))&&vqe(e,_.p(a.config,eqe,123));if(d)uqe(_.Bb(e,_.Nz,4,d.tnb),d.Pcc),_.ji(c,11,_.Ooe,e);else{const g=(new _.Zt(a.history.getCurrentUrl(),{sXa:_.fLa})).oa.get("vssid")||"",h=_.y(await _.y(a.AKd.promise))(g);h&&(_.Bb(e,_.Nz,4,h),_.ji(c,11,_.Ooe,e))}}finally{_.y()}};
Lqe=function(a,b,c,d,e,f,g,h){var k=new _.Koe;g=_.xg(k,8,g);g=_.xg(g,16,_.gg);e=e!=null?e:b==null?void 0:_.si(b,19);e=_.lh(g,12,e);b&&_.Bb(e,_.wG,6,b);c&&_.Sf(e,7,c);d!=null&&_.Sf(e,17,d);f!=null&&_.lh(e,18,f);a.config&&_.Oh(a.config,eqe,123)&&mqe(e,_.p(a.config,eqe,123));h&&_.Sf(e,13,h);return e};
Iqe=async function(a){_.Qh(a,gqe,1,jqe)?_.Eq():_.Qh(a,fqe,2,jqe)?(a=_.vg(a,fqe,2,jqe),_.bn(window,"attn_dom_immersive",!1,new _.aqe(a.xX(),_.z(a,2)))):_.Qh(a,iqe,3,jqe)?(a=_.vg(a,iqe,3,jqe),a=_.A(a,1),_.Upe(a)):_.Qh(a,hqe,4,jqe)&&_.Vpe()};Jqe=async function(a){_.Mf(document.body,"xHsTDe",{unb:_.A(a,1)})};
_.Mqe=class extends _.Tr{static Sa(){return{service:{history:_.zG,navigation:_.Sz,Yob:_.Goe,y$a:_.Hoe,window:_.Hu}}}constructor(a){super(a.Oa);this.jbb=!1;this.config=this.Z1=null;this.cFd=[];this.Cfc=!0;this.AKd=new _.fh;this.history=a.service.history;this.kc=a.service.navigation;this.Yob=a.service.Yob;var b=this.y$a=a.service.y$a;b.oa.push(this);b.Aa!=null&&(b.Aa.resolve(this),b.Aa=null);this.B2();this.document=a.service.window.getDocument()}Ub(){var a=this.y$a;const b=a.oa.indexOf(this);b>=0&&
a.oa.splice(b,1);super.Ub()}Rqe(a){a=Dqe(a.data);this.initialize(_.p(a,_.Pz,1),_.p(a,_.Nz,2),_.p(a,_.wG,3))}VQb(){if(!this.Z1){var a=_.Doe;a.Aj.oa.sJ()&&_.Do(a.Aj,"uvpbs");this.init();_.dqe();this.rwd()}}initialize(a,b,c){this.config=a;this.cFd.push({tnb:b,Pcc:c});this.VQb()}init(){Gqe(this);if(this.Z1=_.Toe())Kqe(this,this.Z1),this.Z1.initialize(_.ela())}zNe(a){this.AKd.resolve(a)}dLa(){return{aU:!0,aOa:()=>{this.dirty()}}}rwd(){this.Z1&&this.Z1.Aa&&this.Z1.Aa.then(()=>{var a=_.Doe;a.Aj.oa.sJ()&&
(_.Do(a.Aj,"uvpbe"),a.Aj.log())})}async rwb(a,b,c,d,e,f,g,h,k){try{let l;if(_.OSd&&((l=google)==null?0:l.zl)&&google.zl.qvoc)return google.zl.qvoc=!1,Promise.resolve();const n=Math.round(h);this.Yob.Oc(n);const q=a.Aa()[a.Ji()],r=q==null?void 0:_.ii(q,_.mu,1,_.HLc).getViewerType();r!==25&&r!==47&&(_.Spe.oa._guestSettings={fetchPriority:"high"});this.Hrb();if(!this.Z1||!this.Cfc)return Promise.resolve().then(()=>{var B=b==null?void 0:_.Si(b,19),G=this.kc,L=_.Gn(new _.yn(this.history.getCurrentUrl()),
"q")||"";(B=_.Xpe(q,L,d,B||null))&&G.navigateTo(B)});if(!q)return _.Yd(Error("Zm")),Promise.resolve();const u=nqe(Lqe(this,b,d,e,f,g,n,k),a);if(c==null?0:_.Oh(c,eqe,123))mqe(u,_.p(c,eqe,123));else{let B;((B=this.config)==null?0:_.Oh(B,eqe,123))&&mqe(u,_.p(this.config,eqe,123))}_.y(await _.y(this.Klc(u,q,d,b)));this.document.dispatchEvent(new CustomEvent("viewerOpenEventHandled"))}finally{_.y()}}async Klc(a,b,c,d){this.Hrb();return this.Z1?this.Z1.sendMessage((new _.Poe).Klc(a),!0).catch(e=>{_.Yd(Error("an`"+
e.message));var f=d==null?void 0:_.Si(d,19);e=this.kc;var g=_.Gn(new _.yn(this.history.getCurrentUrl()),"q")||"";(f=_.Xpe(b,g,c,f||null))&&e.navigateTo(f)}):(a=Error("$m"),_.Yd(a),Promise.reject(a))}jle(a){a=Eqe(a.data);this.rwb(_.p(a,_.Nz,1),_.p(a,_.wG,2)||null,null,_.A(a,3)||null,a.getInteractionVed()||null,_.sd(a,5)||null,null,_.wi(a,6),_.A(a,7)||null)}async lle(a){a=a.data;const b=a.params.qo;if(!b)return _.Yd(Error("bn")),Promise.resolve();b==null||_.ii(b,_.mu,1,_.HLc).getViewerType();var c;
const d=tqe(sqe(rqe(qqe(b),a.Aa),(c=a.oa)==null?void 0:c.id),a.params.uc);b.OV();this.Hrb();return this.Z1?await this.Z1.sendMessage(Cqe(d)).catch(e=>{_.Yd(Error("cn`"+e.message))}):(c=Error("$m"),_.Yd(c),Promise.reject(c))}async XHc(a){try{this.Z1&&_.y(await _.y(this.Z1.sendMessage(_.Bqe(new _.Poe,_.kqe(new _.lqe,!!a.data))).catch(b=>{_.Yd(Error("dn`"+b.message))})))}finally{_.y()}}sob(a){this.Hrb();return this.Z1?this.Z1.sendMessage(zqe(new _.Poe,xqe(new yqe,a))).catch(b=>{_.Yd(Error("en`"+b.message))}):
(a=Error("$m"),_.Yd(a),Promise.reject(a))}bIc(a){this.Hrb();return this.Z1?this.Z1.sendMessage(Aqe(new _.Poe,oqe(new _.Loe,a))).catch(b=>{_.Yd(Error("fn`"+b.message))}):(a=Error("$m"),_.Yd(a),Promise.reject(a))}Hrb(){this.Z1||(_.Yd(Error("gn"),{level:2}),this.VQb())}B2(){}};_.Mqe.prototype.$wa$npAYtf=function(){return this.B2};_.Mqe.prototype.$wa$Nj7Yd=function(){return this.Hrb};_.Mqe.prototype.$wa$A1kDjc=function(){return this.XHc};_.Mqe.prototype.$wa$gj6b3c=function(){return this.lle};
_.Mqe.prototype.$wa$dwOkab=function(){return this.jle};_.Mqe.prototype.$wa$NMQPwb=function(){return this.rwd};_.Mqe.prototype.$wa$fjjfVb=function(){return this.VQb};_.Mqe.prototype.$wa$f0xwYb=function(){return this.Rqe};_.Mqe.prototype.$wa$k4Iseb=function(){return this.Ub};_.Ie.getInstance().register(_.$pe,_.Mqe);
var Nqe=function(a,b,c){a=new _.En(_.dl(a.url));b=!!a.get("imgrc")&&a.get("imgrc")!=="_";if(a.get("vhid")||b){b=!!a.get("oshop");var d=!!a.get("epd");if(b||d)if(c.userInitiated)a.remove("oshop"),a.remove("oshopproduct"),a.remove("epd"),c=new _.yn(this.history.getCurrentUrl()),_.Dn(c,a.toString()),this.history.oa(c.toString());else try{const e=_.kqe(new _.lqe,!0);this.Z1.sendMessage(_.Bqe(new _.Poe,e))}catch(e){this.Z1.sendMessage((new _.Poe).Klc(new _.Koe))}}};_.Mqe.prototype.B2=function(){this.history.addListener(Nqe.bind(this))};
_.Mqe.prototype.$wa$npAYtf=function(){return this.B2};

_.v();
_.PcC=_.x("NmZKpe",[_.Iq]);
_.t("NmZKpe");
var UME=class extends _.Tr{static Sa(){return{service:{location:_.cv}}}constructor(a){super(a.Oa);this.Cc=a.service.location;(new _.Zt(this.Cc.location.hash)).oa.has("sv")&&_.Ne(_.j0a,this.An())}};_.Ie.getInstance().register(_.PcC,UME);
_.v();
_.SCq=_.x("I9y8sd",[]);
_.t("I9y8sd");
var TCq=function(){return google.ht&&google.ht<Date.now()&&!google.fuht?!0:!1},UCq=function(a){a=getComputedStyle(a);if(a.display==="none")return"display: none";if(Number(a.opacity)<.5)return`opacity: ${a.opacity}`;if(a.visibility==="hidden")return"visibility: hidden"},VCq=function(a,b,c,d,{logError:e}){d=_.Vd(d);b=`${b}-${c}-${_.pma(d)}`;const f=a.get(b),g=_.Wd(d,"am");if(g){if(f){if(g===f)return;let h=`k=${_.pma(d)}`;(d=_.Wd(d,"ck"))&&(h=`${h}.ck=${d}`);e(Error("Iv`"+JSON.stringify({type:c,v1f:h,
EZf:f,lZf:g})))}a.set(b,g)}},XCq=function(a){if(a.toggle){var b;a.sampleRate=(b=a.sampleRate)!=null?b:.01;WCq.push(a)}},YCq={name:"umods"},ZCq=!!(_.uh[20]&1024),$Cq=!!(_.uh[20]&2048),aDq=!!(_.uh[20]&4096),bDq=!!(_.uh[20]&8192),cDq=!!(_.uh[20]>>14&1),dDq=!!(_.uh[20]>>15&1),eDq=!!(_.uh[20]>>16&1);var fDq=["google.com","youtube.com","ampproject.org",(new URL(location.href)).host];var WCq=[],gDq=[],hDq=class extends _.Tr{static Sa(){return{}}constructor(a){super(a.Oa);this.Ca=Math.random();this.Aa=!1;this.logError=this.logError.bind(this);window.addEventListener("pagehide",()=>{this.Aa=!0});window.addEventListener("pageshow",()=>{this.Aa=!1});google.sx(null,()=>{(0,_.Tn)(()=>{this.Ba()},2E3)})}Ba(){if(!this.Aa)for(const a of WCq)this.sample(a,()=>{a.run({logError:(b,c={})=>{this.logError(a.name,b,c)}})})}logError(a,b,c={}){if(!this.oa){this.oa={};for(const d of gDq)this.sample(d,
()=>{const e=d.run();e&&(this.oa=Object.assign({},this.oa,e))})}_.Yd(b,{level:0,zf:Object.assign({},{src:"bad_srp_detection"},c,this.oa)});$Cq&&navigator.sendBeacon(`/gen_204?atyp=i&bsf=${a}.1&ei=${(0,_.wl.Tw)()}`,"")}sample(a,b){((a.B1f?Math.random():this.Ca)<(a.sampleRate||0)||ZCq)&&b()}};hDq.prototype.$wa$rT3LBf=function(){return this.Ba};
XCq({name:"fi",run:function({logError:a}){const b={},c=Array.from(document.querySelectorAll("iframe")).map(d=>{try{return d.src&&d.src.length!==0?(new URL(d.src)).hostname:void 0}catch(e){return e.toString()}}).filter(d=>{if(!d)return!1;d=d.split(".");for(const e of fDq)if(d.slice(-1*e.split(".").length).join(".").toLowerCase()===e)return!1;return!0});if(c.length){b.count=String(c.length);for(let d=0;d<Math.min(c.length,3);d++)b[`iframe_${d+1}`]=c[d];a(Error("Jv"),b)}},toggle:bDq});
XCq({name:"hp",run:function({logError:a}){if(!TCq()){for(var b=document.elementFromPoint(window.innerWidth/2,window.innerHeight/2),c=[];b;)c.unshift(b),b=b.parentElement;for(const d of c){if(d.offsetWidth<window.innerWidth*.6||d.offsetHeight<200)break;const e=UCq(d);if(e){const f=d;(0,_.Tn)(()=>{e===UCq(f)&&a(Error("Kv"),{hiddenProperty:e,id:f.id,tagName:f.tagName,classes:f.classList.value,styles:f.getAttribute("style")||""})},1E3);break}}}},toggle:aDq});
XCq({name:"sp",run:function({logError:a}){var b;if(b=!TCq())b=document.body.querySelector("[jsname=KG3hVc]"),b=!(b&&window.getComputedStyle(b).display!=="none");if(b){b=document.body.clientHeight;var c,d=((c=document.getElementById("rcnt")||document.getElementById("center_col"))==null?void 0:c.clientHeight)||0;(b<400||d<100)&&a(Error("Lv"),{pageHeight:String(b),resultsHeight:String(d)})}},toggle:aDq});XCq({name:"qm",run:function({logError:a}){document.compatMode==="BackCompat"&&a(Error("Mv"))},toggle:cDq});
XCq({name:"um",run:function({logError:a}){var b=google.erd;if(b){var c=b.bv;if(c&&(b=b.dpf)){var d,e=(d=navigator)==null?void 0:d.userAgent;if(e){d=_.mf("s",YCq);c=`${c}-${b}-${e}`;var f;(b=(f=google.xjs)==null?void 0:f.basejs)&&VCq(d,c,"jsurl",b,{logError:a});var g;(f=(g=google.xjs)==null?void 0:g.basecss)&&VCq(d,c,"cssurl",f,{logError:a});var h;(g=(h=google.xjs)==null?void 0:h.basecomb)&&VCq(d,c,"comburl",g,{logError:a})}}}},toggle:eDq});
var iDq={name:"nn",run:function(){var a=document.querySelectorAll("script:not([nonce])");if(a.length!==0){var b={nonce_count:String(a.length)},c=0;for(const d of a){a=d.src;let e;if((e=a)==null?0:e.startsWith("https://www.gstatic.com/"))return;if(c++>3)break;let f;const g=(f=d.textContent)==null?void 0:f.substring(0,300);g&&(b[`nonce_script_${c}`]=g);a&&(b[`nonce_src_${c}`]=a)}return b}},toggle:dDq};if(iDq.toggle){var jDq;iDq.sampleRate=(jDq=iDq.sampleRate)!=null?jDq:1;gDq.push(iDq)}
_.Ie.getInstance().register(_.SCq,hDq);
_.v();
_.t("xBbsrc");
_.vBp=new _.Me(_.M4a);
_.v();
_.BBp=_.x("DLOxie",[_.M4a,_.Iq]);
_.t("DLOxie");
var CBp=function(a){try{const b=_.OC(a);return b.hostname!=null&&b.hostname.endsWith(".search.translate.goog")}catch(b){return!1}},DBp=RegExp("^(.+)[.]([a-zA-Z]+)2([a-zA-Z]+)[.]search[.]translate[.]goog");var EBp={childList:!0,subtree:!0,attributes:!0,attributeFilter:["href"]},IBp=function(a,b){if(CBp(b.href))try{var c=b.href;if(!CBp(c))throw Error("bu`"+c);const e=_.OC(c),f=e.hostname.match(DBp);if(!f||f.length!==4)throw Error("cu`"+c);const g=f[1],h=f[2],k=f[3];if(h.length!==2||!/^[a-zA-Z]+$/.test(h))throw Error("du`"+c);if(k.length!==2||!/^[a-zA-Z]+$/.test(k))throw Error("eu`"+c);var d={uha:_.Z2c({hostname:g},e).href,Y6:h,q4:k};_.Pf().Hc("toledo_url",b.href).log();_.Ac(b,d.uha)}catch(e){}(a.Aa||
a.Ca)&&(d=FBp(a,b))&&(GBp(a,b,d)||HBp(b,d))},FBp=function(a,b){if(!b.href)return null;let c,d;try{b=c=_.OC(b.href);let f=!1;if((b.hostname==="google.com"||b.hostname==="www.google.com"||b.hostname===a.Cc.location.hostname)&&b.pathname==="/url"){f=!0;var e=_.PC(b);e.has("q")?b=_.OC(e.get("q")):e.has("url")&&(b=_.OC(e.get("url")))}({url:c,Ayb:d}={url:b,Ayb:f})}catch(f){return null}if(c.hostname!=="translate.google.com"||c.pathname!=="/translate")return null;a=_.PC(c);if(!a.has("u")||!a.has("tl")||!a.has("sl"))return null;
e=a.get("u");e+=c.hash!=="#"?c.hash:"";return{Ayb:d,p0b:c.href,V9a:e,B_b:a.get("tl"),iZa:a.get("sl")}},GBp=function(a,b,c){if(!a.oa.isAvailable())return!1;_.Ac(b,c.V9a);b.addEventListener("click",d=>{d.preventDefault();_.Mv(b,{userAction:3,data:{url:c.p0b}});a.oa.oa(c.V9a,c.B_b,c.iZa,_.Vc())});return!0},HBp=function(a,b){HTMLAnchorElement.prototype.hasOwnProperty("hrefTranslate")&&(_.Ac(a,b.V9a),a.setAttribute("hrefTranslate",b.B_b),b.Ayb&&a.addEventListener("click",async()=>{try{_.y(await _.y(_.Mv(a,
{userAction:3,data:{url:b.p0b}})))}finally{_.y()}}))},JBp=class extends _.Tr{static Sa(){return{service:{vk:_.vBp,Cc:_.cv}}}constructor(a){super(a.Oa);this.Yh=null;this.Ba=b=>{for(const c of b)c.type==="childList"?c.addedNodes.forEach(d=>{d.nodeType===Node.ELEMENT_NODE&&(d.matches("a")&&IBp(this,d),d instanceof Element&&d.querySelectorAll("a").forEach(e=>{IBp(this,e)}))}):c.type==="attributes"&&c.attributeName==="href"&&c.target.matches("a")&&IBp(this,c.target)};this.oa=a.service.vk;this.Cc=a.service.Cc;
this.Yh=new MutationObserver(this.Ba);this.Aa=this.getData("cte").Lb();this.Ca=this.getData("ste").Lb()}Td(){document.documentElement.querySelectorAll("a").forEach(a=>{IBp(this,a)});this.Yh.observe(document.body,EBp)}ud(){super.ud();this.Yh&&this.Yh.disconnect()}};JBp.prototype.$wa$mU5qzf=function(){return this.ud};JBp.prototype.$wa$npT2md=function(){return this.Td};_.Ie.getInstance().register(_.BBp,JBp);
_.v();
});
// Google Inc.
