"use strict";loaded_1_7(function(_){var window=this;
_.k("d6FVZd");

_.l();
_.k("yb08jf");
var DMc,FMc;DMc=function(a,b,c){const d=a.Aa++;if(a.Qg===void 0)return d;b=b instanceof _.qp?b.toArray():[b];a.oa.push({key:d,elements:b,callback:c});b.forEach(e=>{a.Qg.observe(e)});return d};_.EMc=function(a,b){if(a.Qg!==void 0){var c=a.oa.filter(d=>d.key===b).flatMap(d=>d.elements);a.oa=a.oa.filter(d=>d.key!==b);c.filter(d=>!a.oa.flatMap(e=>e.elements).includes(d)).forEach(d=>{a.Qg.unobserve(d)})}};
FMc=class{constructor(){this.oa=[];this.Aa=1;const a=window;this.Qg=a.ResizeObserver===void 0?void 0:new a.ResizeObserver(b=>{this.Ea(b)})}pause(){this.Qg!==void 0&&this.Qg.disconnect()}resume(){this.Qg!==void 0&&this.oa.flatMap(a=>a.elements).forEach(a=>{this.Qg.observe(a)})}isSupported(){return this.Qg!==void 0}Ea(a){this.oa.forEach(b=>{const c=a.filter(d=>b.elements.includes(d.target));c.length>0&&b.callback(c)})}};_.GMc=function(a,b,c){return DMc(a.Qg,b,c)};_.pG=class{constructor(){this.Qg=new FMc}pause(){this.Qg.pause()}resume(){this.Qg.resume()}isSupported(){return this.Qg.isSupported()}};
_.Hh(_.pG,_.eq);
_.l();
_.k("hypYI");
_.fJd=class extends _.At{static Za(){return{service:{window:_.jv}}}constructor(a){super();this.window=a.service.window.get();this.document=a.service.window.getDocument()}oa(){return this.document.documentElement.clientWidth/this.window.innerWidth}};_.Gh(_.H8a,_.fJd);
_.l();
var IMc;IMc=_.gh().getDocument().documentElement;_.HMc=IMc.requestFullscreen?"fullscreenchange":IMc.webkitRequestFullscreen?"webkitfullscreenchange":IMc.mozRequestFullScreen?"mozfullscreenchange":IMc.msRequestFullscreen?"MSFullscreenChange":"fullscreenchange";
_.JMc=function(a){a=a?a.getDocument():_.gh().getDocument();const b=a.body;return!!(b.webkitRequestFullscreen&&a.webkitFullscreenEnabled||b.mozRequestFullScreen&&a.mozFullScreenEnabled||b.msRequestFullscreen&&a.msFullscreenEnabled||b.requestFullscreen&&a.fullscreenEnabled)};_.KMc=function(a,b){if(a.requestFullscreen)return a.requestFullscreen(b);if(a.webkitRequestFullscreen)return a.webkitRequestFullscreen();if(a.mozRequestFullScreen)return a.mozRequestFullScreen();if(a.msRequestFullscreen)return a.msRequestFullscreen()};
_.LMc=function(a){a=a?a.getDocument():_.gh().getDocument();a.exitFullscreen?a.exitFullscreen():a.webkitCancelFullScreen?a.webkitCancelFullScreen():a.mozCancelFullScreen?a.mozCancelFullScreen():a.msExitFullscreen&&a.msExitFullscreen()};_.MMc=function(a){a=a?a.getDocument():_.gh().getDocument();return!!(a.webkitIsFullScreen||a.mozFullScreen||a.msFullscreenElement||a.fullscreenElement)};
_.k("yGkNuf");
var NMc,QMc,XMc,YMc,ZMc,$Mc;NMc=function(a,b=0){return{Ol:a,Bm:b}};_.OMc=function(){return!1};_.PMc=function(a){return a.Na?a.Na.querySelector("[jsname=Ehk02]")||null:null};_.RMc=function(a){return a.Sa?(a=QMc(a.Sa.XP(),_.Vt),a?(a=QMc(a,_.uD))?_.kpc(a.Gb().getExtension(_.uD))||null:null:null):null};_.SMc=function(){return!1};_.TMc=function(){return!1};_.UMc=function(){};_.VMc=function(){};_.WMc=function(){};
QMc=function(a,b){let c;a=(a==null?void 0:(c=a.uf())==null?void 0:_.Dh(c))||[];for(const d of a){let e;if((e=d.Gb())==null?0:e.hasExtension(b))return d}};_.qG=function(a,b,c){a.isInitialized()&&_.$e(a.oa,b,c)};XMc=function(a){(a=_.KMc(a,{navigationUI:"hide"}))&&a.catch(()=>{})};YMc=function(a){var b=_.PMc(a);b&&(!(b=b.getBoundingClientRect())||b.width<=0||(b=b.top,a.Oq()&&b<52&&(b=52),a.oa.style.top=`${b}px`,a.Oq()||_.SMc()||(a.oa.style.clipPath=`inset(${52-b}px 0 0 0)`)))};
ZMc=function(a){!a.Ga&&a.oa&&(a.Ga=a.oa.querySelector("[jsname=yxspve]"));a.Ga||(a.Ga=a.Aa.document.body.querySelector("[jsname=yxspve]"));return a.Ga};
_.aNc=function(a){if(a.isInitialized()){var b=_.PMc(a);if(b){var c,d=(c=_.RMc(a))==null?void 0:c.Ds();if(d){document.addEventListener("visibilitychange",a.yb);a.Ea.addEventListener?a.Ea.addEventListener("change",a.La):a.Ea.addListener&&a.Ea.addListener(a.La);_.SMc()&&a.Aa.addEventListener("resize",a.D9);c=$Mc(a);var e=b.getElementsByTagName("img")[0];c<=1&&e&&(e.style.display="none");e=_.yp(b);let g;e=(e==null?void 0:(g=e.getData("ved"))==null?void 0:_.Io(g))||null;_.qG(a,"znUj3",{Ol:{id:d||void 0,
aspectRatio:c},HZ:e||""});var f;_.qG(a,"KZOHMb",NMc({id:d||void 0,aspectRatio:c},_.fu((f=_.RMc(a))==null?void 0:_.Sg(f,3))||a.Fb||0));a.oa.style.display="block";a.oa.style.height="";a.oa.style.position="fixed";a.oa.style.top=`${b.getBoundingClientRect().top}px`;a.oa.style.left=`${b.getBoundingClientRect().left}px`;a.oa.style.width=`${b.getBoundingClientRect().width}px`;a.oa.style.height=`${b.getBoundingClientRect().height}px`;a.oa.style.zIndex="1030"}}}};
_.bNc=function(a){if(a.isInitialized()){var b=_.PMc(a);b&&(b.style.height="220px");document.removeEventListener("visibilitychange",a.yb);a.Ea.removeEventListener?a.Ea.removeEventListener("change",a.La):a.Ea.removeListener&&a.Ea.removeListener(a.La);_.SMc()&&a.Aa.removeEventListener("resize",a.D9);_.EMc(a.Ix.Qg,a.Ya);a.Ya=0;_.qG(a,"jQntwf");_.qG(a,"iPWSJb");a.Xa&&(_.$e(a.Xa,"jQntwf"),a.Xa=null);a.oa.style.display="none";a.oa.style.removeProperty("clip-path")}};
$Mc=function(a){let b;return(a=(b=_.RMc(a))==null?void 0:b.rk())?a:1.778};
_.rG=class extends _.At{static Za(){return{service:{Ix:_.pG,fq:_.vw,window:_.jv}}}constructor(a){super();this.Ya=0;this.ob=null;this.Sa=void 0;this.Kb=this.mb=this.Oj=this.Ga=this.oa=this.Xa=this.Na=null;this.Fb=0;this.Wb=()=>{const b=_.PMc(this);b&&(this.oa.style.top=`${b.getBoundingClientRect().top}px`)};this.D9=()=>{if(this.isInitialized()){var b=_.PMc(this);if(b){var c;if((c=_.RMc(this))!=null&&c.Ds()){if(_.SMc()){var d=_.PMc(this).getBoundingClientRect().width,e=this.fq.Aa().size.height;const {maxWidth:h,
maxHeight:m}={maxWidth:d,maxHeight:e};d=$Mc(this);e=Math.round(h/d);e>m&&(e=m);var f;(f=ZMc(this))==null||f.style.setProperty("border-radius","16px");b.style.borderRadius="16px";d<=1&&(e=Math.min(Math.round(m*.67),950));b.style.height=`${e}px`;d<=1&&(b.style.width=`${e*d}px`);this.oa.style.height=`${e}px`;this.oa.style.width=`${e*d}px`;this.oa.style.top=`${b.getBoundingClientRect().top}px`;this.oa.style.left=`${b.getBoundingClientRect().left}px`}else{f=this.Oq()?this.Eb:this.Cb;c=(this.Oq()?this.Cb:
this.Eb)-52;const {maxWidth:h,maxHeight:m}={maxWidth:f,maxHeight:c};f=this.Oq();var g=!f&&$Mc(this)<=1?1.778:$Mc(this);let n=Math.round(h/g);n>m&&(n=m);f||(n*=.9);c=n;g*=n;b.style.height=`${c}px`;b.style.width=`${g}px`;if(b=_.PMc(this))f?(this.oa.style.removeProperty("clip-path"),(d=ZMc(this))==null||d.style.removeProperty("border-radius"),b.style.removeProperty("border-radius")):((e=ZMc(this))==null||e.style.setProperty("border-radius","16px"),b.style.borderRadius="16px");this.oa.style.left="50%";
this.oa.style.transform="translate(-50%, 0)";this.oa.style.height=`${c}px`;this.oa.style.width=`${g}px`}_.qG(this,"ZVbNQe")}}}};this.La=()=>{this.D9();this.Oq()?(_.qG(this,"x5gMP",1),_.OMc()&&_.JMc(this.Ja)&&_.MMc(this.Ja)&&(_.qG(this,"D8UFDb"),_.LMc(this.Ja))):(_.qG(this,"x5gMP",2),!_.SMc()&&_.OMc()&&_.JMc(this.Ja)&&!_.MMc(this.Ja)&&(_.qG(this,"f2KIuf"),this.Ga&&XMc(this.Ga)));_.TMc()&&_.qG(this,"pwISFb");YMc(this)};this.fq=a.service.fq;this.Aa=a.service.window.get();this.Ja=new _.hj(this.Aa.document);
this.Ea=this.Aa.matchMedia("(orientation: portrait)");this.Ix=a.service.Ix;this.Eb=Math.min(this.Aa.innerWidth,this.Aa.innerHeight);this.Cb=Math.max(this.Aa.innerWidth,this.Aa.innerHeight);this.yb=()=>{document.visibilityState==="hidden"&&_.qG(this,"ICrPLb")}}Oq(){return this.Ea.matches&&!_.SMc()}rb(a){this.Oj=a;this.oa&&a.Ea(this).listen(()=>{YMc(this)})}scrollTo(a){this.Oj&&this.Oj.scrollTo(a)}hb(a){this.Na=a}kb(a){this.Sa=a}isInitialized(){return!!this.oa&&!!this.oa.firstChild&&(!!this.Na||!!this.Sa||
!!this.mb)}uc(){if(this.isInitialized()){var a;(a=_.RMc(this))!=null&&a.Ds()?(_.aNc(this),this.D9()):_.bNc(this)}}Pb(a){$Mc(this)<=1&&a&&(a.style.height="764px")}};_.Gh(_.is,_.rG);
_.OMc=()=>!0;
_.SMc=()=>!0;
_.l();
_.nG=function(a){_.mG=a;_.$e(document.body,"MDuPYe",!a)};_.mG=!1;
_.k("BYwJlf");
_.pMc=window.agsa_ext;_.oG=()=>_.pMc&&_.pMc.getScrollTop&&_.pMc.getScrollTop()||0;_.qMc=!1;
_.l();
_.k("RBPODc");
var sMc=function(a,b){b=Math.max(b,0);let c,d;a===document.body||a===document.documentElement?(d=window.pageYOffset,c=(e,f)=>{window.scrollTo(window.pageXOffset,f.Gqa)}):(d=a.scrollTop,c=(e,f)=>{a.scrollTop=f.Gqa});return rMc(c,d,b)},rMc=function(a,b,c){const d=c-b;return(new _.eSb(200,(e,f)=>{f.Gqa=b+d*e},a)).start()};var tMc,uMc,zMc,AMc,yMc,wMc,vMc,CMc;tMc=class extends _.Xx{constructor(){super(...arguments);this.Aa=!1}};uMc=class{constructor(a){this.window=a}get(){return this.window}getDocument(){return this.window.document}find(a){return(new _.sp(this.window.document.documentElement)).find(a)}};_.xMc=function(a){let b=vMc.get(a);b||(b=new wMc(a),vMc.set(a,b));return b};
zMc=function(a,b,c=!0){return _.kf(function*(){if(c){var d=b+_.oG();if(a.oa.scrollTop!==d)return yMc()?new Promise(e=>{a.oa.scrollTo({top:d,behavior:"smooth"});let f=0;const g=()=>{a.oa.scrollTop===d?e():f++>10?(a.oa.scrollTop=d,e()):setTimeout(g,100)};setTimeout(g,100)}):sMc(a.oa,d)}else a.oa.scrollTop=b+_.oG(),yield new Promise(e=>void setTimeout(e,0))})};AMc=function(a,b){const c=_.iv(a).Yb(d=>{d=new tMc(d.scrollTop-_.oG(),d.velocity,d.oa);d.Aa=a.Aa;b(d)}).qh().build();a.Oj.oa(c);return c};
yMc=function(){return _.Ki(()=>"scrollBehavior"in document.documentElement.style)()};
wMc=class{constructor(a){this.Aa=!1;let b;((b=a.constructor)==null?void 0:b.name)==="Window"?(this.Oj=new _.Yx(new uMc(a)),this.oa=_.tua(new _.hj(a.document)),_.BMc&&"scrollRestoration"in window.history&&(a.history.scrollRestoration="manual")):(this.Oj=new _.Yx(a),this.oa=a)}scrollTo(a,b=!0){const c=this;return _.kf(function*(){c.Aa=!0;yield zMc(c,a,b);c.Aa=!1})}Ea(a){const b=new CMc(this);a&&_.Ci(a,b);return b}getScrollTop(){return this.Oj.getScrollTop()-_.oG()}Yv(){return this.oa.scrollTop-_.oG()}};
_.BMc=!0;vMc=new Map;CMc=class extends _.Ff{constructor(a){super();this.Oj=a;this.Yd=[]}listen(a){this.Yd.push(AMc(this.Oj,a))}Bd(){for(const a of this.Yd)this.Oj.Oj.Ea(a);this.Yd=[]}};
_.BMc=!1;
_.l();
_.k("qMBFFe");
_.Pwm=function(a,b){if(!_.Tt(a.Ko.oa())&&b!==a.Ga){a.Ga=b;var c=a.document.documentElement,d=a.document.body;b?(_.$o(c,"overscrollBehaviorY",a.Na),_.$o(d,"overscrollBehaviorY",a.La),_.$o(d,"overflow",a.Ja)):(a.Na=_.ap(c,"overscrollBehaviorY"),a.La=_.ap(d,"overscrollBehaviorY"),a.Ja=_.ap(d,"overflow"),_.$o(c,"overscrollBehaviorY","none"),_.$o(d,"overscrollBehaviorY","none"),_.$o(d,"overflow","hidden"));a=[...a.document.querySelectorAll("#kO001e,#gsr,header"),_.kj("z1Vi9d"),_.kj("Lj9fsd")];for(const e of a)e&&
_.$o(e,{visibility:b?"":"hidden"})}};
_.Qwm=class extends _.At{static Za(){return{service:{viewport:_.vw,window:_.jv,Fma:_.B5l,config:_.dy}}}constructor(a){super();this.wd=null;this.Ga=!0;this.Na=this.La=this.Ja="";this.oa=0;this.fq=a.service.viewport;this.ri=a.service.window;this.Ea=a.service.Fma;this.Ko=a.service.config;this.Oj=_.xMc(this.ri.get());this.document=this.ri.get().document;this.Aa=_.kj("SDsPCf")||this.document.querySelector("#gsr")}Sa(a=null){if(!_.Tt(this.Ko.oa()))if(a){var b=this.Aa&&this.Aa.querySelector(`[data-tbnid="${a}"] img.rg_i`);
!b&&a.startsWith("sv-")&&(b=this.Aa&&this.Aa.querySelector(`[data-tbnid="${a}"] img`));b&&(a=_.mp(b),b=this.fq.Aa().size.height,a.top&&(a.top+a.height>this.oa+b||a.top<this.oa)&&(this.oa=a.top-b/2+a.height/2),this.Oj.oa.scrollTop=this.oa+_.oG())}else this.Oj.oa.scrollTop=this.oa+_.oG()}enterBasicMode(){_.Tt(this.Ko.oa())||this.Ea.enterBasicMode()}exitBasicMode(){_.Tt(this.Ko.oa())||this.Ea.exitBasicMode()}restoreToPreviousState(){_.Tt(this.Ko.oa())||this.Ea.restoreToPreviousState()}};_.Gh(_.A7a,_.Qwm);
_.Qwm.prototype.Sa=()=>{};
_.l();
_.j6d=class extends _.HTc{constructor(a,b){super();this.open=a;this.close=b}};
_.k("ZfBJ7b");
var fym,gym,hym,iym,jym,kym,lym,mym,nym,oym,pym,qym,rym,sym,tym,uym;_.BRb.prototype.Ga=_.ca(142,function(){this.state.Ya.resolve();_.Sx(this.state.Jf,"uvpcot")});_.Tx.prototype.Ga=_.ca(141,function(a){let b;(b=this.oa.get(a))==null||b.Ga()});var eym=class extends _.q{constructor(a){super(a)}};eym.prototype.qb="mRi2Le";fym=function(a){return _.z(a,83)};
gym=function(a){return _.kf(function*(){yield a.Ea;{let c;var b=(c=a.getScope((0,_.YMb)(1)))!=null?c:a.getScope((0,_.YMb)(10));b=b!=null?b:a.getScope((0,_.YMb)(4));if(!b)throw Error("le");}return b})};hym=function(a){let b;return(b=a.Vq)==null?void 0:_.z(b,11)};iym=function(a,b){return _.sh(a,7,b)};jym=function(a,b){typeof b!=="undefined"?a.state.Jf.Xx("uvphct",b):_.Sx(a.state.Jf,"uvphct");a.state.Ja=!0;a.state.Xa.resolve()};
kym=function(a,b){const c=a.oa.get(b);(c==null?0:c.state.Jf.oa.startTime!=null&&!c.state.Ea)?c.state.Jf.oa.startTime==null||c.state.Ea||(c.state.Ea=_.Qx(c.state.Jf.oa.elapsedTime())):a.oa.delete(b)};lym=function(a,b){return(a=a.oa.get(b))?_.muc(a):1};mym=function(a,b){a.window.visualViewport&&a.window.visualViewport.addEventListener("resize",b)};nym=function(a){let b,c;return(c=(b=a.window.visualViewport)==null?void 0:b.pageLeft)!=null?c:0};
oym=function(a){if(a.Ka().getData("bp").Sb()){var b=_.Of(a.Ka().getData("bp"),0),c=a.xta;let d,e;const f=(e=(d=c.window.visualViewport)==null?void 0:d.scale)!=null?e:c.oa();b/=Math.round(f*100)/100;a.Ka().setStyle({top:`${b}px`,height:`calc(100% - ${24+b}px)`})}_.pp(a.Ka().el())&&nym(a.xta)<0&&(b=Math.abs(nym(a.xta)),a.Ka().setStyle({left:`${4+b}px`}))};pym=function(a,b){return _.kf(function*(){return yield _.Ep(a,b.el())})};
qym=function(a){a=new _.sp(a);a.Xb("jsname")!=="Z9MBEf"&&(a=_.Mu(a,"Z9MBEf").first());if(!a)throw Error("Fr");return a};rym=function(a){return _.kf(function*(){try{let b;yield(b=a.fT)==null?void 0:b.Cr()}catch(b){}})};sym=function(a,b){return _.kf(function*(){const c=yield a.xma(b);let d,e;const f=(e=c==null?void 0:(d=c.oa)==null?void 0:_.VFb(d,b.Ea||b.Aa))!=null?e:null;return{scope:c,match:f}})};
tym=function(a,b,c,d,e,f,g,h){return _.kf(function*(){const m=yield _.Pe(_.kla(_.rbb,void 0,a.Mj())),n=a.Via.Aj();var p,t,v;const x=(v=e==null?void 0:(p=e.Yq)==null?void 0:(t=p.Mk())==null?void 0:t.getViewerType())!=null?v:0;v=a.Ka().wb();p=_.Nx(a.Xc,()=>m.render({query:b,bOb:c,JBb:d,NDa:e.NDa,clusterId:e.clusterId,J_:n,Yda:!e.NMb,PJb:a.Ka().el().clientHeight,Xn:x,CBb:!0}),{Zc:f.Zc||void 0,SF:_.oxc()});var y=(t=f.Ga())?lym(a.Ml,t):1,A=_.luc(_.kuc(iym(_.juc(f.Y0||a.Y0(x,f.yu)),hym(a.hK)),g),h);const D=
p.querySelector("[jsname=CGzTgf]");y=yield _.ruc(a.X$,{Wa:e.Wa,Yba:a.nH(),Yq:e.Yq,isActive:!0,Dr:A},{Mc:f.Mc||void 0,Zc:_.dh(D,3),Jq:_.rxc(f.Jq,y),SF:_.oxc()});A="";const H=y.querySelector("[aria-label]");if(H){var M;A=(M=H.getAttribute("aria-label"))!=null?M:""}if(A.length===0&&f.sourceElement&&(M=f.sourceElement.querySelector("[alt], [aria-label]"))){var U,T;A=(T=(U=M.getAttribute("aria-label"))!=null?U:M.getAttribute("alt"))!=null?T:""}A.length>0?(p.setAttribute("role","dialog"),p.setAttribute("aria-label",
A)):(p.setAttribute("role",""),p.setAttribute("aria-label",""));if(U=f.MAa?y:null)U.style.visibility="hidden";D.appendChild(y);v.appendChild(p);t&&(kym(a.Ml,t),a.Ml.oa.has(t),a.Ml.Aa(t,D));_.Tt(a.Ko.oa())&&a.kC&&_.$o(a.kC,"visibility","hidden");if(T=yield pym(a,qym(p))){T.Od({element:f.sourceElement});var Z,ia,la;a.cab=(la=(Z=e.Me)==null?void 0:(ia=Z.Pc())==null?void 0:_.r(ia,eym,24))!=null?la:null;a.document.dispatchEvent(new CustomEvent("viewerOpened"));Z=_.yo;a.oca&&Z&&!a.Bi.isOpen(Z)?(_.$o(Z,
"position","absolute"),yield a.Bi.open(Z,a.a6(f,p,t,y,U))):yield a.xda(p,t,y,U);t&&a.Ml.Ga(t);_.tj(a.kC);a.kC=p;a.fT=T;a.Fi.D9()}else _.Jb(Error("Ir"))})};uym=function(a,b){(a=a.kC)&&_.$e(a,b.type,b.data)};
_.z$=class extends _.Yu{static Za(){return{service:{chrome:_.by,config:_.dy,Ml:_.Tx,mY:_.HU,Vq:_.fNb,XXa:_.gbm,Nqa:_.eJd,Qb:_.Jx,Uc:_.Ox,qO:_.rTb,k_a:_.Qwm,stream:_.dNb,Q1a:_.uuc,Of:_.ww,window:_.jv,visualViewport:_.fJd,cC:_.rG,i6:_.$Mb,iB:_.esc,overlay:_.jH},model:{Uia:_.TMb}}}constructor(a){super();this.BTa=this.cab=this.fT=this.kC=null;this.window=a.service.window.get();this.document=a.service.window.getDocument();this.chrome=a.service.chrome;this.Ko=a.service.config;this.RDa=a.service.Nqa;this.aU=
a.service.i6;this.hK=a.service.Vq;this.YQ=a.service.mY;this.Db=a.service.Qb;this.qO=a.service.qO;this.Via=a.model.Uia;this.X$=a.service.Q1a;this.Of=a.service.Of;this.Fi=a.service.cC;this.wd=null;this.Xc=a.service.Uc;this.JR=a.service.k_a;this.cq=a.service.stream;this.yfa=a.service.XXa;this.Ml=a.service.Ml;this.kC=(new _.qp([this.document])).find("[jsname=Z9MBEf]").el();this.xta=a.service.visualViewport;this.fP=a.service.iB;this.Bi=a.service.overlay;(this.oca=!this.Of.IH())||_.Te(this.window.document.body,
"R6Slyc",()=>{this.kC&&this.Bza(this.kC)});fym(this.Ko.oa())&&(oym(this),mym(this.xta,()=>{oym(this)}));this.Rh(Promise.all([this.sW(),this.tW(),this.ujb()]))}sW(){return _.kf(function*(){})}tW(){return _.kf(function*(){})}ujb(){const a=this;return _.kf(function*(){a.kC&&(a.fT=yield pym(a,qym(a.kC)))})}RP(){return this.YQ.RP(this.Ka().el())}yPa(a){var b=this.fP,c=a.data.Mk(),d=this.nH();a=a.data.wk();_.dsc(b,c,d,a)}RAb(a){const b=this;return _.kf(function*(){var c=a.data;b.BTa=c;if(!c.Ja){var d=b.cq.streams.get(c.yu||
""),e=(d==null?void 0:d.zi())||0,f,g=(d==null?void 0:(f=d.Aa())==null?void 0:f.length)||0;f=e>0;e=e<g-1;g=c.Aa;var h=c.Ea;if(g)if(yield rym(b),(d=c.Ga())&&b.Ml.Ea(d),b.yfa.reset(),d=yield sym(b,c),d.match){var m=d.scope,n=d.match,p=n.bH;n=n.result;let t=void 0,v;if((v=n.Me())==null?0:v.hasExtension(_.Hvc))t=_.Fvc(_.yl(n.Me(),_.Hvc));b.Fi.kb(t);yield tym(b,b.Via.Aj().getQuery()||"",h||g,h?"imgdii":"imgrc",{Wa:n.Uq(),clusterId:c.clusterId||p.id(),NMb:d,Me:n.Me(),NDa:m.id,Yq:t},c,f,e);b.Fi.hb(b.Ka().el().querySelector("[jsname=CGzTgf]"))}else c=
"Viewer",b.Of.IH()?c="Standalone Viewer":(f=(0,_.Ut)(),_.z(f,117)&&(c="IU Viewer")),f=((m=d.scope)==null?void 0:m.payload().getType())||null,_.Jb(Error("Gr`"+c+"`"+g+"`"+h+"`"+f));else c.oa&&c.yu?(yield rym(b),(g=c.Ga())&&b.Ml.Ea(g),b.yfa.reset(),yield _.aNb(b.cq,c.yu),g=_.cNb(b.cq,c.yu,c.oa),g.callback?(h=g.callback.XP(),b.Fi.kb(g.callback),yield tym(b,b.Via.Aj().getQuery()||"",c.oa,"vhid",{Wa:h,Me:(p=h.Gb())==null?void 0:_.yl(p,_.zn),Yq:g.callback,NDa:g.stream.oa()},c,f,e),b.Fi.hb(b.Ka().el().querySelector("[jsname=CGzTgf]")),
d&&d.oa()==="regis"&&_.$e(b.document,"sGvq8c",d.Yc())):_.Jb(Error("Hr`"+c.yu+"`"+c.oa))):(c.Mc&&_.Ix(b.Db,{Mc:c.Mc}),c=_.yo,b.oca&&c?b.kC&&b.Bi.close(c):b.kC&&(yield b.KIa()))}})}KIa(){const a=this;return _.kf(function*(){_.bNc(a.Fi);var b,c;const d=a.oca?null:_.dJd(a.RDa,(c=(b=a.BTa)==null?void 0:b.Na)!=null?c:null);b=null;d&&(b=a.yfa,c=d.el(),b.oa=c,b=_.Le(d.el(),d.el(),"sTFXNd")[0]);if(a.kC){try{yield a.Bza(a.kC)}catch(e){}_.tj(a.kC);a.kC=null;a.fT=null;a.cab=null}else a.JR.restoreToPreviousState();
b&&_.Tt(a.Ko.oa())&&b.focus()})}xma(a){return a.Ea?(a=this.aU.xma(a.Aa,a.Sa||""))?Promise.resolve(a):Promise.resolve(null):gym(this.aU)}nH(){var a=this.RP().width;var b=(_.Tt(this.Ko.oa())?0:16)-2*_.jnf();return a+b}a6(a,b,c,d,e){if(_.Tt(this.Ko.oa())){const f=_.zTc(_.uTc(_.ETc(new _.GTc,1),1,{replace:[5,7]}),127);a.sourceElement&&_.FTc(f,a.sourceElement);a=f}else a=_.BTc(_.CTc(_.zTc(new _.DTc,998)),2);return _.xTc(_.tTc(_.yTc(_.vTc(_.kH(a,this.Lja.bind(this)),[2]),!0),6),new vym(()=>this.xda(b,c,
d,e),()=>this.KIa()))}Lja({eventType:a,f9a:b}){b.then(()=>{this.fT&&this.fT.Vh()});if(a===0){let c;(c=this.fT)==null||c.Ux();return!0}if(!this.fT)throw Error("Jr");this.fT.od(5);return!1}yk(a){uym(this,a)}Lma(a){uym(this,a)}Jzb(){return this.fT}xda(a,b,c,d){const e=this;return _.kf(function*(){const f=yield pym(e,qym(a));if(f){e.JR.enterBasicMode();e.Ka().wb().style.setProperty("visibility","visible");if(d){_.$e(c,"DDMFCe");d.style.visibility="visible";f.ZK.wb().style.visibility="visible";var g,h;
if((g=f.W$)==null?0:(h=g.wb())==null?0:h.style)f.W$.wb().style.visibility="visible"}else yield f.zS();f.gC();e.vDa();_.Pwm(e.JR,!1);yield e.Gza();b&&(g=e.Ml,h=g.oa.get(b),(h==null?0:h.state.Jf.oa.startTime!=null&&!h.state.Ja)?h.state.Jf.oa.startTime!=null&&!h.state.Ja&&(h.state.Ga?h.state.Ea&&jym(h,h.state.Ea):jym(h)):g.oa.delete(b));yield f.dh();var m;e.document.dispatchEvent(new CustomEvent("viewerOpenFinished",{detail:{relatedImgViewer:f==null?void 0:(m=f.jn)==null?void 0:m.Ya()}}))}else _.Jb(Error("Kr"))})}Bza(a){const b=
this;return _.kf(function*(){_.bNc(b.Fi);_.Pwm(b.JR,!0);b.JR.restoreToPreviousState();const c=yield pym(b,qym(a));if(c){_.$e(b.document,"kyj0be",!1);b.document.dispatchEvent(new CustomEvent("viewerClosed"));var d;((d=b.BTa)==null?0:d.gga)?yield c.xt():yield c.oL();c.Od({element:null});yield b.Cza();_.Cp(window,"attn_viewer_close",!1,null);b.Ka().wb().style.visibility="hidden"}else _.Jb(Error("Lr"))})}Gza(){return Promise.resolve()}Cza(){return Promise.resolve()}Gma(a){uym(this,a)}Zqa(){}vDa(){}Y0(a,
b){b=b||"";b.indexOf("-")>0&&(b=b.substring(0,b.indexOf("-")));return _.Auc.includes(a)||_.Buc.includes(b)}};_.z$.prototype.$wa$fJBVee=function(){return this.vDa};_.z$.prototype.$wa$zfeGSe=function(){return this.Gma};_.z$.prototype.$wa$o1YwPc=function(){return this.Cza};_.z$.prototype.$wa$H11Ahd=function(){return this.Gza};_.z$.prototype.$wa$e73z6=function(){return this.Jzb};_.z$.prototype.$wa$onf9S=function(){return this.Lma};_.z$.prototype.$wa$mhSdVe=function(){return this.yk};
_.z$.prototype.$wa$mlmJSd=function(){return this.KIa};_.z$.prototype.$wa$zQYYb=function(){return this.RAb};_.z$.prototype.$wa$C6KsF=function(){return this.yPa};_.z$.prototype.$wa$ysU6pb=function(){return this.ujb};_.z$.prototype.$wa$IaQd1e=function(){return this.tW};_.z$.prototype.$wa$npAYtf=function(){return this.sW};var vym=class extends _.j6d{};_.av(_.ubb,_.z$);


_.z$.prototype.sW=function(){const a=this;return _.kf(function*(){var b=_.mg(_.fYa,a.Mj());const c=yield _.mg(_.eYa,a.Mj());b=yield b;const d=a.Ka();a.S_=c.create(a.window,b,d)})};_.z$.prototype.$wa$npAYtf=function(){return this.sW};_.z$.prototype.yk=()=>{};_.z$.prototype.$wa$mhSdVe=function(){return this.yk};_.z$.prototype.Zqa=function(a){this.S_.Zqa(a)};
_.z$.prototype.Lma=function(){if(this.S_)this.S_.Lma();else{var a=this.window,b=this.Ka();a=a.innerWidth;a=a<1264?368:Math.min(368+a-1264,569);a>368?b.addClass("sUDUrf").removeClass("WdLoq"):b.addClass("WdLoq").removeClass("sUDUrf");b.setStyle("width",`${a}px`)}let c;(c=this.Fi)==null||c.D9()};_.z$.prototype.$wa$onf9S=function(){return this.Lma};_.z$.prototype.Gza=function(){if(this.S_)return this.S_.xda();this.Ka().setStyle("display","block");return Promise.resolve()};_.z$.prototype.$wa$H11Ahd=function(){return this.Gza};
_.z$.prototype.Cza=function(){if(this.S_)return this.S_.Bza();this.Ka().setStyle("display","none");return Promise.resolve()};_.z$.prototype.$wa$o1YwPc=function(){return this.Cza};_.z$.prototype.Gma=function(){this.S_.Gma()};_.z$.prototype.$wa$zfeGSe=function(){return this.Gma};


_.l();
});
// Google Inc.
